/* Same Street: the homes, in the order they are played.
   Every home was visited and photographed by Dollar Street, a Gapminder project.
   Free material from GAPMINDER.ORG, CC-BY LICENSE (CC BY 4.0).

   "start" is day 1. The game shows home number ((day - 1) mod total), counted from "start".
   "low" and "high" are the two ends of the street, in dollars per adult per month.
   "house" is where the home stands on the street (1 to 100), worked out from Dollar Street's income figure.
   "income" is that figure, rounded. "by" is the photographer, "year" the year of the visit.
   "page" is the family's page: https://www.gapminder.org/dollar-street/families/<page>
   The three photos of a home are photos/<id>-1.jpg (outside), -2.jpg (cooking), -3.jpg (sleeping).
   Once real players have albums, the "id" of a home must never change. */
window.TURNSOUT_DATA = window.TURNSOUT_DATA || {};
window.TURNSOUT_DATA["same-street"] = {
  "start": "2026-10-03",
  "low": 25,
  "high": 15000,
  "homes": [
    {"id": "f263", "house": 57, "income": 910, "country": "Sri Lanka", "region": "Asia", "colour": "red", "year": 2018, "by": "Chris Dade", "page": "family-263"},
    {"id": "f409", "house": 83, "income": 5100, "country": "United States", "region": "The Americas", "colour": "green", "year": 2019, "by": "Raashi Saxena", "page": "family-409"},
    {"id": "f100", "house": 12, "income": 50, "country": "Papua New Guinea", "region": "Asia", "colour": "red", "year": 2015, "by": "Johan Eriksson", "page": "family-100"},
    {"id": "f369", "house": 75, "income": 3000, "country": "Austria", "region": "Europe", "colour": "violet", "year": 2019, "by": "Raashi Saxena", "page": "family-369"},
    {"id": "f87", "house": 28, "income": 150, "country": "Nepal", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-87"},
    {"id": "f353", "house": 64, "income": 1500, "country": "Colombia", "region": "The Americas", "colour": "green", "year": 2019, "by": "Daniel Salazar", "page": "family-353"},
    {"id": "f172", "house": 94, "income": 10000, "country": "Ukraine", "region": "Europe", "colour": "violet", "year": 2015, "by": "Zoriah Miller", "page": "family-172"},
    {"id": "f7", "house": 8, "income": 40, "country": "Haiti", "region": "The Americas", "colour": "green", "year": 2014, "by": "Zoriah Miller", "page": "family-7"},
    {"id": "f132", "house": 33, "income": 200, "country": "Tunisia", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-132"},
    {"id": "f227", "house": 78, "income": 3600, "country": "Netherlands", "region": "Europe", "colour": "violet", "year": 2016, "by": "Chenna Kuypers (Global Exploration)", "page": "family-227"},
    {"id": "f75", "house": 17, "income": 68, "country": "Cote d'Ivoire", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-75"},
    {"id": "f365", "house": 63, "income": 1400, "country": "Russia", "region": "Europe", "colour": "violet", "year": 2019, "by": "Alexey Fedorov", "page": "family-365"},
    {"id": "f21", "house": 39, "income": 300, "country": "Cambodia", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-21"},
    {"id": "f394", "house": 82, "income": 4600, "country": "Spain", "region": "Europe", "colour": "violet", "year": 2019, "by": "Omar Havana", "page": "family-394"},
    {"id": "f196", "house": 19, "income": 78, "country": "Bangladesh", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-196"},
    {"id": "f295", "house": 66, "income": 1600, "country": "Nigeria", "region": "Africa", "colour": "blue", "year": 2018, "by": "Keke Boro", "page": "family-295"},
    {"id": "f166", "house": 3, "income": 29, "country": "India", "region": "Asia", "colour": "red", "year": 2015, "by": "Zoriah Miller", "page": "family-166"},
    {"id": "f380", "house": 50, "income": 600, "country": "Ethiopia", "region": "Africa", "colour": "blue", "year": 2019, "by": "Netsi F. Belay", "page": "family-380"},
    {"id": "f272", "house": 82, "income": 4600, "country": "India", "region": "Asia", "colour": "red", "year": 2018, "by": "Akshay Jain", "page": "family-272"},
    {"id": "f265", "house": 61, "income": 1200, "country": "Brazil", "region": "The Americas", "colour": "green", "year": 2018, "by": "Aleksander Schoeffel", "page": "family-265"},
    {"id": "f19", "house": 40, "income": 310, "country": "Cambodia", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-19"},
    {"id": "f425", "house": 88, "income": 7100, "country": "France", "region": "Europe", "colour": "violet", "year": 2020, "by": "Omar Havana", "page": "family-425"},
    {"id": "f401", "house": 31, "income": 180, "country": "Kenya", "region": "Africa", "colour": "blue", "year": 2019, "by": "Zoriah Miller", "page": "family-401"},
    {"id": "f8", "house": 69, "income": 2100, "country": "Sweden", "region": "Europe", "colour": "violet", "year": 2014, "by": "Moa Karlberg", "page": "family-8"},
    {"id": "f137", "house": 41, "income": 320, "country": "Thailand", "region": "Asia", "colour": "red", "year": 2015, "by": "Jonathan Taylor", "page": "family-137"},
    {"id": "f312", "house": 86, "income": 6300, "country": "Romania", "region": "Europe", "colour": "violet", "year": 2018, "by": "Catalin Georgescu", "page": "family-312"},
    {"id": "f120", "house": 13, "income": 53, "country": "Rwanda", "region": "Africa", "colour": "blue", "year": 2015, "by": "Johan Eriksson", "page": "family-120"},
    {"id": "f54", "house": 49, "income": 560, "country": "Indonesia", "region": "Asia", "colour": "red", "year": 2015, "by": "Gito Nirboyo", "page": "family-54"},
    {"id": "f1", "house": 81, "income": 4300, "country": "Colombia", "region": "The Americas", "colour": "green", "year": null, "by": "Isabella Sanchez", "page": "family-1"},
    {"id": "f50", "house": 58, "income": 1000, "country": "Indonesia", "region": "Asia", "colour": "red", "year": 2015, "by": "Gito Nirboyo", "page": "family-50"},
    {"id": "f18", "house": 3, "income": 28, "country": "Burundi", "region": "Africa", "colour": "blue", "year": 2015, "by": "Johan Eriksson", "page": "family-18"},
    {"id": "f347", "house": 80, "income": 4000, "country": "Italy", "region": "Europe", "colour": "violet", "year": 2019, "by": "Giorgio Benatti", "page": "family-347"},
    {"id": "f259", "house": 45, "income": 420, "country": "Mongolia", "region": "Asia", "colour": "red", "year": 2018, "by": "Yrsa Kleijkers", "page": "family-259"},
    {"id": "f285", "house": 71, "income": 2400, "country": "Netherlands", "region": "Europe", "colour": "violet", "year": 2018, "by": "Robbert Ploum (Global Exploration)", "page": "family-285"},
    {"id": "f184", "house": 94, "income": 10000, "country": "China", "region": "Asia", "colour": "red", "year": 2015, "by": "Jonathan Taylor", "page": "family-184"},
    {"id": "f175", "house": 53, "income": 720, "country": "Romania", "region": "Europe", "colour": "violet", "year": 2015, "by": "Roland Zsigmond", "page": "family-175"},
    {"id": "f435", "house": 27, "income": 130, "country": "Pakistan", "region": "Asia", "colour": "red", "year": 2020, "by": "Asif Raza", "page": "family-435"},
    {"id": "f150", "house": 83, "income": 4900, "country": "Sweden", "region": "Europe", "colour": "violet", "year": 2015, "by": "Moa Karlberg", "page": "family-150"},
    {"id": "f128", "house": 43, "income": 380, "country": "Thailand", "region": "Asia", "colour": "red", "year": 2015, "by": "Jonathan Taylor", "page": "family-128"},
    {"id": "f71", "house": 11, "income": 48, "country": "Liberia", "region": "Africa", "colour": "blue", "year": 2015, "by": "Johan Eriksson", "page": "family-71"},
    {"id": "f179", "house": 89, "income": 7400, "country": "Jordan", "region": "Asia", "colour": "red", "year": 2015, "by": "Zoriah Miller", "page": "family-179"},
    {"id": "f314", "house": 30, "income": 160, "country": "Tanzania", "region": "Africa", "colour": "blue", "year": 2018, "by": "Sandra Merks (Global Exploration)", "page": "family-314"},
    {"id": "f262", "house": 48, "income": 510, "country": "Pakistan", "region": "Asia", "colour": "red", "year": 2018, "by": "Tooba Zia", "page": "family-262"},
    {"id": "f371", "house": 84, "income": 5200, "country": "Czech Republic", "region": "Europe", "colour": "violet", "year": 2019, "by": "Michal Sikora", "page": "family-371"},
    {"id": "f201", "house": 10, "income": 45, "country": "Myanmar", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-201"},
    {"id": "f267", "house": 46, "income": 460, "country": "Brazil", "region": "The Americas", "colour": "green", "year": 2018, "by": "Karine Gomes", "page": "family-267"},
    {"id": "f350", "house": 77, "income": 3300, "country": "Turkey", "region": "Europe", "colour": "violet", "year": 2019, "by": "Dila Gokce Kuzu", "page": "family-350"},
    {"id": "f155", "house": 55, "income": 830, "country": "Lebanon", "region": "Asia", "colour": "red", "year": 2015, "by": "Johan Eriksson", "page": "family-155"},
    {"id": "f148", "house": 32, "income": 180, "country": "Bolivia", "region": "The Americas", "colour": "green", "year": 2015, "by": "Zoriah Miller", "page": "family-148"},
    {"id": "f296", "house": 67, "income": 1800, "country": "Netherlands", "region": "Europe", "colour": "violet", "year": 2018, "by": "Dagmar van Beek (Global Exploration)", "page": "family-296"},
    {"id": "f131", "house": 6, "income": 34, "country": "Zimbabwe", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-131"},
    {"id": "f221", "house": 51, "income": 620, "country": "Palestine", "region": "Asia", "colour": "red", "year": 2016, "by": "Eman Jomaa", "page": "family-221"},
    {"id": "f392", "house": 81, "income": 4300, "country": "Spain", "region": "Europe", "colour": "violet", "year": 2019, "by": "Omar Havana", "page": "family-392"},
    {"id": "f217", "house": 59, "income": 1000, "country": "South Korea", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-217"},
    {"id": "f118", "house": 4, "income": 30, "country": "Malawi", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-118"},
    {"id": "f153", "house": 82, "income": 4600, "country": "United States", "region": "The Americas", "colour": "green", "year": 2015, "by": "Zoriah Miller", "page": "family-153"},
    {"id": "f11", "house": 54, "income": 780, "country": "China", "region": "Asia", "colour": "red", "year": 2014, "by": "Jonathan Taylor", "page": "family-11"},
    {"id": "f101", "house": 16, "income": 64, "country": "Malawi", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-101"},
    {"id": "f190", "house": 62, "income": 1300, "country": "Lithuania", "region": "Europe", "colour": "violet", "year": 2015, "by": "Konstatins Sigulis", "page": "family-190"},
    {"id": "f23", "house": 2, "income": 27, "country": "Burundi", "region": "Africa", "colour": "blue", "year": 2015, "by": "Johan Eriksson", "page": "family-23"},
    {"id": "f177", "house": 47, "income": 480, "country": "Ukraine", "region": "Europe", "colour": "violet", "year": 2015, "by": "Zoriah Miller", "page": "family-177"},
    {"id": "f38", "house": 15, "income": 60, "country": "Cambodia", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-38"},
    {"id": "f427", "house": 74, "income": 2700, "country": "France", "region": "Europe", "colour": "violet", "year": 2020, "by": "Omar Havana", "page": "family-427"},
    {"id": "f124", "house": 24, "income": 110, "country": "Tunisia", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-124"},
    {"id": "f151", "house": 52, "income": 650, "country": "Bulgaria", "region": "Europe", "colour": "violet", "year": 2015, "by": "Boryana Katsarova", "page": "family-151"},
    {"id": "f145", "house": 9, "income": 41, "country": "Zimbabwe", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-145"},
    {"id": "f402", "house": 38, "income": 270, "country": "Guatemala", "region": "The Americas", "colour": "green", "year": 2019, "by": "Cynthia Ortiz", "page": "family-402"},
    {"id": "f307", "house": 65, "income": 1500, "country": "Netherlands", "region": "Europe", "colour": "violet", "year": 2018, "by": "Jennifer Beer (Global Exploration)", "page": "family-307"},
    {"id": "f117", "house": 17, "income": 72, "country": "Nigeria", "region": "Africa", "colour": "blue", "year": 2015, "by": "Johan Eriksson", "page": "family-117"},
    {"id": "f243", "house": 81, "income": 4400, "country": "United States", "region": "The Americas", "colour": "green", "year": 2017, "by": "Sarah Diamond", "page": "family-243"},
    {"id": "f338", "house": 42, "income": 350, "country": "Cameroon", "region": "Africa", "colour": "blue", "year": 2018, "by": "Rosine Fidele", "page": "family-338"},
    {"id": "f416", "house": 22, "income": 96, "country": "Nepal", "region": "Asia", "colour": "red", "year": 2019, "by": "Omar Havana", "page": "family-416"},
    {"id": "f99", "house": 87, "income": 6300, "country": "Mexico", "region": "The Americas", "colour": "green", "year": 2015, "by": "Daniela Ortiz", "page": "family-99"},
    {"id": "f323", "house": 35, "income": 230, "country": "Serbia", "region": "Europe", "colour": "violet", "year": 2018, "by": "Darko Rajkovic", "page": "family-323"},
    {"id": "f387", "house": 76, "income": 3100, "country": "Iran", "region": "Asia", "colour": "red", "year": 2019, "by": "Parisa Sayaari", "page": "family-387"},
    {"id": "f66", "house": 8, "income": 39, "country": "Haiti", "region": "The Americas", "colour": "green", "year": 2015, "by": "Zoriah Miller", "page": "family-66"},
    {"id": "f363", "house": 34, "income": 210, "country": "Ghana", "region": "Africa", "colour": "blue", "year": 2019, "by": "Maike Winters", "page": "family-363"},
    {"id": "f121", "house": 56, "income": 860, "country": "Philippines", "region": "Asia", "colour": "red", "year": 2015, "by": "Victrixia Montes", "page": "family-121"},
    {"id": "f55", "house": 23, "income": 110, "country": "Haiti", "region": "The Americas", "colour": "green", "year": 2015, "by": "Zoriah Miller", "page": "family-55"},
    {"id": "f301", "house": 81, "income": 4400, "country": "Pakistan", "region": "Asia", "colour": "red", "year": 2018, "by": "Tooba Zia", "page": "family-301"},
    {"id": "f106", "house": 60, "income": 1100, "country": "Mexico", "region": "The Americas", "colour": "green", "year": 2015, "by": "Joseph Ramirez", "page": "family-106"},
    {"id": "f96", "house": 20, "income": 86, "country": "Philippines", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-96"},
    {"id": "f257", "house": 79, "income": 3900, "country": "Brazil", "region": "The Americas", "colour": "green", "year": 2018, "by": "Leony Carvalho", "page": "family-257"},
    {"id": "f127", "house": 44, "income": 410, "country": "Thailand", "region": "Asia", "colour": "red", "year": 2015, "by": "Jonathan Taylor", "page": "family-127"},
    {"id": "f341", "house": 68, "income": 1800, "country": "Serbia", "region": "Europe", "colour": "violet", "year": 2019, "by": "Zoriah Miller", "page": "family-341"},
    {"id": "f140", "house": 25, "income": 120, "country": "Tunisia", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-140"},
    {"id": "f219", "house": 81, "income": 4500, "country": "South Korea", "region": "Asia", "colour": "red", "year": 2015, "by": "Luc Forsyth", "page": "family-219"},
    {"id": "f315", "house": 5, "income": 32, "country": "Tanzania", "region": "Africa", "colour": "blue", "year": 2018, "by": "Britte Van Beek (Global Exploration)", "page": "family-315"},
    {"id": "f154", "house": 70, "income": 2200, "country": "Sweden", "region": "Europe", "colour": "violet", "year": 2015, "by": "Moa Karlberg", "page": "family-154"},
    {"id": "f424", "house": 26, "income": 120, "country": "Sri Lanka", "region": "Asia", "colour": "red", "year": 2020, "by": "Raashi Saxena", "page": "family-424"},
    {"id": "f391", "house": 90, "income": 7600, "country": "Spain", "region": "Europe", "colour": "violet", "year": 2019, "by": "Omar Havana", "page": "family-391"},
    {"id": "f441", "house": 72, "income": 2400, "country": "Colombia", "region": "The Americas", "colour": "green", "year": 2021, "by": "Juanita Hernandez", "page": "family-441"},
    {"id": "f331", "house": 29, "income": 160, "country": "Indonesia", "region": "Asia", "colour": "red", "year": 2018, "by": "Global Exploration", "page": "family-331"},
    {"id": "f489", "house": 88, "income": 6700, "country": "Colombia", "region": "The Americas", "colour": "green", "year": 2022, "by": "Susana Arabia", "page": "family-489"},
    {"id": "f13", "house": 13, "income": 56, "country": "Burkina Faso", "region": "Africa", "colour": "blue", "year": 2015, "by": "Zoriah Miller", "page": "family-13"},
    {"id": "f289", "house": 73, "income": 2600, "country": "India", "region": "Asia", "colour": "red", "year": 2018, "by": "Pratiksha Biswal", "page": "family-289"},
    {"id": "f27", "house": 37, "income": 250, "country": "Bolivia", "region": "The Americas", "colour": "green", "year": 2015, "by": "Zoriah Miller", "page": "family-27"},
    {"id": "f225", "house": 82, "income": 4700, "country": "China", "region": "Asia", "colour": "red", "year": 2016, "by": "Jianxing Cheng", "page": "family-225"}
  ]
};
