"""The Club: the puzzles as they were written, before checking.

One entry per club. The rule is a plain yes-or-no fact about the real world:
true of every member, false of every outsider, today and in ten years.

  id        never changes once the puzzle is live
  topic     countries, places, animals, food, science, history, culture, sport
  sign      the rule as the club's sign shows it after the last candidate (at most 30 characters)
  stamp     a few words for the stamp in the album (at most 22 characters)
  members   three that are in the club, shown from the start
  outsiders two that are not, shown from the start
  door      five candidates in the order they come to the door: [name, True if it gets in]
  trap      which candidate (0 to 4) is the trap for the most tempting wrong rule, or None
  fact      one short true sentence shown after the reveal (at most 150 characters)

Writing rules: every name at most 24 characters, better under 17; British spelling; no rule about the spelling of names;
of the five candidates at least two get in and at least two do not; at most one trap.
Checked facts and sources live in facts.py. build.py writes the-club/puzzles.js from both.
"""

def P(id, topic, sign, stamp, members, outsiders, door, trap, fact):
    return dict(id=id, topic=topic, sign=sign, stamp=stamp, members=members, outsiders=outsiders,
                door=[[n, bool(i)] for n, i in door], trap=trap, fact=fact)

C = [
    # ------------------------------------------------------------------ countries
    P('left-traffic', 'countries', 'They drive on the left', 'Left-hand traffic',
      ['Japan', 'India', 'Australia'], ['France', 'Brazil'],
      [('Kenya', 1), ('Germany', 0), ('Thailand', 1), ('United States', 0), ('Indonesia', 1)], 0,
      "In all of them traffic keeps to the left. About a third of the world's people live in countries that do."),
    P('landlocked', 'countries', 'They have no sea coast', 'Landlocked',
      ['Switzerland', 'Mongolia', 'Bolivia'], ['Peru', 'Norway'],
      [('Ethiopia', 1), ('Jordan', 0), ('Nepal', 1), ('Chile', 0), ('Austria', 1)], 1,
      "None of them touches the sea. Ethiopia, with more than 100 million people, is the most populous country without a coast."),
    P('equator', 'countries', 'The equator crosses them', 'On the equator',
      ['Ecuador', 'Kenya', 'Indonesia'], ['Peru', 'India'],
      [('Brazil', 1), ('Mexico', 0), ('Uganda', 1), ('Malaysia', 0), ('Colombia', 1)], 3,
      "The equator runs through all of them. It crosses 13 countries, and Ecuador is even named after it."),
    P('time-zones', 'countries', 'More than one time zone', 'Many time zones',
      ['Russia', 'United States', 'Australia'], ['Japan', 'Germany'],
      [('China', 0), ('Canada', 1), ('Italy', 0), ('Brazil', 1), ('Indonesia', 1)], 0,
      "Each uses more than one time zone. China is about as wide as the United States but keeps a single one."),
    P('dollar', 'countries', 'Their money is the dollar', 'The dollar',
      ['Canada', 'Australia', 'Jamaica'], ['Mexico', 'United Kingdom'],
      [('New Zealand', 1), ('Japan', 0), ('Singapore', 1), ('Brazil', 0), ('Namibia', 1)], 4,
      "Each calls its money the dollar. The name goes back to the thaler, a silver coin first struck in Bohemia about 500 years ago."),
    P('portuguese', 'countries', 'Portuguese is official', 'Portuguese spoken',
      ['Brazil', 'Portugal', 'Angola'], ['Spain', 'Argentina'],
      [('Mozambique', 1), ('Mexico', 0), ('Cape Verde', 1), ('Chile', 0), ('Italy', 0)], None,
      "Portuguese is the official language of each. Brazil alone has more Portuguese speakers than all the other countries together."),
    P('hundred-million', 'countries', 'Over 100 million people', '100 million people',
      ['Nigeria', 'Bangladesh', 'Japan'], ['Canada', 'Australia'],
      [('Ethiopia', 1), ('Germany', 0), ('Mexico', 1), ('United Kingdom', 0), ('Philippines', 1)], 0,
      "More than 100 million people live in each of them. Bangladesh has more people than Russia."),
    P('mediterranean', 'countries', 'On the Mediterranean Sea', 'Mediterranean coast',
      ['Spain', 'Egypt', 'Turkey'], ['Germany', 'Iraq'],
      [('Portugal', 0), ('Tunisia', 1), ('Croatia', 1), ('Jordan', 0), ('Lebanon', 1)], 0,
      "Each has a coast on the Mediterranean Sea. Portugal has none: its whole coast faces the Atlantic."),
    P('arctic-circle', 'countries', 'The Arctic Circle crosses them', 'Arctic Circle',
      ['Norway', 'Russia', 'Canada'], ['United Kingdom', 'Poland'],
      [('Finland', 1), ('United States', 1), ('Estonia', 0), ('Sweden', 1), ('Japan', 0)], 1,
      "The Arctic Circle crosses each of them. North of that line the sun stays up all night at midsummer."),
    P('borders-brazil', 'countries', 'They border Brazil', "Brazil's neighbours",
      ['Argentina', 'Peru', 'Colombia'], ['Chile', 'Mexico'],
      [('Uruguay', 1), ('Ecuador', 0), ('France', 1), ('Venezuela', 1), ('Panama', 0)], 2,
      "Each shares a border with Brazil. So does France: French Guiana is part of France, and no French border is longer."),
    P('two-colour-flags', 'countries', 'Flags with two colours', 'Two-colour flags',
      ['Japan', 'Canada', 'Switzerland'], ['France', 'Germany'],
      [('Turkey', 1), ('Italy', 0), ('Poland', 1), ('Brazil', 0), ('Greece', 1)], None,
      "Each of these flags has just two colours. Japan's is a red disc on white: the rising sun."),
    P('monarchies', 'countries', 'A monarch is head of state', 'Monarchies',
      ['Spain', 'Thailand', 'Sweden'], ['Portugal', 'Italy'],
      [('Japan', 1), ('Germany', 0), ('Morocco', 1), ('France', 0), ('Netherlands', 1)], 0,
      "A king, queen or emperor is head of state in each. Japan's emperors form the oldest royal line still on a throne."),
    P('named-countries', 'countries', 'Named after a person', 'Named after people',
      ['Colombia', 'Bolivia', 'Philippines'], ['Argentina', 'Ecuador'],
      [('Saudi Arabia', 1), ('Costa Rica', 0), ('Mauritius', 1), ('Brazil', 0), ('Iceland', 0)], None,
      "Each is named after a person: Colombia after Columbus, Bolivia after Simón Bolívar, the Philippines after King Philip II of Spain."),
    # ------------------------------------------------------------------ cities and places
    P('olympic-hosts', 'sport', 'Hosted the Summer Olympics', 'Olympic hosts',
      ['Tokyo', 'Paris', 'Rio de Janeiro'], ['New York', 'Vienna'],
      [('Mexico City', 1), ('Toronto', 0), ('Sydney', 1), ('Chicago', 0), ('Barcelona', 1)], 3,
      "Each has hosted the Summer Olympic Games. Paris and London have each done so three times."),
    P('capitals', 'places', 'They are capital cities', 'Capital cities',
      ['Canberra', 'Ottawa', 'Ankara'], ['Sydney', 'Toronto'],
      [('Brasília', 1), ('Istanbul', 0), ('Wellington', 1), ('Auckland', 0), ('Abuja', 1)], 1,
      "Each is a capital, though a bigger city gets the fame. Australia's capital is Canberra, not Sydney."),
    P('former-capitals', 'places', 'They were once the capital', 'Former capitals',
      ['Rio de Janeiro', 'Istanbul', 'Kyoto'], ['Sydney', 'Shanghai'],
      [('Saint Petersburg', 1), ('Mumbai', 0), ('Melbourne', 1), ('Chicago', 0), ('Lagos', 1)], 2,
      "Each used to be its country's capital. Rio de Janeiro was Brazil's until Brasília took over in 1960."),
    P('high-capitals', 'places', 'Over 2,000 metres high', 'High capitals',
      ['Mexico City', 'Bogotá', 'Addis Ababa'], ['Lima', 'Madrid'],
      [('Quito', 1), ('Kathmandu', 0), ('La Paz', 1), ('Nairobi', 0), ('Santiago', 0)], 1,
      "Each lies more than 2,000 metres above the sea. La Paz, at about 3,600 metres, is the highest capital in the world."),
    P('below-sea-level', 'places', 'Below sea level', 'Below sea level',
      ['Dead Sea', 'Death Valley', 'Jericho'], ['Venice', 'Cairo'],
      [('Baku', 1), ('Miami', 0), ('Amsterdam', 1), ('Maldives', 0), ('Sea of Galilee', 1)], 0,
      "All lie below sea level. Baku, 28 metres under, is the lowest capital city in the world."),
    P('deserts', 'places', 'They are deserts', 'Deserts',
      ['Sahara', 'Gobi', 'Atacama'], ['Amazon', 'Siberia'],
      [('Kalahari', 1), ('Antarctica', 1), ('Serengeti', 0), ('Mojave', 1), ('Alps', 0)], 1,
      "They are deserts: places with almost no rain or snow. The biggest desert on Earth is Antarctica."),
    P('volcanoes', 'places', 'They are volcanoes', 'Volcanoes',
      ['Mount Fuji', 'Etna', 'Vesuvius'], ['Everest', 'Mont Blanc'],
      [('Kilimanjaro', 1), ('Matterhorn', 0), ('Krakatoa', 1), ('K2', 0), ('Mount St Helens', 1)], 0,
      "They are all volcanoes. So is Kilimanjaro, the highest mountain in Africa."),
    # ------------------------------------------------------------------ animals
    P('marsupials', 'animals', 'They are marsupials', 'Marsupials',
      ['Kangaroo', 'Koala', 'Opossum'], ['Panda', 'Sloth'],
      [('Wombat', 1), ('Platypus', 0), ('Tasmanian devil', 1), ('Dingo', 0), ('Wallaby', 1)], 1,
      "They are marsupials: their young are born tiny and most finish growing in a pouch. The platypus is not one; it lays eggs."),
    P('sea-mammals', 'animals', 'They are mammals', 'Mammals of the sea',
      ['Dolphin', 'Seal', 'Manatee'], ['Shark', 'Penguin'],
      [('Orca', 1), ('Whale shark', 0), ('Walrus', 1), ('Sea turtle', 0), ('Narwhal', 1)], 1,
      "They are mammals: they breathe air and feed their young with milk. The whale shark is a fish, the biggest of all."),
    P('flightless', 'animals', 'Birds that cannot fly', 'Flightless birds',
      ['Ostrich', 'Penguin', 'Kiwi'], ['Peacock', 'Swan'],
      [('Emu', 1), ('Turkey', 0), ('Cassowary', 1), ('Flamingo', 0), ('Kakapo', 1)], 1,
      "None of them can fly. The kakapo of New Zealand is the only parrot that cannot."),
    P('insects', 'animals', 'They are insects', 'Insects',
      ['Ant', 'Butterfly', 'Flea'], ['Spider', 'Snail'],
      [('Ladybird', 1), ('Scorpion', 0), ('Dragonfly', 1), ('Tick', 0), ('Centipede', 0)], 3,
      "They are insects, with six legs each. Spiders, scorpions and ticks have eight and are arachnids."),
    P('apes', 'animals', 'They are apes', 'Apes',
      ['Gorilla', 'Orangutan', 'Gibbon'], ['Baboon', 'Lemur'],
      [('Chimpanzee', 1), ('Macaque', 0), ('Human', 1), ('Mandrill', 0), ('Bonobo', 1)], 2,
      "They are apes, not monkeys: apes have no tail. Humans are apes too."),
    P('rodents', 'animals', 'They are rodents', 'Rodents',
      ['Mouse', 'Squirrel', 'Beaver'], ['Hedgehog', 'Bat'],
      [('Capybara', 1), ('Rabbit', 0), ('Porcupine', 1), ('Mole', 0), ('Guinea pig', 1)], 1,
      "They are rodents, with front teeth that never stop growing. The capybara is the biggest; the rabbit is not a rodent at all."),
    P('molluscs', 'animals', 'They are molluscs', 'Molluscs',
      ['Octopus', 'Snail', 'Oyster'], ['Crab', 'Starfish'],
      [('Squid', 1), ('Shrimp', 0), ('Slug', 1), ('Barnacle', 0), ('Mussel', 1)], 3,
      "They are molluscs. An octopus is a relative of the garden snail; a barnacle is a crustacean, like a crab."),
    P('no-bones', 'animals', 'They have no bones', 'No bones',
      ['Shark', 'Octopus', 'Jellyfish'], ['Snake', 'Tuna'],
      [('Squid', 1), ('Eel', 0), ('Stingray', 1), ('Seahorse', 0), ('Lobster', 1)], 1,
      "None of them has a single bone. A shark's skeleton is made of cartilage, the stuff of your ears and nose."),
    P('africa', 'animals', 'They live wild in Africa', 'Wild in Africa',
      ['Zebra', 'Giraffe', 'Gorilla'], ['Kangaroo', 'Polar bear'],
      [('Tiger', 0), ('Hippo', 1), ('Orangutan', 0), ('Chimpanzee', 1), ('Jaguar', 0)], 0,
      "All of them live wild in Africa. Tigers never did: wild tigers live only in Asia."),
    P('penguins', 'animals', 'Wild penguins live there', 'Where penguins live',
      ['Antarctica', 'New Zealand', 'South Africa'], ['Greenland', 'Canada'],
      [('Galápagos Islands', 1), ('Alaska', 0), ('Australia', 1), ('Iceland', 0), ('Chile', 1)], 0,
      "Wild penguins live in all of them. None lives at the North Pole: the northernmost penguins live on the Galápagos, at the equator."),
    P('dinosaurs', 'animals', 'They were dinosaurs', 'Dinosaurs',
      ['T. rex', 'Triceratops', 'Stegosaurus'], ['Mammoth', 'Pterodactyl'],
      [('Velociraptor', 1), ('Plesiosaur', 0), ('Diplodocus', 1), ('Dimetrodon', 0), ('Brachiosaurus', 1)], 3,
      "They were dinosaurs. The flying pterodactyl and the swimming plesiosaur were not: they were other reptiles of the same age."),
    P('keratin', 'science', 'Made of keratin', 'Keratin',
      ['Hair', 'Fingernails', 'Feathers'], ['Bone', 'Teeth'],
      [('Rhino horn', 1), ('Elephant tusk', 0), ('Hooves', 1), ('Antlers', 0), ('Wool', 1)], 0,
      "All are made of keratin, the stuff of your hair and nails. A rhino's horn is too; an elephant's tusk is a tooth."),
    # ------------------------------------------------------------------ food and plants
    P('botanical-fruits', 'food', 'To a botanist, fruits', 'Botanical fruits',
      ['Tomato', 'Cucumber', 'Pumpkin'], ['Carrot', 'Lettuce'],
      [('Courgette', 1), ('Potato', 0), ('Aubergine', 1), ('Rhubarb', 0), ('Olive', 1)], 3,
      "To a botanist they are all fruits: each grows from a flower and holds the seeds. Rhubarb is a leaf stalk."),
    P('berries', 'food', 'To a botanist, berries', 'True berries',
      ['Banana', 'Grape', 'Kiwi'], ['Strawberry', 'Raspberry'],
      [('Watermelon', 1), ('Blackberry', 0), ('Blueberry', 1), ('Cherry', 0), ('Avocado', 1)], 0,
      "To a botanist a banana is a berry and a strawberry is not. A true berry grows from a single flower and keeps its seeds in the flesh."),
    P('legumes', 'food', 'They are legumes', 'Legumes',
      ['Pea', 'Lentil', 'Chickpea'], ['Rice', 'Almond'],
      [('Peanut', 1), ('Coffee bean', 0), ('Soybean', 1), ('Walnut', 0), ('Sesame', 0)], 0,
      "They are legumes, seeds that grow in pods. The peanut is one, so it is closer to a pea than to a walnut."),
    P('nightshades', 'food', 'The nightshade family', 'Nightshades',
      ['Tomato', 'Potato', 'Aubergine'], ['Carrot', 'Cucumber'],
      [('Chilli pepper', 1), ('Sweet potato', 0), ('Tobacco', 1), ('Onion', 0), ('Black pepper', 0)], 1,
      "All belong to one plant family, the nightshades. The potato and tobacco are cousins; the sweet potato is not."),
    P('rose-family', 'food', 'The rose family', 'The rose family',
      ['Apple', 'Cherry', 'Strawberry'], ['Orange', 'Banana'],
      [('Almond', 1), ('Grape', 0), ('Peach', 1), ('Mango', 0), ('Raspberry', 1)], 0,
      "They all belong to the rose family. An almond is the seed of a fruit much like a peach."),
    P('americas', 'food', 'They came from the Americas', 'From the Americas',
      ['Potato', 'Maize', 'Cocoa'], ['Wheat', 'Rice'],
      [('Tomato', 1), ('Coffee', 0), ('Vanilla', 1), ('Onion', 0), ('Pineapple', 1)], 1,
      "All came from the Americas. Before Columbus, nobody in Europe, Asia or Africa had tasted a potato, a tomato or chocolate."),
    P('cabbage', 'food', 'One species: wild cabbage', 'Wild cabbage',
      ['Cabbage', 'Broccoli', 'Cauliflower'], ['Lettuce', 'Carrot'],
      [('Kale', 1), ('Spinach', 0), ('Brussels sprouts', 1), ('Celery', 0), ('Kohlrabi', 1)], 1,
      "They are all one species, wild cabbage, bred by farmers into many shapes."),
    P('underground', 'food', 'They grow underground', 'Grown underground',
      ['Carrot', 'Potato', 'Garlic'], ['Tomato', 'Pumpkin'],
      [('Peanut', 1), ('Pineapple', 0), ('Ginger', 1), ('Asparagus', 0), ('Onion', 1)], 0,
      "All grow under the ground. So does the peanut: after flowering, its stalk bends down and pushes the pod into the soil."),
    P('climacteric', 'food', 'They ripen after picking', 'Ripen after picking',
      ['Banana', 'Avocado', 'Mango'], ['Grape', 'Strawberry'],
      [('Tomato', 1), ('Pineapple', 0), ('Pear', 1), ('Orange', 0), ('Cherry', 0)], 1,
      "They keep ripening after they are picked. Grapes, oranges and pineapples do not."),
    P('caffeine', 'food', 'They contain caffeine', 'Caffeine',
      ['Coffee', 'Tea', 'Cocoa'], ['Milk', 'Orange juice'],
      [('Yerba mate', 1), ('Rooibos', 0), ('Guarana', 1), ('Chamomile tea', 0), ('Kola nut', 1)], 1,
      "Each naturally contains caffeine. Rooibos, the red tea of South Africa, has none."),
    # ------------------------------------------------------------------ science, space, the body
    P('metals', 'science', 'They are metals', 'Metals',
      ['Sodium', 'Calcium', 'Potassium'], ['Carbon', 'Sulphur'],
      [('Lithium', 1), ('Iodine', 0), ('Magnesium', 1), ('Mercury', 1), ('Phosphorus', 0)], 3,
      "They are all metals. The calcium in your bones and the sodium in your salt are metals too."),
    P('noble-gases', 'science', 'They are noble gases', 'Noble gases',
      ['Helium', 'Neon', 'Argon'], ['Oxygen', 'Hydrogen'],
      [('Krypton', 1), ('Nitrogen', 0), ('Xenon', 1), ('Chlorine', 0), ('Radon', 1)], None,
      "They are the noble gases, which almost never react with anything. That is why balloons are filled with helium and not with hydrogen."),
    P('greenhouse', 'science', 'They are greenhouse gases', 'Greenhouse gases',
      ['Carbon dioxide', 'Methane', 'Water vapour'], ['Oxygen', 'Nitrogen'],
      [('Ozone', 1), ('Argon', 0), ('Nitrous oxide', 1), ('Helium', 0), ('Hydrogen', 0)], None,
      "They trap heat in the air. Oxygen and nitrogen, which make up 99 per cent of dry air, do not."),
    P('stars', 'science', 'They are stars', 'Stars',
      ['Sirius', 'Polaris', 'Betelgeuse'], ['Venus', 'The Moon'],
      [('The Sun', 1), ('Jupiter', 0), ('Vega', 1), ("Halley's Comet", 0), ('Proxima Centauri', 1)], 0,
      "They are stars. So is the Sun: it only looks different because it is so close."),
    P('moons', 'science', 'They are moons', 'Moons',
      ['Titan', 'Europa', 'Io'], ['Pluto', 'Sirius'],
      [('Ganymede', 1), ('Ceres', 0), ('Phobos', 1), ("Halley's Comet", 0), ('Triton', 1)], None,
      "Each is a moon of another planet. Ganymede, a moon of Jupiter, is bigger than the planet Mercury."),
    P('alloys', 'science', 'They are alloys', 'Alloys',
      ['Steel', 'Bronze', 'Brass'], ['Iron', 'Copper'],
      [('Pewter', 1), ('Aluminium', 0), ('Sterling silver', 1), ('Titanium', 0), ('Tin', 0)], 3,
      "They are alloys, metals melted together. Bronze is copper and tin; brass is copper and zinc."),
    P('viruses', 'science', 'A virus causes them', 'Caused by a virus',
      ['Flu', 'Measles', 'Chickenpox'], ['Cholera', 'Tuberculosis'],
      [('Rabies', 1), ('Malaria', 0), ('Common cold', 1), ('Plague', 0), ('Polio', 1)], 1,
      "A virus causes each of them, so antibiotics cannot cure them. Malaria is caused by a parasite that mosquitoes carry."),
    P('months', 'culture', 'They have 31 days', '31 days',
      ['January', 'March', 'May'], ['February', 'April'],
      [('July', 1), ('August', 1), ('September', 0), ('November', 0), ('December', 1)], 1,
      "Each has 31 days. July and August both do: one is named after Julius Caesar, the next after the emperor Augustus."),
    # ------------------------------------------------------------------ history and inventions
    P('before-1900', 'history', 'Invented before 1900', 'Before 1900',
      ['Telephone', 'Bicycle', 'Light bulb'], ['Television', 'Aeroplane'],
      [('Fax machine', 1), ('Microwave oven', 0), ('Typewriter', 1), ('Helicopter', 0), ('Dynamite', 1)], 0,
      "All were invented before 1900. The fax machine was patented in 1843, more than thirty years before the telephone."),
    P('china', 'history', 'Invented in China', 'Invented in China',
      ['Paper', 'Gunpowder', 'Compass'], ['Glass', 'Telescope'],
      [('Porcelain', 1), ('Fortune cookie', 0), ('Silk', 1), ('Chess', 0), ('Paper money', 1)], 1,
      "All were invented in China. The fortune cookie was not: it came to American restaurants from Japan, by way of California."),
    P('seven-wonders', 'history', 'The Seven Wonders', 'Seven Wonders',
      ['Great Pyramid', 'Colossus of Rhodes', 'Hanging Gardens'], ['Stonehenge', 'Great Wall'],
      [('Lighthouse of Alexandria', 1), ('Colosseum', 0), ('Statue of Zeus', 1), ('Parthenon', 0), ('Temple of Artemis', 1)], 1,
      "They are among the Seven Wonders of the Ancient World. Only the Great Pyramid still stands."),
    P('nobel', 'history', 'They won a Nobel Prize', 'Nobel Prize',
      ['Albert Einstein', 'Marie Curie', 'Nelson Mandela'], ['Isaac Newton', 'Charles Darwin'],
      [('Winston Churchill', 1), ('Mahatma Gandhi', 0), ('Martin Luther King', 1), ('Stephen Hawking', 0), ('Ernest Hemingway', 1)], 1,
      "Each won a Nobel Prize. Gandhi never did, though he was nominated five times; Churchill's prize was for literature."),
    P('women-inventors', 'history', 'A woman invented it', 'Invented by women',
      ['Dishwasher', 'Windscreen wiper', 'Kevlar'], ['Radio', 'Steam engine'],
      [('Coffee filter', 1), ('Vacuum cleaner', 0), ('Disposable nappy', 1), ('Sewing machine', 0), ('Zip', 0)], None,
      "A woman invented each of them. Josephine Cochrane built the first practical dishwasher in 1886."),
    # ------------------------------------------------------------------ language and culture
    P('van-gogh', 'culture', 'Van Gogh painted them', 'Van Gogh',
      ['The Starry Night', 'Sunflowers', 'Irises'], ['Water Lilies', 'The Scream'],
      [('The Potato Eaters', 1), ('The Kiss', 0), ('Bedroom in Arles', 1), ('Guernica', 0), ('Café Terrace at Night', 1)], None,
      "Vincent van Gogh painted them all in just five years, from 1885 to 1889."),
    P('andersen', 'culture', 'Tales by H. C. Andersen', "Andersen's tales",
      ['The Little Mermaid', 'The Ugly Duckling', 'Thumbelina'], ['Cinderella', 'Snow White'],
      [('The Snow Queen', 1), ('Rapunzel', 0), ('The Princess and the Pea', 1), ('Pinocchio', 0), ('Hansel and Gretel', 0)], None,
      "Hans Christian Andersen made up each of these tales. Cinderella and Snow White are old folk tales that others wrote down."),
    P('japanese-words', 'culture', 'Words from Japanese', 'From Japanese',
      ['Tsunami', 'Karaoke', 'Emoji'], ['Kung fu', 'Yoga'],
      [('Tycoon', 1), ('Kimchi', 0), ('Origami', 1), ('Ketchup', 0), ('Honcho', 1)], 0,
      "English borrowed each of these words from Japanese. 'Tycoon' comes from taikun, a title once used for the shogun."),
    P('arabic-words', 'culture', 'Words from Arabic', 'From Arabic',
      ['Algebra', 'Coffee', 'Sugar'], ['Tea', 'Chocolate'],
      [('Cotton', 1), ('Robot', 0), ('Sofa', 1), ('Shampoo', 0), ('Zero', 1)], None,
      "English took each of these words from Arabic. 'Algebra' comes from al-jabr, a word in the title of a book written about 1,200 years ago."),
    P('eponyms', 'culture', 'Named after real people', 'Eponyms',
      ['Sandwich', 'Diesel', 'Saxophone'], ['Hamburger', 'Jeans'],
      [('Jacuzzi', 1), ('Bikini', 0), ('Nachos', 1), ('Marathon', 0), ('Cardigan', 1)], 2,
      "Each is named after a real person. Nachos carry the nickname of Ignacio 'Nacho' Anaya, the Mexican cook who first made them."),
    P('latin-alphabet', 'culture', 'Written in Latin letters', 'Latin alphabet',
      ['Turkish', 'Vietnamese', 'Swahili'], ['Russian', 'Greek'],
      [('Indonesian', 1), ('Korean', 0), ('Polish', 1), ('Thai', 0), ('Hindi', 0)], None,
      "All are written with the Latin alphabet, the letters you are reading now. Turkish switched to it in 1928."),
    P('un-languages', 'culture', 'Official UN languages', 'UN languages',
      ['English', 'French', 'Russian'], ['German', 'Japanese'],
      [('Arabic', 1), ('Hindi', 0), ('Chinese', 1), ('Portuguese', 0), ('Spanish', 1)], 1,
      "They are the six official languages of the United Nations. Hindi and Portuguese are not among them."),
    P('woodwinds', 'culture', 'They are woodwinds', 'Woodwinds',
      ['Clarinet', 'Oboe', 'Flute'], ['Trumpet', 'Trombone'],
      [('Saxophone', 1), ('Tuba', 0), ('Bassoon', 1), ('French horn', 0), ('Piccolo', 1)], 0,
      "They are woodwinds, whatever they are made of. The saxophone is made of brass but played with a reed, so it counts as one."),
    P('japan-martial', 'sport', 'They come from Japan', 'From Japan',
      ['Judo', 'Karate', 'Sumo'], ['Kung fu', 'Boxing'],
      [('Aikido', 1), ('Taekwondo', 0), ('Kendo', 1), ('Capoeira', 0), ('Ju-jitsu', 1)], 1,
      "Each began in Japan. Taekwondo is Korean, kung fu is Chinese and capoeira is Brazilian."),

    # ------------------------------------------------------------------ added in October 2026 (second round)
    P('island-countries', 'countries', 'They are island countries', 'Island countries',
      ['Japan', 'Iceland', 'Madagascar'], ['Italy', 'Chile'],
      [('Sri Lanka', 1), ('Norway', 0), ('New Zealand', 1), ('Greece', 0), ('Cuba', 1)], 3,
      "Each lies mainly on islands. Indonesia is the largest and most populous island country of all."),
    P('olympics-1896', 'sport', 'In the first modern Olympics', 'Athens 1896',
      ['Athletics', 'Swimming', 'Fencing'], ['Basketball', 'Volleyball'],
      [('Cycling', 1), ('Golf', 0), ('Wrestling', 1), ('Rowing', 0), ('Tennis', 1)], 3,
      "All were part of the first modern Olympics, Athens 1896. Rowing was planned too, but bad weather stopped it."),
    P('citrus', 'food', 'They are citrus fruits', 'Citrus fruits',
      ['Lemon', 'Orange', 'Grapefruit'], ['Apple', 'Banana'],
      [('Lime', 1), ('Pineapple', 0), ('Mandarin', 1), ('Kiwi', 0), ('Pomelo', 1)], None,
      "They are all citrus fruits. The grapefruit is a cross between a pomelo and a sweet orange."),
    P('shakespeare', 'culture', 'Plays by Shakespeare', "Shakespeare's plays",
      ['Hamlet', 'Macbeth', 'Othello'], ['Faust', 'Don Quixote'],
      [('King Lear', 1), ('Oedipus Rex', 0), ('The Tempest', 1), ('Les Misérables', 0), ('Twelfth Night', 1)], None,
      "William Shakespeare wrote all of them. He wrote or co-wrote about 39 plays in all."),
    P('roman-emperors', 'history', 'They were Roman emperors', 'Roman emperors',
      ['Augustus', 'Nero', 'Hadrian'], ['Julius Caesar', 'Cicero'],
      [('Marcus Aurelius', 1), ('Hannibal', 0), ('Constantine', 1), ('Spartacus', 0), ('Trajan', 1)], None,
      "Each was a Roman emperor. Julius Caesar never was: Augustus became the first emperor in 27 BC."),
    P('pharaohs', 'history', 'They were pharaohs', 'Pharaohs of Egypt',
      ['Tutankhamun', 'Ramesses II', 'Cleopatra'], ['Nebuchadnezzar', 'Gilgamesh'],
      [('Khufu', 1), ('Hammurabi', 0), ('Akhenaten', 1), ('Attila', 0), ('Hatshepsut', 1)], None,
      "Each ruled ancient Egypt as pharaoh. Pharaonic rule ended when Rome conquered Egypt in 30 BC."),
]
