"""One of 193: the 193 countries and the lists the phone answers from. Checked on 5 Oct 2026 (quotes in evidence.txt).

Every list was read on two different websites, each page opened and read; the quotes are in evidence.txt.
Overseas territories never count: each country's own land only (so the United Kingdom is not on the Mediterranean,
France does not border Brazil). Partially recognised states and territories are not in the game (only UN member states).

COUNTRIES: (ISO 3166 alpha-3, alpha-2, UN M49 code, name shown in the game, other name shown smaller, UN region,
            UN sub-region, name on the UN's own Member States page)
  - The 193 member states: the UN's "Member States" page and Wikipedia's "Member states of the United Nations"
    list the same 193 (evidence.txt, part A1).
  - Regions and sub-regions: the UN Statistics Division's M49 page ("Geographic Regions") and Wikipedia's
    "List of countries and territories by the United Nations geoscheme" agree for all 193 (part A2).
  - Names shown in the game (C): the common English short name; where the UN uses another name that people may look
    for, it is shown smaller beside it (Naoero is the UN's name for Nauru since 26 June 2026).

LISTS: id -> dict(ids, sources (two websites), note). The build checks that every id is one of the 193.
"""

COUNTRIES = [
    ('AFG', 'AF', '004', 'Afghanistan', '', 'Asia', 'Southern Asia', 'Afghanistan'),
    ('AGO', 'AO', '024', 'Angola', '', 'Africa', 'Middle Africa', 'Angola'),
    ('ALB', 'AL', '008', 'Albania', '', 'Europe', 'Southern Europe', 'Albania'),
    ('AND', 'AD', '020', 'Andorra', '', 'Europe', 'Southern Europe', 'Andorra'),
    ('ARE', 'AE', '784', 'United Arab Emirates', '', 'Asia', 'Western Asia', 'United Arab Emirates'),
    ('ARG', 'AR', '032', 'Argentina', '', 'Americas', 'South America', 'Argentina'),
    ('ARM', 'AM', '051', 'Armenia', '', 'Asia', 'Western Asia', 'Armenia'),
    ('ATG', 'AG', '028', 'Antigua and Barbuda', '', 'Americas', 'Caribbean', 'Antigua and Barbuda'),
    ('AUS', 'AU', '036', 'Australia', '', 'Oceania', 'Australia and New Zealand', 'Australia'),
    ('AUT', 'AT', '040', 'Austria', '', 'Europe', 'Western Europe', 'Austria'),
    ('AZE', 'AZ', '031', 'Azerbaijan', '', 'Asia', 'Western Asia', 'Azerbaijan'),
    ('BDI', 'BI', '108', 'Burundi', '', 'Africa', 'Eastern Africa', 'Burundi'),
    ('BEL', 'BE', '056', 'Belgium', '', 'Europe', 'Western Europe', 'Belgium'),
    ('BEN', 'BJ', '204', 'Benin', '', 'Africa', 'Western Africa', 'Benin'),
    ('BFA', 'BF', '854', 'Burkina Faso', '', 'Africa', 'Western Africa', 'Burkina Faso'),
    ('BGD', 'BD', '050', 'Bangladesh', '', 'Asia', 'Southern Asia', 'Bangladesh'),
    ('BGR', 'BG', '100', 'Bulgaria', '', 'Europe', 'Eastern Europe', 'Bulgaria'),
    ('BHR', 'BH', '048', 'Bahrain', '', 'Asia', 'Western Asia', 'Bahrain'),
    ('BHS', 'BS', '044', 'Bahamas', '', 'Americas', 'Caribbean', 'Bahamas'),
    ('BIH', 'BA', '070', 'Bosnia and Herzegovina', '', 'Europe', 'Southern Europe', 'Bosnia and Herzegovina'),
    ('BLR', 'BY', '112', 'Belarus', '', 'Europe', 'Eastern Europe', 'Belarus'),
    ('BLZ', 'BZ', '084', 'Belize', '', 'Americas', 'Central America', 'Belize'),
    ('BOL', 'BO', '068', 'Bolivia', '', 'Americas', 'South America', 'Bolivia (Plurinational State of)'),
    ('BRA', 'BR', '076', 'Brazil', '', 'Americas', 'South America', 'Brazil'),
    ('BRB', 'BB', '052', 'Barbados', '', 'Americas', 'Caribbean', 'Barbados'),
    ('BRN', 'BN', '096', 'Brunei', '', 'Asia', 'South-eastern Asia', 'Brunei Darussalam'),
    ('BTN', 'BT', '064', 'Bhutan', '', 'Asia', 'Southern Asia', 'Bhutan'),
    ('BWA', 'BW', '072', 'Botswana', '', 'Africa', 'Southern Africa', 'Botswana'),
    ('CAF', 'CF', '140', 'Central African Republic', '', 'Africa', 'Middle Africa', 'Central African Republic'),
    ('CAN', 'CA', '124', 'Canada', '', 'Americas', 'Northern America', 'Canada'),
    ('CHE', 'CH', '756', 'Switzerland', '', 'Europe', 'Western Europe', 'Switzerland'),
    ('CHL', 'CL', '152', 'Chile', '', 'Americas', 'South America', 'Chile'),
    ('CHN', 'CN', '156', 'China', '', 'Asia', 'Eastern Asia', 'China'),
    ('CIV', 'CI', '384', "Côte d'Ivoire", 'Ivory Coast', 'Africa', 'Western Africa', "Côte d'Ivoire"),
    ('CMR', 'CM', '120', 'Cameroon', '', 'Africa', 'Middle Africa', 'Cameroon'),
    ('COD', 'CD', '180', 'DR Congo', 'Democratic Republic of the Congo', 'Africa', 'Middle Africa', 'Democratic Republic of the Congo'),
    ('COG', 'CG', '178', 'Congo', 'Republic of the Congo', 'Africa', 'Middle Africa', 'Congo'),
    ('COL', 'CO', '170', 'Colombia', '', 'Americas', 'South America', 'Colombia'),
    ('COM', 'KM', '174', 'Comoros', '', 'Africa', 'Eastern Africa', 'Comoros'),
    ('CPV', 'CV', '132', 'Cabo Verde', 'Cape Verde', 'Africa', 'Western Africa', 'Cabo Verde'),
    ('CRI', 'CR', '188', 'Costa Rica', '', 'Americas', 'Central America', 'Costa Rica'),
    ('CUB', 'CU', '192', 'Cuba', '', 'Americas', 'Caribbean', 'Cuba'),
    ('CYP', 'CY', '196', 'Cyprus', '', 'Asia', 'Western Asia', 'Cyprus'),
    ('CZE', 'CZ', '203', 'Czechia', 'Czech Republic', 'Europe', 'Eastern Europe', 'Czechia'),
    ('DEU', 'DE', '276', 'Germany', '', 'Europe', 'Western Europe', 'Germany'),
    ('DJI', 'DJ', '262', 'Djibouti', '', 'Africa', 'Eastern Africa', 'Djibouti'),
    ('DMA', 'DM', '212', 'Dominica', '', 'Americas', 'Caribbean', 'Dominica'),
    ('DNK', 'DK', '208', 'Denmark', '', 'Europe', 'Northern Europe', 'Denmark'),
    ('DOM', 'DO', '214', 'Dominican Republic', '', 'Americas', 'Caribbean', 'Dominican Republic'),
    ('DZA', 'DZ', '012', 'Algeria', '', 'Africa', 'Northern Africa', 'Algeria'),
    ('ECU', 'EC', '218', 'Ecuador', '', 'Americas', 'South America', 'Ecuador'),
    ('EGY', 'EG', '818', 'Egypt', '', 'Africa', 'Northern Africa', 'Egypt'),
    ('ERI', 'ER', '232', 'Eritrea', '', 'Africa', 'Eastern Africa', 'Eritrea'),
    ('ESP', 'ES', '724', 'Spain', '', 'Europe', 'Southern Europe', 'Spain'),
    ('EST', 'EE', '233', 'Estonia', '', 'Europe', 'Northern Europe', 'Estonia'),
    ('ETH', 'ET', '231', 'Ethiopia', '', 'Africa', 'Eastern Africa', 'Ethiopia'),
    ('FIN', 'FI', '246', 'Finland', '', 'Europe', 'Northern Europe', 'Finland'),
    ('FJI', 'FJ', '242', 'Fiji', '', 'Oceania', 'Melanesia', 'Fiji'),
    ('FRA', 'FR', '250', 'France', '', 'Europe', 'Western Europe', 'France'),
    ('FSM', 'FM', '583', 'Micronesia', 'Federated States of Micronesia', 'Oceania', 'Micronesia', 'Micronesia (Federated States of)'),
    ('GAB', 'GA', '266', 'Gabon', '', 'Africa', 'Middle Africa', 'Gabon'),
    ('GBR', 'GB', '826', 'United Kingdom', '', 'Europe', 'Northern Europe', 'United Kingdom of Great Britain and Northern Ireland'),
    ('GEO', 'GE', '268', 'Georgia', '', 'Asia', 'Western Asia', 'Georgia'),
    ('GHA', 'GH', '288', 'Ghana', '', 'Africa', 'Western Africa', 'Ghana'),
    ('GIN', 'GN', '324', 'Guinea', '', 'Africa', 'Western Africa', 'Guinea'),
    ('GMB', 'GM', '270', 'Gambia', '', 'Africa', 'Western Africa', 'Gambia'),
    ('GNB', 'GW', '624', 'Guinea-Bissau', '', 'Africa', 'Western Africa', 'Guinea-Bissau'),
    ('GNQ', 'GQ', '226', 'Equatorial Guinea', '', 'Africa', 'Middle Africa', 'Equatorial Guinea'),
    ('GRC', 'GR', '300', 'Greece', '', 'Europe', 'Southern Europe', 'Greece'),
    ('GRD', 'GD', '308', 'Grenada', '', 'Americas', 'Caribbean', 'Grenada'),
    ('GTM', 'GT', '320', 'Guatemala', '', 'Americas', 'Central America', 'Guatemala'),
    ('GUY', 'GY', '328', 'Guyana', '', 'Americas', 'South America', 'Guyana'),
    ('HND', 'HN', '340', 'Honduras', '', 'Americas', 'Central America', 'Honduras'),
    ('HRV', 'HR', '191', 'Croatia', '', 'Europe', 'Southern Europe', 'Croatia'),
    ('HTI', 'HT', '332', 'Haiti', '', 'Americas', 'Caribbean', 'Haiti'),
    ('HUN', 'HU', '348', 'Hungary', '', 'Europe', 'Eastern Europe', 'Hungary'),
    ('IDN', 'ID', '360', 'Indonesia', '', 'Asia', 'South-eastern Asia', 'Indonesia'),
    ('IND', 'IN', '356', 'India', '', 'Asia', 'Southern Asia', 'India'),
    ('IRL', 'IE', '372', 'Ireland', '', 'Europe', 'Northern Europe', 'Ireland'),
    ('IRN', 'IR', '364', 'Iran', '', 'Asia', 'Southern Asia', 'Iran (Islamic Republic of)'),
    ('IRQ', 'IQ', '368', 'Iraq', '', 'Asia', 'Western Asia', 'Iraq'),
    ('ISL', 'IS', '352', 'Iceland', '', 'Europe', 'Northern Europe', 'Iceland'),
    ('ISR', 'IL', '376', 'Israel', '', 'Asia', 'Western Asia', 'Israel'),
    ('ITA', 'IT', '380', 'Italy', '', 'Europe', 'Southern Europe', 'Italy'),
    ('JAM', 'JM', '388', 'Jamaica', '', 'Americas', 'Caribbean', 'Jamaica'),
    ('JOR', 'JO', '400', 'Jordan', '', 'Asia', 'Western Asia', 'Jordan'),
    ('JPN', 'JP', '392', 'Japan', '', 'Asia', 'Eastern Asia', 'Japan'),
    ('KAZ', 'KZ', '398', 'Kazakhstan', '', 'Asia', 'Central Asia', 'Kazakhstan'),
    ('KEN', 'KE', '404', 'Kenya', '', 'Africa', 'Eastern Africa', 'Kenya'),
    ('KGZ', 'KG', '417', 'Kyrgyzstan', '', 'Asia', 'Central Asia', 'Kyrgyzstan'),
    ('KHM', 'KH', '116', 'Cambodia', '', 'Asia', 'South-eastern Asia', 'Cambodia'),
    ('KIR', 'KI', '296', 'Kiribati', '', 'Oceania', 'Micronesia', 'Kiribati'),
    ('KNA', 'KN', '659', 'Saint Kitts and Nevis', '', 'Americas', 'Caribbean', 'Saint Kitts and Nevis'),
    ('KOR', 'KR', '410', 'South Korea', 'Republic of Korea', 'Asia', 'Eastern Asia', 'Republic of Korea'),
    ('KWT', 'KW', '414', 'Kuwait', '', 'Asia', 'Western Asia', 'Kuwait'),
    ('LAO', 'LA', '418', 'Laos', '', 'Asia', 'South-eastern Asia', "Lao People's Democratic Republic"),
    ('LBN', 'LB', '422', 'Lebanon', '', 'Asia', 'Western Asia', 'Lebanon'),
    ('LBR', 'LR', '430', 'Liberia', '', 'Africa', 'Western Africa', 'Liberia'),
    ('LBY', 'LY', '434', 'Libya', '', 'Africa', 'Northern Africa', 'Libya'),
    ('LCA', 'LC', '662', 'Saint Lucia', '', 'Americas', 'Caribbean', 'Saint Lucia'),
    ('LIE', 'LI', '438', 'Liechtenstein', '', 'Europe', 'Western Europe', 'Liechtenstein'),
    ('LKA', 'LK', '144', 'Sri Lanka', '', 'Asia', 'Southern Asia', 'Sri Lanka'),
    ('LSO', 'LS', '426', 'Lesotho', '', 'Africa', 'Southern Africa', 'Lesotho'),
    ('LTU', 'LT', '440', 'Lithuania', '', 'Europe', 'Northern Europe', 'Lithuania'),
    ('LUX', 'LU', '442', 'Luxembourg', '', 'Europe', 'Western Europe', 'Luxembourg'),
    ('LVA', 'LV', '428', 'Latvia', '', 'Europe', 'Northern Europe', 'Latvia'),
    ('MAR', 'MA', '504', 'Morocco', '', 'Africa', 'Northern Africa', 'Morocco'),
    ('MCO', 'MC', '492', 'Monaco', '', 'Europe', 'Western Europe', 'Monaco'),
    ('MDA', 'MD', '498', 'Moldova', '', 'Europe', 'Eastern Europe', 'Republic of Moldova'),
    ('MDG', 'MG', '450', 'Madagascar', '', 'Africa', 'Eastern Africa', 'Madagascar'),
    ('MDV', 'MV', '462', 'Maldives', '', 'Asia', 'Southern Asia', 'Maldives'),
    ('MEX', 'MX', '484', 'Mexico', '', 'Americas', 'Central America', 'Mexico'),
    ('MHL', 'MH', '584', 'Marshall Islands', '', 'Oceania', 'Micronesia', 'Marshall Islands'),
    ('MKD', 'MK', '807', 'North Macedonia', '', 'Europe', 'Southern Europe', 'North Macedonia'),
    ('MLI', 'ML', '466', 'Mali', '', 'Africa', 'Western Africa', 'Mali'),
    ('MLT', 'MT', '470', 'Malta', '', 'Europe', 'Southern Europe', 'Malta'),
    ('MMR', 'MM', '104', 'Myanmar', 'Burma', 'Asia', 'South-eastern Asia', 'Myanmar'),
    ('MNE', 'ME', '499', 'Montenegro', '', 'Europe', 'Southern Europe', 'Montenegro'),
    ('MNG', 'MN', '496', 'Mongolia', '', 'Asia', 'Eastern Asia', 'Mongolia'),
    ('MOZ', 'MZ', '508', 'Mozambique', '', 'Africa', 'Eastern Africa', 'Mozambique'),
    ('MRT', 'MR', '478', 'Mauritania', '', 'Africa', 'Western Africa', 'Mauritania'),
    ('MUS', 'MU', '480', 'Mauritius', '', 'Africa', 'Eastern Africa', 'Mauritius'),
    ('MWI', 'MW', '454', 'Malawi', '', 'Africa', 'Eastern Africa', 'Malawi'),
    ('MYS', 'MY', '458', 'Malaysia', '', 'Asia', 'South-eastern Asia', 'Malaysia'),
    ('NAM', 'NA', '516', 'Namibia', '', 'Africa', 'Southern Africa', 'Namibia'),
    ('NER', 'NE', '562', 'Niger', '', 'Africa', 'Western Africa', 'Niger'),
    ('NGA', 'NG', '566', 'Nigeria', '', 'Africa', 'Western Africa', 'Nigeria'),
    ('NIC', 'NI', '558', 'Nicaragua', '', 'Americas', 'Central America', 'Nicaragua'),
    ('NLD', 'NL', '528', 'Netherlands', '', 'Europe', 'Western Europe', 'Netherlands (Kingdom of the)'),
    ('NOR', 'NO', '578', 'Norway', '', 'Europe', 'Northern Europe', 'Norway'),
    ('NPL', 'NP', '524', 'Nepal', '', 'Asia', 'Southern Asia', 'Nepal'),
    ('NRU', 'NR', '520', 'Naoero', 'Nauru', 'Oceania', 'Micronesia', 'Naoero'),
    ('NZL', 'NZ', '554', 'New Zealand', '', 'Oceania', 'Australia and New Zealand', 'New Zealand'),
    ('OMN', 'OM', '512', 'Oman', '', 'Asia', 'Western Asia', 'Oman'),
    ('PAK', 'PK', '586', 'Pakistan', '', 'Asia', 'Southern Asia', 'Pakistan'),
    ('PAN', 'PA', '591', 'Panama', '', 'Americas', 'Central America', 'Panama'),
    ('PER', 'PE', '604', 'Peru', '', 'Americas', 'South America', 'Peru'),
    ('PHL', 'PH', '608', 'Philippines', '', 'Asia', 'South-eastern Asia', 'Philippines'),
    ('PLW', 'PW', '585', 'Palau', '', 'Oceania', 'Micronesia', 'Palau'),
    ('PNG', 'PG', '598', 'Papua New Guinea', '', 'Oceania', 'Melanesia', 'Papua New Guinea'),
    ('POL', 'PL', '616', 'Poland', '', 'Europe', 'Eastern Europe', 'Poland'),
    ('PRK', 'KP', '408', 'North Korea', "Democratic People's Republic of Korea", 'Asia', 'Eastern Asia', "Democratic People's Republic of Korea"),
    ('PRT', 'PT', '620', 'Portugal', '', 'Europe', 'Southern Europe', 'Portugal'),
    ('PRY', 'PY', '600', 'Paraguay', '', 'Americas', 'South America', 'Paraguay'),
    ('QAT', 'QA', '634', 'Qatar', '', 'Asia', 'Western Asia', 'Qatar'),
    ('ROU', 'RO', '642', 'Romania', '', 'Europe', 'Eastern Europe', 'Romania'),
    ('RUS', 'RU', '643', 'Russia', '', 'Europe', 'Eastern Europe', 'Russian Federation'),
    ('RWA', 'RW', '646', 'Rwanda', '', 'Africa', 'Eastern Africa', 'Rwanda'),
    ('SAU', 'SA', '682', 'Saudi Arabia', '', 'Asia', 'Western Asia', 'Saudi Arabia'),
    ('SDN', 'SD', '729', 'Sudan', '', 'Africa', 'Northern Africa', 'Sudan'),
    ('SEN', 'SN', '686', 'Senegal', '', 'Africa', 'Western Africa', 'Senegal'),
    ('SGP', 'SG', '702', 'Singapore', '', 'Asia', 'South-eastern Asia', 'Singapore'),
    ('SLB', 'SB', '090', 'Solomon Islands', '', 'Oceania', 'Melanesia', 'Solomon Islands'),
    ('SLE', 'SL', '694', 'Sierra Leone', '', 'Africa', 'Western Africa', 'Sierra Leone'),
    ('SLV', 'SV', '222', 'El Salvador', '', 'Americas', 'Central America', 'El Salvador'),
    ('SMR', 'SM', '674', 'San Marino', '', 'Europe', 'Southern Europe', 'San Marino'),
    ('SOM', 'SO', '706', 'Somalia', '', 'Africa', 'Eastern Africa', 'Somalia'),
    ('SRB', 'RS', '688', 'Serbia', '', 'Europe', 'Southern Europe', 'Serbia'),
    ('SSD', 'SS', '728', 'South Sudan', '', 'Africa', 'Eastern Africa', 'South Sudan'),
    ('STP', 'ST', '678', 'São Tomé and Príncipe', '', 'Africa', 'Middle Africa', 'Sao Tome and Principe'),
    ('SUR', 'SR', '740', 'Suriname', '', 'Americas', 'South America', 'Suriname'),
    ('SVK', 'SK', '703', 'Slovakia', '', 'Europe', 'Eastern Europe', 'Slovakia'),
    ('SVN', 'SI', '705', 'Slovenia', '', 'Europe', 'Southern Europe', 'Slovenia'),
    ('SWE', 'SE', '752', 'Sweden', '', 'Europe', 'Northern Europe', 'Sweden'),
    ('SWZ', 'SZ', '748', 'Eswatini', 'Swaziland', 'Africa', 'Southern Africa', 'Eswatini'),
    ('SYC', 'SC', '690', 'Seychelles', '', 'Africa', 'Eastern Africa', 'Seychelles'),
    ('SYR', 'SY', '760', 'Syria', '', 'Asia', 'Western Asia', 'Syrian Arab Republic'),
    ('TCD', 'TD', '148', 'Chad', '', 'Africa', 'Middle Africa', 'Chad'),
    ('TGO', 'TG', '768', 'Togo', '', 'Africa', 'Western Africa', 'Togo'),
    ('THA', 'TH', '764', 'Thailand', '', 'Asia', 'South-eastern Asia', 'Thailand'),
    ('TJK', 'TJ', '762', 'Tajikistan', '', 'Asia', 'Central Asia', 'Tajikistan'),
    ('TKM', 'TM', '795', 'Turkmenistan', '', 'Asia', 'Central Asia', 'Turkmenistan'),
    ('TLS', 'TL', '626', 'Timor-Leste', 'East Timor', 'Asia', 'South-eastern Asia', 'Timor-Leste'),
    ('TON', 'TO', '776', 'Tonga', '', 'Oceania', 'Polynesia', 'Tonga'),
    ('TTO', 'TT', '780', 'Trinidad and Tobago', '', 'Americas', 'Caribbean', 'Trinidad and Tobago'),
    ('TUN', 'TN', '788', 'Tunisia', '', 'Africa', 'Northern Africa', 'Tunisia'),
    ('TUR', 'TR', '792', 'Türkiye', 'Turkey', 'Asia', 'Western Asia', 'Türkiye'),
    ('TUV', 'TV', '798', 'Tuvalu', '', 'Oceania', 'Polynesia', 'Tuvalu'),
    ('TZA', 'TZ', '834', 'Tanzania', '', 'Africa', 'Eastern Africa', 'United Republic of Tanzania'),
    ('UGA', 'UG', '800', 'Uganda', '', 'Africa', 'Eastern Africa', 'Uganda'),
    ('UKR', 'UA', '804', 'Ukraine', '', 'Europe', 'Eastern Europe', 'Ukraine'),
    ('URY', 'UY', '858', 'Uruguay', '', 'Americas', 'South America', 'Uruguay'),
    ('USA', 'US', '840', 'United States', '', 'Americas', 'Northern America', 'United States of America'),
    ('UZB', 'UZ', '860', 'Uzbekistan', '', 'Asia', 'Central Asia', 'Uzbekistan'),
    ('VCT', 'VC', '670', 'Saint Vincent and the Grenadines', '', 'Americas', 'Caribbean', 'Saint Vincent and the Grenadines'),
    ('VEN', 'VE', '862', 'Venezuela', '', 'Americas', 'South America', 'Venezuela (Bolivarian Republic of)'),
    ('VNM', 'VN', '704', 'Vietnam', '', 'Asia', 'South-eastern Asia', 'Viet Nam'),
    ('VUT', 'VU', '548', 'Vanuatu', '', 'Oceania', 'Melanesia', 'Vanuatu'),
    ('WSM', 'WS', '882', 'Samoa', '', 'Oceania', 'Polynesia', 'Samoa'),
    ('YEM', 'YE', '887', 'Yemen', '', 'Asia', 'Western Asia', 'Yemen'),
    ('ZAF', 'ZA', '710', 'South Africa', '', 'Africa', 'Southern Africa', 'South Africa'),
    ('ZMB', 'ZM', '894', 'Zambia', '', 'Africa', 'Eastern Africa', 'Zambia'),
    ('ZWE', 'ZW', '716', 'Zimbabwe', '', 'Africa', 'Eastern Africa', 'Zimbabwe'),
]

REGION_SOURCES = [
    ('UN Statistics Division (M49)', 'https://unstats.un.org/unsd/methodology/m49'),
    ('Wikipedia', 'https://en.wikipedia.org/wiki/List_of_countries_and_territories_by_the_United_Nations_geoscheme'),
]
MEMBER_SOURCES = [
    ('United Nations', 'https://www.un.org/en/about-us/member-states'),
    ('Wikipedia', 'https://en.wikipedia.org/wiki/Member_states_of_the_United_Nations'),
]

LISTS = {
    # B1: 44 on both sources; Vatican City is not a UN member state, so 43 here. Both count the Caspian countries
    # (Azerbaijan, Kazakhstan, Turkmenistan) as landlocked; Wikipedia's de facto states are left out.
    'landlocked': dict(name='Landlocked', sources=[
        ('Wikipedia', 'https://en.wikipedia.org/wiki/Landlocked_country'),
        ('WorldAtlas', 'https://www.worldatlas.com/articles/landlocked-countries-of-the-world.html')],
        ids='AFG AND ARM AUT AZE BLR BTN BOL BWA BFA BDI CAF TCD CZE SWZ ETH HUN KAZ KGZ LAO LSO LIE LUX MWI MLI MDA MNG NPL '
            'NER MKD PRY RWA SMR SRB SVK SSD CHE TJK TKM UGA UZB ZMB ZWE'),
    # B2: the same 46 UN member states on both (Wikipedia's "UN member states" table, Nations Online's 46 sovereign
    # states). Australia is on neither ("considered a continental country"); Taiwan is not a UN member state.
    'island': dict(name='Island country', sources=[
        ('Wikipedia', 'https://en.wikipedia.org/wiki/List_of_island_countries'),
        ('Nations Online', 'https://www.nationsonline.org/oneworld/island-countries.htm')],
        ids='ATG BHS BHR BRB BRN CPV COM CUB CYP DMA DOM TLS FJI GRD HTI ISL IDN IRL JAM JPN KIR MDG MDV MLT MHL MUS FSM NRU '
            'NZL PLW PNG PHL KNA LCA VCT WSM STP SYC SGP SLB LKA TON TTO TUV GBR VUT'),
    # B3: the same 22 on both; Palestine is not a UN member state, so 21. The United Kingdom touches the sea only
    # through its overseas territories (Gibraltar, Akrotiri and Dhekelia), which do not count.
    'med': dict(name='Coast on the Mediterranean', sources=[
        ('Wikipedia', 'https://en.wikipedia.org/wiki/Mediterranean_Sea'),
        ('WorldAtlas', 'https://www.worldatlas.com/geography/mediterranean-countries.html')],
        ids='ESP FRA MCO ITA SVN HRV BIH MNE ALB GRC TUR SYR LBN ISR EGY LBY TUN DZA MAR CYP MLT'),
    # B4: "It passes through the land of eleven sovereign states" (Wikipedia); "The Equator passes through the land of
    # 11 countries" (WorldAtlas). Kiribati and the Maldives: only their waters.
    'equator': dict(name='The equator crosses its land', sources=[
        ('Wikipedia', 'https://en.wikipedia.org/wiki/Equator'),
        ('WorldAtlas', 'https://www.worldatlas.com/articles/countries-on-the-equator.html')],
        ids='STP GAB COG COD UGA KEN SOM IDN ECU COL BRA'),
    # D1: the same 14 land neighbours on both.
    'china': dict(name='Shares a land border with China', sources=[
        ('Wikipedia', 'https://en.wikipedia.org/wiki/Borders_of_China'),
        ('WorldAtlas', 'https://www.worldatlas.com/articles/what-countries-border-china.html')],
        ids='AFG BTN IND KAZ KGZ LAO MNG MMR NPL PRK PAK RUS TJK VNM'),
    # D2: the same 16 on both, of which Abkhazia and South Ossetia are left out (partially recognised): 14.
    # Poland and Lithuania border Russia's Kaliningrad region.
    'russia': dict(name='Shares a land border with Russia', sources=[
        ('Wikipedia', 'https://en.wikipedia.org/wiki/Borders_of_Russia'),
        ('WorldAtlas', 'https://www.worldatlas.com/articles/what-countries-border-russia.html')],
        ids='AZE BLR CHN EST FIN GEO KAZ LVA LTU MNG PRK NOR POL UKR'),
    # D3: the same 54 UN member states on both (territories left out).
    'left': dict(name='Drives on the left', sources=[
        ('Wikipedia', 'https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic'),
        ('WorldAtlas', 'https://www.worldatlas.com/articles/list-of-countries-who-drive-on-the-left.html')],
        ids='ATG AUS BHS BGD BRB BTN BWA BRN CYP DMA SWZ FJI GRD GUY IND IDN IRL JAM JPN KEN KIR LSO MWI MYS MDV MLT MUS MOZ '
            'NAM NRU NPL NZL PAK PNG KNA LCA VCT WSM SYC SGP SLB ZAF LKA SUR TZA THA TLS TON TTO TUV UGA GBR ZMB ZWE'),
    # D4: the 21 members of the euro area (Bulgaria since 1 January 2026) on both, and the UN member states that use
    # the euro outside it: Andorra, Monaco, San Marino by agreement, Montenegro on its own (Vatican City and Kosovo
    # are not UN member states).
    'euro': dict(name='Uses the euro', sources=[
        ('European Commission', 'https://economy-finance.ec.europa.eu/euro/what-euro-area_en'),
        ('Wikipedia', 'https://en.wikipedia.org/wiki/Eurozone')],
        ids='AUT BEL BGR HRV CYP EST FIN FRA DEU GRC IRL ITA LVA LTU LUX MLT NLD PRT SVK SVN ESP AND MCO SMR MNE'),
}
