# Long Lost Cousin: the sentence shown after the reveal, the two sources (each opened and read on 3 Oct 2026),
# and the age of the last common ancestor in million years where two sources agree.
W = "Wikipedia"; BR = "Britannica"; ADW = "Animal Diversity Web"; AMNH = "American Museum of Natural History"
NHM = "Natural History Museum, London"; UCMP = "UC Museum of Paleontology"; AM = "Australian Museum"; PMC = "PubMed Central"
def w(page): return (W, "https://en.wikipedia.org/wiki/" + page)
F = {
"M01": ("Whales and dolphins are the hippo's closest living relatives. Their last common ancestor lived about 55 million years ago.", w("Hippopotamus"), (AMNH, "https://www.amnh.org/explore/news-blogs/whale-dolphin-evolution-analysis"), 55),
"M02": ("Manatees and other sea cows are among the elephant's closest living relatives. Rhinos and hippos only look the part.", w("Paenungulata"), (NHM, "https://www.nhm.ac.uk/discover/what-is-a-sea-cow.html"), None),
"M03": ("The hyrax looks like a guinea pig, but its closest living relatives are elephants and sea cows.", w("Hyrax"), (BR, "https://www.britannica.com/animal/hyrax"), None),
"M04": ("Hyenas look like dogs, but they sit on the cat side of the carnivores, with cats, civets and mongooses.", w("Hyena"), (UCMP, "https://ucmp.berkeley.edu/mammal/carnivora/carnivorasy.html"), None),
"M05": ("The red panda is not a bear. It belongs with raccoons, weasels and skunks. The giant panda is a true bear.", w("Red_panda"), ("Smithsonian's National Zoo", "https://nationalzoo.si.edu/animals/news/red-panda-bear-and-more-red-panda-facts"), None),
"M06": ("The giant panda is a true bear. The red panda is not: it belongs with raccoons and weasels.", w("Giant_panda"), ("Smithsonian's National Zoo", "https://nationalzoo.si.edu/animals/giant-panda"), None),
"M07": ("The koala is not a bear. It is a marsupial, and its closest living relatives are the wombats.", w("Koala"), (AM, "https://australian.museum/learn/animals/mammals/koala/"), None),
"M08": ("Dolphins and whales descend from hoofed land mammals, the group of cows, pigs and hippos. Seals went back to the sea separately.", w("Artiodactyla"), (AMNH, "https://www.amnh.org/explore/news-blogs/whale-dolphin-evolution-analysis"), None),
"M09": ("Seals are carnivores from the dog-like branch, with dogs, bears and weasels. Dolphins and manatees returned to the sea on their own.", w("Pinniped"), (NHM, "https://www.nhm.ac.uk/discover/what-is-a-seal.html"), None),
"M10": ("Bats are not flying mice. They belong to the group of horses, cats, dogs and whales. Mice sit on the other big branch, with monkeys and us.", w("Laurasiatheria"), (PMC, "https://pmc.ncbi.nlm.nih.gov/articles/PMC3539735"), None),
"M11": ("Chimpanzees and bonobos are our closest living relatives. Gorillas come next, then orangutans.", w("Hominidae"), ("Smithsonian Human Origins", "https://humanorigins.si.edu/evidence/genetics"), None),
"M12": ("A shrew looks like a mouse but is not a rodent. It belongs with hedgehogs and moles. Mice are closer to rabbits.", w("Eulipotyphla"), (PMC, "https://pmc.ncbi.nlm.nih.gov/articles/PMC3539735"), None),
"M13": ("The Tasmanian tiger was a marsupial, like the kangaroo. It only looked like a wolf: two animals that evolved the same shape separately.", w("Thylacine"), ("Communications Biology", "https://www.nature.com/articles/s42003-020-01569-x"), None),
"M14": ("The sugar glider is a marsupial, in the same order as the koala. Flying squirrels evolved their gliding skin separately.", w("Diprotodontia"), (AM, "https://australian.museum/learn/species-identification/ask-an-expert/what-is-a-marsupial/"), None),
"M15": ("Armadillos belong with sloths and anteaters. The pangolin wears armour too, but it is not related to them.", w("Xenarthra"), (BR, "https://www.britannica.com/animal/xenarthran"), None),
"M16": ("The pangolin's closest living relatives are the carnivores: cats, dogs and bears. Its scales only resemble an armadillo's armour.", w("Pangolin"), (ADW, "https://animaldiversity.org/accounts/Manidae/"), None),
"M17": ("Anteaters and sloths are close relatives. The pangolin is called the scaly anteater and the echidna the spiny anteater, but neither is a close relative.", w("Xenarthra"), (BR, "https://www.britannica.com/animal/xenarthran"), None),
"M18": ("The aardvark belongs to an African group that includes elephants, sea cows and hyraxes. It is not closely related to pigs.", w("Aardvark"), (ADW, "https://animaldiversity.org/accounts/Orycteropus_afer/"), None),
"M19": ("Horses, rhinos and tapirs are the odd-toed hoofed mammals. Cows and camels are even-toed, a different branch.", w("Odd-toed_ungulate"), (BR, "https://www.britannica.com/animal/perissodactyl"), None),
"M20": ("Camels and llamas belong to the same family. Llamas are South America's camels.", w("Camelidae"), (ADW, "https://animaldiversity.org/accounts/Camelidae/"), None),
"M21": ("The okapi has stripes like a zebra, but it is the giraffe's only living close relative.", w("Okapi"), (BR, "https://www.britannica.com/animal/okapi"), None),
"M22": ("Otters are members of the weasel family. Seals are other carnivores, and beavers are rodents.", w("Otter"), (BR, "https://www.britannica.com/animal/otter"), None),
"M23": ("The beaver is a rodent, like the mouse. The platypus has a beaver-like tail but is an egg-laying mammal from a far older branch.", w("Rodent"), (BR, "https://www.britannica.com/animal/rodent/Evolution-and-classification"), None),
"M24": ("The echidna and the platypus are the only mammals that lay eggs. Hedgehogs and porcupines grew their spines separately.", w("Monotreme"), (BR, "https://www.britannica.com/animal/monotreme"), None),
"M25": ("Rodents and primates share a branch, so a mouse is closer to you than to a shrew. That shared ancestor lived about 90 million years ago.", w("Euarchontoglires"), ("University of Western Australia", "https://www.uwa.edu.au/study/-/media/Faculties/Science/Docs/Mammalian-clades.pdf"), 90),
"M26": ("Meerkats are mongooses, on the cat side of the carnivores. Prairie dogs stand up the same way, but they are rodents.", w("Feliformia"), (UCMP, "https://ucmp.berkeley.edu/mammal/carnivora/carnivorasy.html"), None),
"M27": ("The capybara, the largest living rodent, belongs to the guinea pig's family. Rabbits are not rodents at all.", w("Capybara"), (BR, "https://www.britannica.com/animal/capybara-genus"), None),
"M28": ("The narwhal and the beluga are the only two living members of their whale family.", w("Monodontidae"), (ADW, "https://animaldiversity.org/accounts/Monodon_monoceros/"), None),
"M29": ("The orca, or killer whale, is the largest member of the dolphin family.", w("Orca"), (AM, "https://australian.museum/learn/animals/mammals/killer-whale/"), None),
"M30": ("Ancient DNA shows the woolly mammoth was closer to the Asian elephant than to the African one. Mastodons belonged to a separate, older family.", w("Woolly_mammoth"), ("Science News", "https://www.sciencenews.org/article/mammoth-findings-asian-elephant-closest-living-kin"), None),
"M31": ("Tapirs look a little like pigs, but they belong with horses and rhinos.", w("Tapir"), (ADW, "https://animaldiversity.org/accounts/Perissodactyla/"), None),
"M32": ("Genes place the walrus closer to sea lions and fur seals than to true seals. Manatees are not seals at all.", w("Pinniped"), ("BMC Evolutionary Biology", "https://link.springer.com/article/10.1186/1471-2148-7-216"), 20),
"M33": ("Zebras and horses belong to the same genus, Equus. Their lines split about 4 million years ago.", w("Equus_(genus)"), (BR, "https://www.britannica.com/animal/zebra"), 4),
"M34": ("Deer and cows are both ruminants. Even a pig is closer to a deer than a horse is.", w("Pecora"), (BR, "https://www.britannica.com/animal/artiodactyl/Annotated-classification"), None),
"M35": ("Porcupines are rodents from the guinea pig's branch. Hedgehogs and echidnas grew their spines separately.", w("Hystricognathi"), ("University of Western Australia", "https://www.uwa.edu.au/study/-/media/Faculties/Science/Docs/Mammalian-clades.pdf"), None),

"B01": ("Genome studies moved falcons away from hawks and eagles. Their closest relatives are parrots and songbirds.", ("Science News", "https://www.sciencenews.org/article/new-tree-life-confirms-strange-history-birds"), (PMC, "https://pmc.ncbi.nlm.nih.gov/articles/PMC4405904/"), None),
"B02": ("The flamingo's closest living relatives are the grebes, small diving birds. Storks and herons only look similar.", w("Mirandornithes"), ("Muséum national d'Histoire naturelle", "https://sciencepress.mnhn.fr/sites/default/files/articles/pdf/comptes-rendus-palevol2014v13f1a03.pdf"), None),
"B03": ("The penguin's closest living relatives are albatrosses and petrels. The two lines split about 60 million years ago. Puffins only look like penguins.", w("Penguin"), ("GigaScience", "https://link.springer.com/article/10.1186/2047-217X-3-27"), 60),
"B04": ("Swifts are the closest relatives of hummingbirds. Swallows look like swifts but are songbirds.", (BR, "https://www.britannica.com/animal/swift-bird"), w("Apodiformes"), None),
"B05": ("DNA from old bones showed that the kiwi's closest relatives were the giant elephant birds of Madagascar, not the moa of New Zealand.", w("Elephant_bird"), ("Science (copy at the University of British Columbia)", "https://www.zoology.ubc.ca/~jankowsk/Mitchell_et_al_2014_Science.pdf"), None),
"B06": ("Ducks and chickens belong together: waterfowl and landfowl form one old branch of birds. Coots only look like ducks.", w("Galloanserae"), ("The Timetree of Life (book chapter)", "https://TimeTree.org/public/data/pdf/Pereira2009Chap59.pdf"), None),
"B07": ("The dodo was a giant pigeon that could not fly. Its closest living relative is the Nicobar pigeon.", w("Dodo"), ("Oxford University Museum of Natural History", "https://oumnh.ox.ac.uk/node/315161"), None),
"B08": ("Toucans belong to the woodpecker order. Hornbills grew their big bill separately.", w("Piciformes"), (ADW, "https://animaldiversity.org/accounts/Ramphastos_toco/"), None),
"B09": ("Ostriches and emus sit on the same old branch of birds, the one that also holds kiwis and rheas.", w("Palaeognathae"), (BR, "https://www.britannica.com/animal/ratite"), None),
"B10": ("Swallows are songbirds, like sparrows, and parrots are the songbirds' closest relatives. Swifts only look like swallows.", (BR, "https://www.britannica.com/animal/passeriform/Annotated-classification"), ("Nature Communications", "https://www.nature.com/articles/ncomms1448"), None),

"R01": ("Birds are living dinosaurs, so a chicken is closer to T. rex than any crocodile or lizard.", (UCMP, "https://ucmp.berkeley.edu/taxa/verts/dinosauria/"), ("Smithsonian Magazine", "https://www.smithsonianmag.com/science-nature/t-rex-linked-to-chickens-ostriches-180940877/"), None),
"R02": ("The crocodile's closest living relatives are the birds, not the lizards.", (NHM, "https://www.nhm.ac.uk/discover/news/2023/november/unravelling-the-surprisingly-complex-history-of-crocodiles.html"), (BR, "https://www.britannica.com/animal/Crocodylomorpha"), None),
"R03": ("Genome studies place turtles next to crocodiles and birds, not lizards. The split dates back about 255 million years.", ("Smithsonian Insider", "https://insider.si.edu/2014/05/turtle-lineage-solved-new-study/"), ("BMC Biology", "https://link.springer.com/article/10.1186/1741-7007-10-65"), 255),
"R04": ("Pterosaurs were flying reptiles and the closest relatives of the dinosaurs, and birds are dinosaurs. Bats learned to fly separately.", (AMNH, "https://www.amnh.org/explore/news-blogs/what-is-a-pterosaur"), w("Archosaur"), None),
"R05": ("Ichthyosaurs were reptiles of the sea. Their dolphin shape evolved separately: a classic pair of look-alikes.", w("Ichthyosauria"), (NHM, "https://www.nhm.ac.uk/discover/what-is-an-ichthyosaur.html"), None),
"R06": ("Dimetrodon was not a dinosaur. It belongs to the line that led to mammals, so it is closer to a dog than to T. rex.", w("Dimetrodon"), (BR, "https://www.britannica.com/animal/pelycosaur"), None),
"R07": ("The axolotl is a salamander, and salamanders are amphibians, like frogs. Lizards are reptiles.", w("Lissamphibia"), ("Systematic Biology", "https://academic.oup.com/sysbio/article/70/1/49/5857591"), None),
"R08": ("The Komodo dragon and other monitor lizards share a branch with snakes. Crocodiles are closer to birds.", w("Toxicofera"), ("Systematic Biology", "https://academic.oup.com/sysbio/article/69/3/502/5573126"), None),
"R09": ("Snakes belong to the same order as lizards. A snake is, in effect, a highly modified lizard.", w("Squamata"), (BR, "https://www.britannica.com/animal/snake"), None),
"R10": ("Triceratops was a dinosaur, and birds are living dinosaurs. The rhino's horn is a look-alike.", w("Dinosaur"), (UCMP, "https://ucmp.berkeley.edu/taxa/verts/dinosauria/"), None),
"R11": ("Stegosaurus and Triceratops both belonged to the bird-hipped dinosaurs. T. rex came from the other great branch.", w("Ornithischia"), (UCMP, "https://ucmp.berkeley.edu/taxa/verts/dinosauria/"), None),
"R12": ("Velociraptor had feathers and was a close relative of birds.", (NHM, "https://www.nhm.ac.uk/discover/velociraptor-facts.html"), (AMNH, "https://www.amnh.org/explore/news-blogs/velociraptor-feather-evidence"), None),

"F01": ("Rays are flat relatives of sharks. A tuna, a bony fish, is closer to a dolphin than to a shark.", w("Elasmobranchii"), (BR, "https://www.britannica.com/animal/elasmobranch"), None),
"F02": ("Lungfish are the closest living relatives of all four-limbed animals, so a lungfish is closer to a cow than to a salmon. Their shared ancestor lived about 420 million years ago.", w("Lungfish"), ("Nature", "https://www.nature.com/articles/s41586-021-03198-8"), 420),
"F03": ("The whale shark is a shark. Whales are mammals, and a whale is closer to a tuna than to any shark.", w("Shark"), (BR, "https://www.britannica.com/animal/whale-shark"), None),
"F05": ("The octopus is a mollusc, like the snail.", w("Mollusca"), (ADW, "https://animaldiversity.org/accounts/Mollusca/"), None),
"F06": ("Corals are animals, and close relatives of jellyfish.", w("Cnidaria"), (BR, "https://www.britannica.com/animal/cnidarian"), None),
"F07": ("Horseshoe crabs are not crabs. They are relatives of spiders and scorpions.", w("Horseshoe_crab"), (BR, "https://www.britannica.com/animal/horseshoe-crab"), None),
"F08": ("Barnacles look like shellfish, but they are crustaceans, relatives of crabs.", w("Barnacle"), ("Florida Museum", "https://www.floridamuseum.ufl.edu/science/five-facts-barnacles/"), None),
"F09": ("The seahorse is a bony fish, in the same big group as the tuna.", w("Teleost"), ("PLOS Currents", "https://currents.plos.org/treeoflife/article/the-tree-of-life-and-a-new-classification-of-bony-fishes/"), None),
"F10": ("Sea urchins and starfish belong to the same group. Even a hedgehog is closer to a sea urchin than a jellyfish is.", w("Echinoderm"), (BR, "https://www.britannica.com/animal/echinoderm"), None),
"F11": ("Eels are bony fish, like salmon. Lampreys look like eels but are jawless fish from a far older branch. Even a snake is closer to an eel.", w("Actinopterygii"), ("PLOS Currents", "https://currents.plos.org/treeoflife/article/the-tree-of-life-and-a-new-classification-of-bony-fishes/"), None),
"F12": ("Sea cucumbers are relatives of starfish and sea urchins, not of slugs.", w("Echinoderm"), (BR, "https://www.britannica.com/animal/echinoderm"), None),

"I01": ("Termites are not ants. They are cockroaches that became social.", w("Termite"), ("University of Queensland", "https://uq.pressbooks.pub/insect-science/chapter/orders-of-insects-blattodea-includes-isoptera/"), None),
"I02": ("Ants evolved from wasps and belong with wasps and bees. Termites are relatives of cockroaches.", w("Ant"), ("Current Biology (copy at Cornell University)", "https://www.danforthlab.entomology.cornell.edu/wp-content/uploads/branstetter_etal_2017_currbiol.pdf"), None),
"I03": ("Ticks are arachnids, like spiders, not insects.", w("Arachnid"), ("Nature Communications", "https://www.nature.com/articles/s41467-019-10244-7"), None),
"I04": ("Fireflies are not flies. They are beetles, like ladybirds.", w("Beetle"), ("Britannica Kids", "https://kids.britannica.com/students/article/beetle/273149"), None),
"I05": ("Woodlice are crustaceans that live on land, relatives of shrimp and crabs.", w("Malacostraca"), (BR, "https://www.britannica.com/animal/malacostracan"), None),
"I06": ("Scorpions are arachnids, like spiders. Lobsters only look similar.", w("Arachnid"), ("Nature Communications", "https://www.nature.com/articles/s41467-019-10244-7"), None),
"I07": ("The praying mantis's closest relatives are cockroaches and termites.", w("Mantis"), (PMC, "https://pmc.ncbi.nlm.nih.gov/articles/PMC4511787/"), None),
"I08": ("Butterflies and moths form one order of insects.", w("Lepidoptera"), ("Boise State University", "https://scholarworks.boisestate.edu/bio_facpubs/600"), None),
"I09": ("Centipedes and millipedes are close relatives. Both have many legs, and neither is an insect.", w("Myriapoda"), (UCMP, "https://ucmp.berkeley.edu/arthropoda/uniramia/myriapoda.html"), None),
"I10": ("Slugs are molluscs, like the octopus. Earthworms belong to another group.", w("Mollusca"), (NHM, "https://www.nhm.ac.uk/discover/molluscs.html"), None),
"I11": ("Leeches are close relatives of earthworms.", w("Clitellata"), (UCMP, "https://ucmp.berkeley.edu/annelida/annelida.html"), None),
"I12": ("Fleas are closer to flies than to lice. Ticks are not insects at all.", w("Holometabola"), ("BMC Biology", "https://link.springer.com/article/10.1186/1741-7007-7-34"), None),
"I13": ("Bees evolved from wasps.", w("Bee"), ("Current Biology (copy at Cornell University)", "https://www.danforthlab.entomology.cornell.edu/wp-content/uploads/branstetter_etal_2017_currbiol.pdf"), None),

"P01": ("Fungi are closer to animals than to plants. A mushroom is your distant cousin, not the oak's.", w("Fungus"), ("East Carolina University", "https://thescholarship.ecu.edu/handle/10342/7740"), None),
"P02": ("The peanut is not a nut. It is a legume, like peas and beans.", w("Peanut"), ("Royal Botanic Gardens, Kew", "https://www.kew.org/plants/peanut"), None),
"P03": ("Tomato and potato belong to the same genus. Chili peppers are in the same family, the nightshades.", w("Tomato"), ("Nature", "https://www.nature.com/articles/nature11119"), None),
"P04": ("Strawberries belong to the rose family, and within it they sit closer to roses than to apples.", w("Rosaceae"), ("Missouri Botanical Garden", "https://www.mobot.org/MOBOT/research/APweb/orders/rosalesweb.htm"), None),
"P05": ("The almond is a close relative of the peach: they belong to the same genus.", w("Almond"), (BR, "https://www.britannica.com/plant/Prunus"), None),
"P06": ("Cashew and mango belong to the same family, together with pistachio.", w("Anacardiaceae"), (BR, "https://www.britannica.com/plant/Anacardiaceae"), None),
"P07": ("Bananas belong to the ginger order of plants.", w("Zingiberales"), (BR, "https://www.britannica.com/plant/Zingiberales"), None),
"P08": ("The cocoa tree is in the mallow family, with cotton, okra and hibiscus.", w("Malvaceae"), (BR, "https://www.britannica.com/plant/Malvaceae"), None),
"P09": ("Cacti belong to the same order as beetroot, spinach and carnations. Aloe only looks like a cactus.", w("Caryophyllales"), ("Botanischer Garten Berlin", "https://bo.berlin/en/plants/research-program-caryophyllales"), None),
"P10": ("Chili peppers are nightshades, like tomatoes. Black pepper is an unrelated plant.", w("Solanaceae"), ("Encyclopedia.com", "https://www.encyclopedia.com/science/encyclopedias-almanacs-transcripts-and-maps/tomato-family-solanaceae"), None),
"P11": ("Bamboo is a grass, like rice and wheat.", w("Poaceae"), ("Nature Communications", "https://www.nature.com/articles/ncomms1482"), None),
}
