# Long Lost Cousin: every animal, plant or fungus that may appear, with the names PhyloPic is asked for.
# key: (label, "the ..." form for sentences, [scientific names to try, most specific first])
ORG = {
# ---- mammals
"hippo": ("Hippo", "the hippo", ["Hippopotamus amphibius", "Hippopotamidae"]),
"whale": ("Whale", "the whale", ["Balaenoptera musculus", "Megaptera novaeangliae", "Balaenoptera physalus", "Balaenopteridae", "Mysticeti"]),
"pig": ("Pig", "the pig", ["Sus scrofa", "Sus scrofa domesticus", "Suidae"]),
"rhino": ("Rhino", "the rhino", ["Ceratotherium simum", "Diceros bicornis", "Rhinoceros unicornis", "Rhinocerotidae"]),
"elephant": ("Elephant", "the elephant", ["Loxodonta africana", "Elephas maximus", "Elephantidae"]),
"manatee": ("Manatee", "the manatee", ["Trichechus manatus", "Trichechus", "Trichechidae", "Sirenia"]),
"hyrax": ("Hyrax", "the hyrax", ["Procavia capensis", "Procaviidae", "Hyracoidea"]),
"guinea_pig": ("Guinea pig", "the guinea pig", ["Cavia porcellus", "Cavia aperea", "Caviidae"]),
"rabbit": ("Rabbit", "the rabbit", ["Oryctolagus cuniculus", "Sylvilagus floridanus", "Leporidae"]),
"hyena": ("Hyena", "the hyena", ["Crocuta crocuta", "Hyaena hyaena", "Hyaenidae"]),
"cat": ("Cat", "the cat", ["Felis catus", "Felis silvestris", "Felis silvestris catus"]),
"dog": ("Dog", "the dog", ["Canis lupus familiaris", "Canis familiaris", "Canis lupus"]),
"bear": ("Bear", "the bear", ["Ursus arctos", "Ursus americanus", "Ursidae"]),
"red_panda": ("Red panda", "the red panda", ["Ailurus fulgens", "Ailuridae"]),
"raccoon": ("Raccoon", "the raccoon", ["Procyon lotor", "Procyonidae"]),
"giant_panda": ("Giant panda", "the giant panda", ["Ailuropoda melanoleuca"]),
"polar_bear": ("Polar bear", "the polar bear", ["Ursus maritimus"]),
"koala": ("Koala", "the koala", ["Phascolarctos cinereus", "Phascolarctidae"]),
"wombat": ("Wombat", "the wombat", ["Vombatus ursinus", "Lasiorhinus latifrons", "Vombatidae"]),
"kangaroo": ("Kangaroo", "the kangaroo", ["Macropus giganteus", "Osphranter rufus", "Macropus rufus", "Macropodidae"]),
"dolphin": ("Dolphin", "the dolphin", ["Tursiops truncatus", "Delphinus delphis", "Delphinidae"]),
"cow": ("Cow", "the cow", ["Bos taurus", "Bos primigenius", "Bos primigenius taurus"]),
"seal": ("Seal", "the seal", ["Phoca vitulina", "Halichoerus grypus", "Phocidae"]),
"sea_lion": ("Sea lion", "the sea lion", ["Zalophus californianus", "Otariidae"]),
"bat": ("Bat", "the bat", ["Myotis lucifugus", "Pipistrellus pipistrellus", "Desmodus rotundus", "Pteropus vampyrus", "Chiroptera"]),
"horse": ("Horse", "the horse", ["Equus ferus caballus", "Equus caballus", "Equus ferus"]),
"mouse": ("Mouse", "the mouse", ["Mus musculus", "Apodemus sylvaticus", "Muridae"]),
"monkey": ("Monkey", "the monkey", ["Macaca mulatta", "Macaca fascicularis", "Cercopithecus", "Cercopithecidae"]),
"human": ("Human", "the human", ["Homo sapiens", "Homo sapiens sapiens"]),
"chimp": ("Chimp", "the chimp", ["Pan troglodytes", "Pan paniscus"]),
"gorilla": ("Gorilla", "the gorilla", ["Gorilla gorilla", "Gorilla beringei"]),
"orangutan": ("Orangutan", "the orangutan", ["Pongo pygmaeus", "Pongo abelii"]),
"shrew": ("Shrew", "the shrew", ["Sorex araneus", "Sorex cinereus", "Crocidura russula", "Soricidae"]),
"hedgehog": ("Hedgehog", "the hedgehog", ["Erinaceus europaeus", "Atelerix albiventris", "Erinaceidae"]),
"thylacine": ("Tasmanian tiger", "the Tasmanian tiger", ["Thylacinus cynocephalus", "Thylacinidae"]),
"wolf": ("Wolf", "the wolf", ["Canis lupus", "Canis lupus lupus"]),
"tiger": ("Tiger", "the tiger", ["Panthera tigris", "Panthera leo", "Panthera"]),
"sugar_glider": ("Sugar glider", "the sugar glider", ["Petaurus breviceps", "Petauridae"]),
"flying_squirrel": ("Flying squirrel", "the flying squirrel", ["Glaucomys volans", "Glaucomys sabrinus", "Pteromys volans", "Pteromyini"]),
"armadillo": ("Armadillo", "the armadillo", ["Dasypus novemcinctus", "Dasypodidae", "Cingulata"]),
"sloth": ("Sloth", "the sloth", ["Bradypus variegatus", "Bradypus tridactylus", "Choloepus hoffmanni", "Choloepus didactylus", "Folivora"]),
"pangolin": ("Pangolin", "the pangolin", ["Manis pentadactyla", "Manis javanica", "Smutsia gigantea", "Manidae", "Pholidota"]),
"anteater": ("Anteater", "the anteater", ["Myrmecophaga tridactyla", "Tamandua tetradactyla", "Myrmecophagidae"]),
"echidna": ("Echidna", "the echidna", ["Tachyglossus aculeatus", "Zaglossus bruijni", "Tachyglossidae"]),
"aardvark": ("Aardvark", "the aardvark", ["Orycteropus afer", "Orycteropodidae"]),
"platypus": ("Platypus", "the platypus", ["Ornithorhynchus anatinus"]),
"porcupine": ("Porcupine", "the porcupine", ["Hystrix cristata", "Erethizon dorsatum", "Hystricidae"]),
"camel": ("Camel", "the camel", ["Camelus dromedarius", "Camelus bactrianus", "Camelus ferus"]),
"llama": ("Llama", "the llama", ["Lama glama", "Vicugna pacos", "Lama guanicoe"]),
"giraffe": ("Giraffe", "the giraffe", ["Giraffa camelopardalis", "Giraffa"]),
"okapi": ("Okapi", "the okapi", ["Okapia johnstoni"]),
"zebra": ("Zebra", "the zebra", ["Equus quagga", "Equus zebra", "Equus grevyi", "Equus burchellii"]),
"otter": ("Otter", "the otter", ["Lutra lutra", "Lontra canadensis", "Enhydra lutris", "Lutrinae"]),
"weasel": ("Weasel", "the weasel", ["Mustela nivalis", "Mustela erminea", "Mustela putorius", "Mustelidae"]),
"beaver": ("Beaver", "the beaver", ["Castor canadensis", "Castor fiber", "Castoridae"]),
"squirrel": ("Squirrel", "the squirrel", ["Sciurus vulgaris", "Sciurus carolinensis", "Sciuridae"]),
"meerkat": ("Meerkat", "the meerkat", ["Suricata suricatta", "Herpestidae"]),
"prairie_dog": ("Prairie dog", "the prairie dog", ["Cynomys ludovicianus", "Cynomys gunnisoni", "Marmota marmota", "Marmota monax"]),
"capybara": ("Capybara", "the capybara", ["Hydrochoerus hydrochaeris", "Hydrochoerus"]),
"hamster": ("Hamster", "the hamster", ["Mesocricetus auratus", "Cricetus cricetus", "Cricetinae"]),
"narwhal": ("Narwhal", "the narwhal", ["Monodon monoceros"]),
"beluga": ("Beluga", "the beluga", ["Delphinapterus leucas"]),
"walrus": ("Walrus", "the walrus", ["Odobenus rosmarus"]),
"swordfish": ("Swordfish", "the swordfish", ["Xiphias gladius", "Istiophorus platypterus", "Istiophoridae"]),
"marlin": ("Marlin", "the marlin", ["Kajikia audax"]),
"orca": ("Orca", "the orca", ["Orcinus orca"]),
"humpback": ("Humpback whale", "the humpback whale", ["Megaptera novaeangliae"]),
"mammoth": ("Mammoth", "the mammoth", ["Mammuthus primigenius", "Mammuthus columbi", "Mammuthus"]),
"asian_elephant": ("Asian elephant", "the Asian elephant", ["Elephas maximus"]),
"african_elephant": ("African elephant", "the African elephant", ["Loxodonta africana", "Loxodonta cyclotis"]),
"mastodon": ("Mastodon", "the mastodon", ["Mammut americanum", "Mammut", "Mammutidae"]),
"tapir": ("Tapir", "the tapir", ["Tapirus terrestris", "Tapirus indicus", "Tapirus bairdii", "Tapiridae"]),
"deer": ("Deer", "the deer", ["Cervus elaphus", "Odocoileus virginianus", "Capreolus capreolus", "Cervidae"]),
# ---- birds
"falcon": ("Falcon", "the falcon", ["Falco peregrinus", "Falco tinnunculus", "Falconidae"]),
"parrot": ("Parrot", "the parrot", ["Ara macao", "Psittacus erithacus", "Amazona aestiva", "Melopsittacus undulatus", "Psittaciformes"]),
"eagle": ("Eagle", "the eagle", ["Haliaeetus leucocephalus", "Aquila chrysaetos", "Accipitridae"]),
"heron": ("Heron", "the heron", ["Ardea cinerea", "Ardea herodias", "Ardea alba", "Ardeidae"]),
"flamingo": ("Flamingo", "the flamingo", ["Phoenicopterus roseus", "Phoenicopterus ruber", "Phoenicopteridae"]),
"grebe": ("Grebe", "the grebe", ["Podiceps cristatus", "Podilymbus podiceps", "Podicipedidae"]),
"stork": ("Stork", "the stork", ["Ciconia ciconia", "Ciconia nigra", "Ciconiidae"]),
"penguin": ("Penguin", "the penguin", ["Aptenodytes forsteri", "Aptenodytes patagonicus", "Pygoscelis adeliae", "Spheniscidae"]),
"albatross": ("Albatross", "the albatross", ["Diomedea exulans", "Phoebastria", "Thalassarche melanophris", "Diomedeidae"]),
"puffin": ("Puffin", "the puffin", ["Fratercula arctica", "Alca torda", "Alcidae"]),
"swift": ("Swift", "the swift", ["Apus apus", "Chaetura pelagica", "Apodidae"]),
"hummingbird": ("Hummingbird", "the hummingbird", ["Archilochus colubris", "Calypte anna", "Trochilidae"]),
"swallow": ("Swallow", "the swallow", ["Hirundo rustica", "Delichon urbicum", "Hirundinidae"]),
"kiwi": ("Kiwi", "the kiwi", ["Apteryx australis", "Apteryx mantelli", "Apteryx owenii", "Apterygidae"]),
"elephant_bird": ("Elephant bird", "the elephant bird", ["Aepyornis maximus", "Aepyornis", "Aepyornithidae"]),
"moa": ("Moa", "the moa", ["Dinornis robustus", "Dinornis novaezealandiae", "Dinornis", "Dinornithiformes"]),
"ostrich": ("Ostrich", "the ostrich", ["Struthio camelus"]),
"emu": ("Emu", "the emu", ["Dromaius novaehollandiae", "Casuarius casuarius"]),
"chicken": ("Chicken", "the chicken", ["Gallus gallus domesticus", "Gallus gallus"]),
"coot": ("Coot", "the coot", ["Fulica atra", "Fulica americana", "Gallinula chloropus", "Rallidae"]),
"dodo": ("Dodo", "the dodo", ["Raphus cucullatus"]),
"pigeon": ("Pigeon", "the pigeon", ["Columba livia", "Columba palumbus", "Columbidae"]),
"turkey": ("Turkey", "the turkey", ["Meleagris gallopavo"]),
"toucan": ("Toucan", "the toucan", ["Ramphastos toco", "Ramphastos sulfuratus", "Ramphastidae"]),
"woodpecker": ("Woodpecker", "the woodpecker", ["Dendrocopos major", "Picus viridis", "Dryocopus martius", "Picidae"]),
"hornbill": ("Hornbill", "the hornbill", ["Buceros bicornis", "Buceros rhinoceros", "Bucerotidae"]),
"crane": ("Crane", "the crane", ["Grus grus", "Grus canadensis", "Gruidae"]),
"duck": ("Duck", "the duck", ["Anas platyrhynchos", "Anatidae"]),
"sparrow": ("Sparrow", "the sparrow", ["Passer domesticus", "Passeridae"]),
"gull": ("Gull", "the gull", ["Larus argentatus", "Larus", "Laridae"]),
# ---- reptiles, amphibians, dinosaurs
"trex": ("T. rex", "the T. rex", ["Tyrannosaurus rex", "Tyrannosaurus"]),
"crocodile": ("Crocodile", "the crocodile", ["Crocodylus niloticus", "Crocodylus porosus", "Alligator mississippiensis", "Crocodylidae"]),
"komodo": ("Komodo dragon", "the Komodo dragon", ["Varanus komodoensis", "Varanus"]),
"lizard": ("Lizard", "the lizard", ["Lacerta agilis", "Podarcis muralis", "Anolis carolinensis", "Lacertidae"]),
"turtle": ("Turtle", "the turtle", ["Chelonia mydas", "Caretta caretta", "Testudo graeca", "Testudines"]),
"frog": ("Frog", "the frog", ["Rana temporaria", "Lithobates catesbeianus", "Pelophylax", "Ranidae", "Anura"]),
"salamander": ("Salamander", "the salamander", ["Salamandra salamandra", "Salamandridae", "Caudata"]),
"axolotl": ("Axolotl", "the axolotl", ["Ambystoma mexicanum", "Ambystoma"]),
"snake": ("Snake", "the snake", ["Naja naja", "Vipera berus", "Python regius", "Python molurus", "Serpentes"]),
"iguana": ("Iguana", "the iguana", ["Iguana iguana", "Iguanidae"]),
"pterodactyl": ("Pterodactyl", "the pterodactyl", ["Pterodactylus antiquus", "Pterodactylus", "Pteranodon longiceps", "Pteranodon"]),
"ichthyosaur": ("Ichthyosaur", "the ichthyosaur", ["Ichthyosaurus communis", "Ichthyosaurus", "Stenopterygius quadriscissus", "Ophthalmosaurus icenicus", "Ichthyosauria"]),
"dimetrodon": ("Dimetrodon", "the Dimetrodon", ["Dimetrodon grandis", "Dimetrodon limbatus", "Dimetrodon"]),
"triceratops": ("Triceratops", "the Triceratops", ["Triceratops horridus", "Triceratops"]),
"stegosaurus": ("Stegosaurus", "the Stegosaurus", ["Stegosaurus stenops", "Stegosaurus"]),
"velociraptor": ("Velociraptor", "the Velociraptor", ["Velociraptor mongoliensis", "Velociraptor"]),
# ---- fish and sea life
"shark": ("Shark", "the shark", ["Carcharodon carcharias", "Carcharhinus leucas", "Prionace glauca", "Lamnidae"]),
"great_white": ("Great white shark", "the great white shark", ["Carcharodon carcharias"]),
"whale_shark": ("Whale shark", "the whale shark", ["Rhincodon typus"]),
"ray": ("Ray", "the ray", ["Mobula birostris", "Manta birostris", "Raja clavata", "Dasyatis pastinaca", "Batoidea"]),
"tuna": ("Tuna", "the tuna", ["Thunnus thynnus", "Thunnus albacares", "Thunnus"]),
"salmon": ("Salmon", "the salmon", ["Salmo salar", "Oncorhynchus mykiss", "Salmonidae"]),
"goldfish": ("Goldfish", "the goldfish", ["Carassius auratus", "Cyprinus carpio"]),
"eel": ("Eel", "the eel", ["Anguilla anguilla", "Anguilla rostrata", "Anguillidae"]),
"lamprey": ("Lamprey", "the lamprey", ["Petromyzon marinus", "Lampetra fluviatilis", "Petromyzontidae"]),
"lungfish": ("Lungfish", "the lungfish", ["Neoceratodus forsteri", "Protopterus annectens", "Lepidosiren paradoxa", "Dipnoi"]),
"seahorse": ("Seahorse", "the seahorse", ["Hippocampus hippocampus", "Hippocampus kuda", "Hippocampus"]),
"flounder": ("Flounder", "the flounder", ["Platichthys flesus", "Pleuronectes platessa", "Pleuronectidae"]),
"starfish": ("Starfish", "the starfish", ["Asterias rubens", "Asterias", "Asteroidea"]),
"sea_urchin": ("Sea urchin", "the sea urchin", ["Strongylocentrotus purpuratus", "Paracentrotus lividus", "Echinoidea"]),
"sea_cucumber": ("Sea cucumber", "the sea cucumber", ["Holothuria", "Apostichopus japonicus", "Holothuroidea"]),
"jellyfish": ("Jellyfish", "the jellyfish", ["Aurelia aurita", "Chrysaora", "Scyphozoa"]),
"coral": ("Coral", "the coral", ["Acropora", "Acropora millepora", "Scleractinia", "Anthozoa"]),
"sponge": ("Sponge", "the sponge", ["Spongia officinalis", "Amphimedon queenslandica", "Demospongiae", "Porifera"]),
"octopus": ("Octopus", "the octopus", ["Octopus vulgaris", "Octopus bimaculoides", "Octopodidae"]),
"squid": ("Squid", "the squid", ["Loligo vulgaris", "Doryteuthis pealeii", "Architeuthis dux", "Loliginidae"]),
"snail": ("Snail", "the snail", ["Helix pomatia", "Cornu aspersum", "Cepaea nemoralis", "Helicidae"]),
"slug": ("Slug", "the slug", ["Arion ater", "Limax maximus", "Arion", "Arionidae"]),
"mussel": ("Mussel", "the mussel", ["Mytilus edulis", "Mytilus galloprovincialis", "Mytilidae"]),
"crab": ("Crab", "the crab", ["Cancer pagurus", "Callinectes sapidus", "Carcinus maenas", "Brachyura"]),
"lobster": ("Lobster", "the lobster", ["Homarus americanus", "Homarus gammarus", "Nephropidae"]),
"shrimp": ("Shrimp", "the shrimp", ["Litopenaeus vannamei", "Penaeus monodon", "Crangon crangon", "Palaemon serratus", "Caridea"]),
"horseshoe_crab": ("Horseshoe crab", "the horseshoe crab", ["Limulus polyphemus", "Limulidae"]),
"barnacle": ("Barnacle", "the barnacle", ["Semibalanus balanoides", "Balanus", "Lepas anatifera", "Cirripedia"]),
# ---- insects and other small creatures
"spider": ("Spider", "the spider", ["Araneus diadematus", "Latrodectus", "Lycosidae", "Araneae"]),
"scorpion": ("Scorpion", "the scorpion", ["Pandinus imperator", "Androctonus australis", "Centruroides", "Scorpiones"]),
"tick": ("Tick", "the tick", ["Ixodes scapularis", "Ixodes ricinus", "Ixodidae", "Ixodida"]),
"butterfly": ("Butterfly", "the butterfly", ["Papilio machaon", "Danaus plexippus", "Vanessa atalanta", "Papilionidae"]),
"moth": ("Moth", "the moth", ["Bombyx mori", "Actias luna", "Manduca sexta", "Saturniidae"]),
"dragonfly": ("Dragonfly", "the dragonfly", ["Anax imperator", "Libellula depressa", "Anisoptera", "Odonata"]),
"bee": ("Bee", "the bee", ["Apis mellifera", "Bombus terrestris", "Apidae"]),
"wasp": ("Wasp", "the wasp", ["Vespula vulgaris", "Vespa crabro", "Polistes dominula", "Vespidae"]),
"ant": ("Ant", "the ant", ["Formica rufa", "Camponotus", "Lasius niger", "Formicidae"]),
"termite": ("Termite", "the termite", ["Reticulitermes flavipes", "Zootermopsis", "Mastotermes darwiniensis", "Macrotermes", "Isoptera", "Termitoidae"]),
"cockroach": ("Cockroach", "the cockroach", ["Periplaneta americana", "Blattella germanica", "Blatta orientalis", "Blattodea"]),
"mantis": ("Praying mantis", "the praying mantis", ["Mantis religiosa", "Mantidae", "Mantodea"]),
"grasshopper": ("Grasshopper", "the grasshopper", ["Locusta migratoria", "Schistocerca gregaria", "Acrididae"]),
"firefly": ("Firefly", "the firefly", ["Photinus pyralis", "Lampyris noctiluca", "Lampyridae"]),
"ladybird": ("Ladybird", "the ladybird", ["Coccinella septempunctata", "Harmonia axyridis", "Coccinellidae"]),
"beetle": ("Beetle", "the beetle", ["Lucanus cervus", "Dynastes hercules", "Scarabaeidae", "Coleoptera"]),
"housefly": ("Fly", "the fly", ["Musca domestica", "Drosophila melanogaster", "Calliphora vicina", "Muscidae"]),
"flea": ("Flea", "the flea", ["Pulex irritans", "Ctenocephalides felis", "Siphonaptera"]),
"louse": ("Louse", "the louse", ["Pediculus humanus", "Pediculus humanus capitis", "Phthiraptera"]),
"woodlouse": ("Woodlouse", "the woodlouse", ["Armadillidium vulgare", "Porcellio scaber", "Oniscus asellus", "Oniscidea", "Isopoda"]),
"millipede": ("Millipede", "the millipede", ["Narceus americanus", "Julus", "Julida", "Diplopoda"]),
"centipede": ("Centipede", "the centipede", ["Scolopendra", "Scolopendra gigantea", "Lithobius forficatus", "Chilopoda"]),
"earthworm": ("Earthworm", "the earthworm", ["Lumbricus terrestris", "Lumbricidae", "Oligochaeta"]),
"leech": ("Leech", "the leech", ["Hirudo medicinalis", "Hirudinea", "Hirudinidae"]),
# ---- plants and fungi
"mushroom": ("Mushroom", "the mushroom", ["Agaricus bisporus", "Amanita muscaria", "Boletus edulis", "Agaricales"]),
"moss": ("Moss", "moss", ["Physcomitrella patens", "Physcomitrium patens", "Sphagnum", "Polytrichum", "Bryophyta"]),
"oak": ("Oak tree", "the oak tree", ["Quercus robur", "Quercus alba", "Quercus"]),
"peanut": ("Peanut", "the peanut", ["Arachis hypogaea", "Arachis"]),
"pea": ("Pea", "the pea", ["Pisum sativum", "Phaseolus vulgaris", "Glycine max"]),
"walnut": ("Walnut", "the walnut", ["Juglans regia", "Juglans nigra", "Juglandaceae"]),
"pine": ("Pine tree", "the pine tree", ["Pinus sylvestris", "Pinus taeda", "Pinus"]),
"almond": ("Almond", "the almond", ["Prunus dulcis", "Prunus amygdalus"]),
"peach": ("Peach", "the peach", ["Prunus persica"]),
"apple": ("Apple", "the apple", ["Malus domestica", "Malus pumila", "Malus"]),
"tomato": ("Tomato", "the tomato", ["Solanum lycopersicum", "Lycopersicon esculentum"]),
"potato": ("Potato", "the potato", ["Solanum tuberosum"]),
"chili": ("Chili pepper", "the chili pepper", ["Capsicum annuum", "Capsicum"]),
"cucumber": ("Cucumber", "the cucumber", ["Cucumis sativus", "Cucurbita pepo", "Cucurbitaceae"]),
"strawberry": ("Strawberry", "the strawberry", ["Fragaria vesca", "Fragaria ananassa", "Fragaria"]),
"rose": ("Rose", "the rose", ["Rosa canina", "Rosa chinensis", "Rosa rugosa"]),
"cashew": ("Cashew", "the cashew", ["Anacardium occidentale", "Anacardium"]),
"mango": ("Mango", "the mango", ["Mangifera indica", "Mangifera"]),
"banana": ("Banana", "the banana", ["Musa acuminata", "Musa balbisiana", "Musaceae"]),
"ginger": ("Ginger", "ginger", ["Zingiber officinale", "Zingiberaceae"]),
"palm": ("Palm tree", "the palm tree", ["Cocos nucifera", "Phoenix dactylifera", "Arecaceae"]),
"cocoa": ("Cocoa", "cocoa", ["Theobroma cacao", "Theobroma"]),
"cotton": ("Cotton", "cotton", ["Gossypium hirsutum", "Gossypium"]),
"coffee": ("Coffee", "coffee", ["Coffea arabica", "Coffea canephora", "Coffea"]),
"tea": ("Tea", "tea", ["Camellia sinensis", "Camellia"]),
"bamboo": ("Bamboo", "bamboo", ["Phyllostachys edulis", "Bambusa vulgaris", "Bambusoideae"]),
"rice": ("Rice", "rice", ["Oryza sativa"]),
"cactus": ("Cactus", "the cactus", ["Carnegiea gigantea", "Opuntia ficus-indica", "Opuntia", "Cactaceae"]),
"beet": ("Beetroot", "the beetroot", ["Beta vulgaris"]),
"aloe": ("Aloe", "the aloe", ["Aloe vera", "Aloe"]),
"pineapple": ("Pineapple", "the pineapple", ["Ananas comosus", "Bromeliaceae"]),
"black_pepper": ("Black pepper", "black pepper", ["Piper nigrum", "Piper"]),
"mustard": ("Mustard", "mustard", ["Sinapis alba", "Brassica nigra", "Brassica juncea", "Brassica oleracea"]),
}
