# -*- coding: utf-8 -*-
"""Twin or Trap: the stock, as written after the dictionary checks (6 Oct 2026, night).

Each pair: a word that looks the same in two languages, and whether it means the same in both (twin, a true friend)
or something else (trap, a false friend). Every meaning was read in two dictionaries; the quotes are in evidence.txt.
The meanings, the sentences and their translations, and the mix-up lines are Logicers' own words: short, plain,
showing only the checked meaning. Never copied from a dictionary.

Fields of a pair (W):
  id      stable id: <foreign language>-<word> for pairs with English, <lang>-<lang>-<word> otherwise. Never change it.
  v       "twin" or "trap"
  a, b    the two sides: (language code, word as written, meaning, [(dictionary, address), (dictionary, address)])
          plus, for Russian, the word in Latin letters (tr). b is English for pairs with English.
  say     the sentences read out loud: one for a pair with English (in the other language), two for a pair without
          English (one per language). (language, sentence with the word in [brackets], English translation[, Latin letters])
  mix     traps only: one of the sentences as it would sound to a speaker of the other language, that is, if the
          word meant what it means on the other side (build.py finds which sentence: the one it shares most words with).
To add a pair: read two dictionaries for each word, put the quotes into evidence.txt, add the pair here, run build.py.
"""

LANGS = {"en": "English", "de": "German", "nl": "Dutch", "fr": "French", "es": "Spanish", "it": "Italian",
         "pt": "Portuguese", "sv": "Swedish", "ru": "Russian", "tr": "Turkish"}

MW = "Merriam-Webster"; OX = "Oxford Learner's"; BR = "Britannica Dictionary"
DWDS = "DWDS"; WAHRIG = "WAHRIG (on DWDS)"; WDG = "WDG (on DWDS)"; WIKT = "Wiktionary"
WOORDEN = "woorden.org"; VD = "Van Dale 1950 (on Ensie)"; MUIS = "Ensie (Muiswerk)"
LAR = "Larousse"; LARC = "Larousse Collège"; LARFE = "Larousse French-English"; WIKTFR = "Wiktionnaire"; ACAD = "Académie française"
RAE = "RAE"; SD = "SpanishDict"; TREC = "Treccani"; DEM = "De Mauro"; PRI = "Priberam"; INF = "Infopédia"
SYN = "synonymer.se"; WOX = "Woxikon"; USH = "Ushakov"; GRAM = "Gramota.ru"; TUR = "Tureng"; ZAR = "Zargan"; SES = "Sesli Sözlük"


def W(id, v, a, b, say, mix=""):
    return dict(id=id, v=v, a=a, b=b, say=say, mix=mix)


PAIRS = [
    # ---------------- traps (false friends) ----------------
    W("de-gift", "trap",
      ("de", "Gift", "poison", [(DWDS, "https://www.dwds.de/wb/Gift"), (WIKT, "https://en.wiktionary.org/wiki/Gift")]),
      ("en", "gift", "a present (or a talent)", [(MW, "https://www.merriam-webster.com/dictionary/gifts"), (BR, "https://www.britannica.com/dictionary/gift")]),
      [("de", "Diese Beeren sind [Gift].", "These berries are poison.")],
      "These berries are a gift."),
    W("de-handy", "trap",
      ("de", "Handy", "a mobile phone", [(DWDS, "https://www.dwds.de/wb/Handy"), (WAHRIG, "https://www.dwds.de/wb/wdw/search/?q=Handy")]),
      ("en", "handy", "useful, or close at hand", [(OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/handy"), (MW, "https://www.merriam-webster.com/dictionary/handier")]),
      [("de", "Sein [Handy] klingelt.", "His mobile phone is ringing.")],
      "His handy is ringing."),
    W("de-bald", "trap",
      ("de", "bald", "soon", [(DWDS, "https://www.dwds.de/wb/bald"), (WAHRIG, "https://www.dwds.de/wb/wdw/bald")]),
      ("en", "bald", "with little or no hair on the head", [(MW, "https://www.merriam-webster.com/dictionary/bald"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/bald")]),
      [("de", "Ich bin [bald] zu Hause.", "I'll be home soon.")],
      "I am bald at home."),
    W("de-hut", "trap",
      ("de", "Hut", "a hat", [(DWDS, "https://www.dwds.de/wb/Hut"), (WAHRIG, "https://www.dwds.de/wb/wdw/search/?q=Hut")]),
      ("en", "hut", "a small, simple house or shelter", [(MW, "https://www.merriam-webster.com/dictionary/hut"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/hut")]),
      [("de", "Opa trägt einen [Hut].", "Grandpa is wearing a hat.")],
      "Grandpa is wearing a hut."),
    W("de-mantel", "trap",
      ("de", "Mantel", "a coat", [(DWDS, "https://www.dwds.de/wb/Mantel"), (WAHRIG, "https://www.dwds.de/wb/wdw/search/?q=Mantel")]),
      ("en", "mantel", "the shelf above a fireplace", [(MW, "https://www.merriam-webster.com/dictionary/mantels"), (BR, "https://www.britannica.com/dictionary/mantel")]),
      [("de", "Zieh deinen [Mantel] an!", "Put your coat on!")],
      "Put your mantel on!"),
    W("de-nl-rat", "trap",
      ("de", "Rat", "advice (or a council)", [(DWDS, "https://www.dwds.de/wb/Rat"), (WAHRIG, "https://www.dwds.de/wb/wdw/search/?q=Rat")]),
      ("nl", "rat", "a rat, the animal", [(WOORDEN, "https://www.woorden.org/woord/rat"), (VD, "https://www.ensie.nl/van-dale/rat")]),
      [("de", "Ich brauche deinen [Rat].", "I need your advice."),
       ("nl", "De [rat] woont onder de brug.", "The rat lives under the bridge.")],
      "I need your rat."),
    W("nl-room", "trap",
      ("nl", "room", "cream, the fat of milk", [(WOORDEN, "https://www.woorden.org/woord/room"), (VD, "https://www.ensie.nl/van-dale/room")]),
      ("en", "room", "a space with walls inside a building", [(MW, "https://www.merriam-webster.com/dictionary/room"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/room_1")]),
      [("nl", "Wil je [room] in je koffie?", "Would you like cream in your coffee?")],
      "Would you like a room in your coffee?"),
    W("nl-big", "trap",
      ("nl", "big", "a piglet, a young pig", [(WOORDEN, "https://www.woorden.org/woord/big"), (MUIS, "https://www.ensie.nl/betekenis/big")]),
      ("en", "big", "large", [(MW, "https://www.merriam-webster.com/dictionary/biggest"), (BR, "https://www.britannica.com/dictionary/big")]),
      [("nl", "De [big] slaapt in het stro.", "The piglet is sleeping in the straw.")],
      "The big is sleeping in the straw."),
    W("nl-boot", "trap",
      ("nl", "boot", "a boat", [(WOORDEN, "https://www.woorden.org/woord/boot"), (VD, "https://www.ensie.nl/van-dale/boot")]),
      ("en", "boot", "a strong shoe that covers the ankle", [(OX, "https://www.oxfordlearnersdictionaries.com/definition/english/boot_1"), (MW, "https://www.merriam-webster.com/dictionary/boot")]),
      [("nl", "De [boot] vaart naar het eiland.", "The boat sails to the island.")],
      "The boot sails to the island."),
    W("fr-pain", "trap",
      ("fr", "pain", "bread", [(LAR, "https://www.larousse.fr/dictionnaires/francais/pain/57279"), (ACAD, "https://www.dictionnaire-academie.fr/article/A9P0082")]),
      ("en", "pain", "the feeling when something hurts", [(MW, "https://www.merriam-webster.com/dictionary/pains"), (BR, "https://www.britannica.com/dictionary/pain")]),
      [("fr", "Je mange du [pain] avec du fromage.", "I'm eating bread with cheese.")],
      "I'm eating pain with cheese."),
    W("fr-main", "trap",
      ("fr", "main", "a hand", [(LAR, "https://www.larousse.fr/dictionnaires/francais/main/48688"), (WIKTFR, "https://fr.wiktionary.org/wiki/main")]),
      ("en", "main", "most important", [(BR, "https://www.britannica.com/dictionary/main"), (MW, "https://www.merriam-webster.com/simple/main")]),
      [("fr", "Lève la [main] pour parler.", "Raise your hand to speak.")],
      "Raise your main to speak."),
    W("fr-four", "trap",
      ("fr", "four", "an oven", [(LAR, "https://www.larousse.fr/dictionnaires/francais/four/34816"), (WIKTFR, "https://fr.wiktionary.org/wiki/four")]),
      ("en", "four", "the number 4", [(BR, "https://www.britannica.com/dictionary/four"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/four")]),
      [("fr", "Le gâteau est dans le [four].", "The cake is in the oven.")],
      "The cake is in the four."),
    W("fr-lecture", "trap",
      ("fr", "lecture", "reading", [(LAR, "https://www.larousse.fr/dictionnaires/francais/lecture/46547"), (LARC, "https://www.larousse.fr/dictionnaires/college/lecture")]),
      ("en", "lecture", "a talk that teaches a group", [(BR, "https://www.britannica.com/dictionary/lecture"), (MW, "https://www.merriam-webster.com/dictionary/lectures")]),
      [("fr", "La [lecture] est mon passe-temps préféré.", "Reading is my favourite pastime.")],
      "The lecture is my favourite pastime."),
    W("fr-chandelier", "trap",
      ("fr", "chandelier", "a candlestick", [(LAR, "https://www.larousse.fr/dictionnaires/francais/chandelier/14602"), (LARFE, "https://www.larousse.fr/dictionnaires/francais-anglais/chandelier/14472")]),
      ("en", "chandelier", "a branched light hanging from a ceiling", [(BR, "https://www.britannica.com/dictionary/chandelier"), (MW, "https://www.merriam-webster.com/dictionary/chandelier")]),
      [("fr", "Le [chandelier] est sur la table.", "The candlestick is on the table.")],
      "The chandelier is on the table."),
    W("es-red", "trap",
      ("es", "red", "a net (or a network)", [(RAE, "https://dle.rae.es/red"), (SD, "https://www.spanishdict.com/translate/la%20red")]),
      ("en", "red", "the colour of blood", [(BR, "https://www.britannica.com/dictionary/reds"), (MW, "https://www.merriam-webster.com/dictionary/red?pronunciation=&lang=en_us&dir=r&file=red00001")]),
      [("es", "El pez está en la [red].", "The fish is in the net.")],
      "The fish is in the red."),
    W("es-once", "trap",
      ("es", "once", "eleven", [(RAE, "https://dle.rae.es/once"), (SD, "https://www.spanishdict.com/translate/once")]),
      ("en", "once", "one time", [(BR, "https://www.britannica.com/dictionary/once"), (MW, "https://www.merriam-webster.com/dictionary/onces")]),
      [("es", "Tengo [once] primos.", "I have eleven cousins.")],
      "I have once cousins."),
    W("fr-es-salir", "trap",
      ("fr", "salir", "to make something dirty", [(LAR, "https://www.larousse.fr/dictionnaires/francais/salir/70697"), (WIKTFR, "https://fr.wiktionary.org/wiki/salir")]),
      ("es", "salir", "to go out", [(RAE, "https://dle.rae.es/salir"), (SD, "https://www.spanishdict.com/translate/salir")]),
      [("fr", "Attention, tu vas [salir] le tapis !", "Careful, you'll get the carpet dirty!"),
       ("es", "¿Quieres [salir] esta noche?", "Do you want to go out tonight?")],
      "Careful, you'll go out the carpet!"),
    W("it-estate", "trap",
      ("it", "estate", "summer", [(TREC, "https://www.treccani.it/vocabolario/estate/"), (DEM, "https://dizionario.internazionale.it/parola/estate")]),
      ("en", "estate", "a big piece of land with a house on it", [(MW, "https://www.merriam-webster.com/dictionary/estate#legalDictionary"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/estate")]),
      [("it", "L'[estate] è la mia stagione preferita.", "Summer is my favourite season.")],
      "The estate is my favourite season."),
    W("it-fame", "trap",
      ("it", "fame", "hunger", [(TREC, "https://www.treccani.it/vocabolario/fame/"), (DEM, "https://dizionario.internazionale.it/parola/fame")]),
      ("en", "fame", "being known by very many people", [(OX, "https://www.oxfordlearnersdictionaries.com/definition/english/fame"), (BR, "https://www.britannica.com/dictionary/fame")]),
      [("it", "Ho [fame], mangiamo!", "I'm hungry, let's eat!")],
      "I have fame, let's eat!"),
    W("it-cane", "trap",
      ("it", "cane", "a dog", [(TREC, "https://www.treccani.it/vocabolario/cane1/"), (DEM, "https://dizionario.internazionale.it/parola/cane")]),
      ("en", "cane", "a walking stick", [(OX, "https://www.oxfordlearnersdictionaries.com/us/definition/american_english/cane_1"), (BR, "https://www.britannica.com/dictionary/cane")]),
      [("it", "Il [cane] abbaia al postino.", "The dog barks at the postman.")],
      "The cane barks at the postman."),
    W("it-ape", "trap",
      ("it", "ape", "a bee", [(TREC, "https://www.treccani.it/vocabolario/ape/"), (DEM, "https://dizionario.internazionale.it/parola/ape")]),
      ("en", "ape", "an animal like a gorilla or a chimpanzee", [(BR, "https://www.britannica.com/dictionary/ape"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/american_english/ape_1")]),
      [("it", "Un'[ape] vola sul fiore.", "A bee flies onto the flower.")],
      "An ape flies onto the flower."),
    W("pt-data", "trap",
      ("pt", "data", "a date: the day, month and year", [(PRI, "https://dicionario.priberam.org/pt-pt/data"), (INF, "https://www.infopedia.pt/dicionarios/lingua-portuguesa/data")]),
      ("en", "data", "facts and information", [(OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/data"), (BR, "https://www.britannica.com/dictionary/data")]),
      [("pt", "Qual é a [data] de hoje?", "What is today's date?")],
      "What is today's data?"),
    W("es-it-camino", "trap",
      ("es", "camino", "a path or a way", [(RAE, "https://dle.rae.es/camino"), (SD, "https://www.spanishdict.com/translate/camino")]),
      ("it", "camino", "a fireplace (or a chimney)", [(TREC, "https://www.treccani.it/vocabolario/camino1/"), (DEM, "https://dizionario.internazionale.it/parola/camino")]),
      [("es", "El [camino] sube a la montaña.", "The path goes up the mountain."),
       ("it", "Accendiamo il [camino]?", "Shall we light the fireplace?")],
      "Shall we light the path?"),
    W("es-it-topo", "trap",
      ("es", "topo", "a mole, the animal that digs", [(RAE, "https://dle.rae.es/topo"), (SD, "https://www.spanishdict.com/translate/topo")]),
      ("it", "topo", "a mouse", [(TREC, "https://www.treccani.it/vocabolario/topo1/"), (DEM, "https://dizionario.internazionale.it/parola/topo")]),
      [("es", "El [topo] vive bajo tierra.", "The mole lives underground."),
       ("it", "Il [topo] mangia il formaggio.", "The mouse is eating the cheese.")],
      "The mole is eating the cheese."),
    W("es-it-seta", "trap",
      ("es", "seta", "a mushroom", [(RAE, "https://dle.rae.es/seta"), (SD, "https://www.spanishdict.com/translate/seta")]),
      ("it", "seta", "silk", [(TREC, "https://www.treccani.it/vocabolario/seta/"), (DEM, "https://dizionario.internazionale.it/parola/seta")]),
      [("es", "Encontré una [seta] en el bosque.", "I found a mushroom in the forest."),
       ("it", "La camicia è di [seta].", "The shirt is made of silk.")],
      "The shirt is made of mushroom."),
    W("es-it-burro", "trap",
      ("es", "burro", "a donkey", [(RAE, "https://dle.rae.es/burro"), (SD, "https://www.spanishdict.com/translate/burro")]),
      ("it", "burro", "butter", [(TREC, "https://www.treccani.it/vocabolario/burro/"), (DEM, "https://dizionario.internazionale.it/parola/burro")]),
      [("es", "El [burro] come hierba.", "The donkey is eating grass."),
       ("it", "Pane e [burro], per favore.", "Bread and butter, please.")],
      "Bread and donkey, please."),
    W("sv-barn", "trap",
      ("sv", "barn", "a child, or children", [(SYN, "https://www.synonymer.se/sv-en/barn"), (WOX, "https://ordbok.woxikon.se/sv-en/barn")]),
      ("en", "barn", "a big farm building for animals or crops", [(OX, "https://www.oxfordlearnersdictionaries.com/definition/english/barn"), (MW, "https://www.merriam-webster.com/dictionary/barns")]),
      [("sv", "Alla [barn] får en present.", "All the children get a present.")],
      "All the barns get a present."),
    W("sv-glass", "trap",
      ("sv", "glass", "ice cream", [(SYN, "https://www.synonymer.se/sv-en/glass"), (WOX, "https://ordbok.woxikon.se/sv-en/glass")]),
      ("en", "glass", "the hard, clear material of windows", [(MW, "https://www.merriam-webster.com/dictionary/glass"), (BR, "https://www.britannica.com/dictionary/glass")]),
      [("sv", "Vi äter [glass] på stranden.", "We're eating ice cream on the beach.")],
      "We're eating glass on the beach."),
    W("sv-semester", "trap",
      ("sv", "semester", "a holiday from work", [(SYN, "https://www.synonymer.se/sv-en/semester"), (WOX, "https://ordbok.woxikon.se/sv-en/semester")]),
      ("en", "semester", "half of a school or university year", [(BR, "https://www.britannica.com/dictionary/semester"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/semester")]),
      [("sv", "Vi åker till Spanien på [semester].", "We're going to Spain on holiday.")],
      "We're going to Spain for a semester."),
    W("sv-dam", "trap",
      ("sv", "dam", "a lady", [(SYN, "https://www.synonymer.se/sv-en/dam"), (WOX, "https://ordbok.woxikon.se/sv-en/dam")]),
      ("en", "dam", "a wall that holds back water", [(MW, "https://www.merriam-webster.com/dictionary/dam"), (BR, "https://www.britannica.com/dictionary/dam")]),
      [("sv", "En äldre [dam] sitter på bänken.", "An older lady is sitting on the bench.")],
      "An older dam is sitting on the bench."),
    W("sv-hem", "trap",
      ("sv", "hem", "home", [(SYN, "https://www.synonymer.se/sv-en/hem"), (WOX, "https://ordbok.woxikon.se/sv-en/hem")]),
      ("en", "hem", "the folded edge of a piece of cloth", [(MW, "https://www.merriam-webster.com/dictionary/hem"), (BR, "https://www.britannica.com/dictionary/hem")]),
      [("sv", "Välkommen [hem]!", "Welcome home!")],
      "Welcome, hem!"),
    W("ru-fabrika", "trap",
      ("ru", "фабрика", "a factory", [(USH, "https://dic.academic.ru/dic.nsf/ushakov/1074418"), (GRAM, "https://gramota.ru/meta/fabrika")], "fabrika"),
      ("en", "fabric", "cloth", [(MW, "https://www.merriam-webster.com/dictionary/fabrics"), (BR, "https://www.britannica.com/dictionary/fabric")]),
      [("ru", "Это старая [фабрика].", "This is an old factory.", "Eto staraya [fabrika].")],
      "This is an old fabric."),
    W("tr-bin", "trap",
      ("tr", "bin", "a thousand", [(TUR, "https://tureng.com/en/turkish-english/bin"), (ZAR, "https://www.zargan.com/tr/q/bin-ceviri-nedir")]),
      ("en", "bin", "a container for rubbish", [(MW, "https://www.merriam-webster.com/dictionary/bin"), (BR, "https://www.britannica.com/dictionary/bin")]),
      [("tr", "[Bin] kere teşekkür ederim!", "Thank you a thousand times!")],
      "Thank you a bin times!"),
    W("tr-ten", "trap",
      ("tr", "ten", "skin, its colour and look", [(TUR, "https://tureng.com/en/turkish-english/ten"), (ZAR, "https://www.zargan.com/tr/q/ten-ceviri-nedir")]),
      ("en", "ten", "the number 10", [(BR, "https://www.britannica.com/dictionary/ten"), (MW, "https://www.merriam-webster.com/dictionary/10")]),
      [("tr", "Bu krem her [ten] için uygun.", "This cream suits every skin.")],
      "This cream suits every ten."),
    W("tr-pasta", "trap",
      ("tr", "pasta", "a cake", [(TUR, "https://tureng.com/en/turkish-english/pasta"), (ZAR, "https://www.zargan.com/tr/q/pasta-ceviri-nedir")]),
      ("en", "pasta", "Italian food made of dough, like spaghetti", [(MW, "https://www.merriam-webster.com/dictionary/pastas"), (BR, "https://www.britannica.com/dictionary/pasta")]),
      [("tr", "[Pasta]ya mumları koyduk.", "We put the candles on the cake.")],
      "We put the candles on the pasta."),
    W("tr-at", "trap",
      ("tr", "at", "a horse", [(TUR, "https://tureng.com/en/turkish-english/at"), (ZAR, "https://www.zargan.com/tr/q/at-ceviri-nedir")]),
      ("en", "at", "a little word for where or when: at home, at six", [(BR, "https://www.britannica.com/dictionary/at"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/at")]),
      [("tr", "Çiftlikte beyaz bir [at] var.", "There is a white horse on the farm.")],
      "There is a white at on the farm."),
    W("tr-son", "trap",
      ("tr", "son", "the end; last", [(TUR, "https://tureng.com/en/turkish-english/son"), (ZAR, "https://www.zargan.com/tr/q/son-ceviri-nedir")]),
      ("en", "son", "a male child", [(OX, "https://www.oxfordlearnersdictionaries.com/definition/english/son"), (MW, "https://www.merriam-webster.com/dictionary/sons")]),
      [("tr", "Bu [son] şansın!", "This is your last chance!")],
      "This is your son chance!"),

    # ---------------- twins (true friends) ----------------
    W("de-rucksack", "twin",
      ("de", "Rucksack", "a bag you carry on your back", [(DWDS, "https://www.dwds.de/wb/Rucksack"), (WAHRIG, "https://www.dwds.de/wb/wdw/search/?q=Rucksack")]),
      ("en", "rucksack", "a bag you carry on your back", [(OX, "https://www.oxfordlearnersdictionaries.com/definition/english/rucksack"), (BR, "https://www.britannica.com/dictionary/rucksack")]),
      [("de", "Mein [Rucksack] ist zu schwer.", "My rucksack is too heavy.")]),
    W("de-hamster", "twin",
      ("de", "Hamster", "a small furry animal with big cheek pouches", [(DWDS, "https://www.dwds.de/wb/Hamster"), (WAHRIG, "https://www.dwds.de/wb/wdw/Hamster")]),
      ("en", "hamster", "a small furry animal with big cheek pouches", [(MW, "https://www.merriam-webster.com/dictionary/hamster"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/hamster")]),
      [("de", "Der [Hamster] schläft am Tag.", "The hamster sleeps during the day.")]),
    W("de-kitsch", "twin",
      ("de", "Kitsch", "showy things in poor taste", [(DWDS, "https://www.dwds.de/wb/Kitsch"), (WAHRIG, "https://www.dwds.de/wb/wdw/search/?q=Kitsch")]),
      ("en", "kitsch", "showy things in poor taste", [(OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/kitsch_1"), (BR, "https://www.britannica.com/dictionary/kitsch")]),
      [("de", "Der Laden ist voller [Kitsch].", "The shop is full of kitsch.")]),
    W("de-film", "twin",
      ("de", "Film", "a movie (and the film of old cameras)", [(DWDS, "https://www.dwds.de/wb/Film"), (WAHRIG, "https://www.dwds.de/wb/wdw/search/?q=Film")]),
      ("en", "film", "a movie (and the film of old cameras)", [(MW, "https://www.merriam-webster.com/dictionary/film#medicalDictionary"), (BR, "https://www.britannica.com/dictionary/film")]),
      [("de", "Der [Film] beginnt um acht.", "The film starts at eight.")]),
    W("de-kohlrabi", "twin",
      ("de", "Kohlrabi", "a cabbage-like vegetable with a round, fat stem", [(DWDS, "https://www.dwds.de/wb/Kohlrabi"), (WAHRIG, "https://www.dwds.de/wb/wdw/Kohlrabi")]),
      ("en", "kohlrabi", "a cabbage-like vegetable with a round, fat stem", [(MW, "https://www.merriam-webster.com/dictionary/kohlrabi"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/kohlrabi")]),
      [("de", "Oma kocht heute [Kohlrabi].", "Grandma is cooking kohlrabi today.")]),
    W("de-nl-wand", "twin",
      ("de", "Wand", "a wall", [(DWDS, "https://www.dwds.de/wb/Wand"), (WAHRIG, "https://www.dwds.de/wb/wdw/search/?q=Wand")]),
      ("nl", "wand", "a wall", [(WOORDEN, "https://www.woorden.org/woord/wand"), (VD, "https://www.ensie.nl/van-dale/wand")]),
      [("de", "Das Bild hängt an der [Wand].", "The picture hangs on the wall."),
       ("nl", "Het schilderij hangt aan de [wand].", "The painting hangs on the wall.")]),
    W("de-nl-kind", "twin",
      ("de", "Kind", "a child", [(DWDS, "https://www.dwds.de/wb/Kind"), (WDG, "https://www.dwds.de/wb/wdg/Kind")]),
      ("nl", "kind", "a child", [(WOORDEN, "https://www.woorden.org/woord/kind"), (MUIS, "https://www.ensie.nl/betekenis/kind")]),
      [("de", "Das [Kind] lacht.", "The child is laughing."),
       ("nl", "Het [kind] speelt buiten.", "The child is playing outside.")]),
    W("nl-water", "twin",
      ("nl", "water", "the clear liquid of rain, rivers and seas", [(WOORDEN, "https://www.woorden.org/woord/water"), (MUIS, "https://www.ensie.nl/betekenis/water")]),
      ("en", "water", "the clear liquid of rain, rivers and seas", [(BR, "https://www.britannica.com/dictionary/water"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/water_1")]),
      [("nl", "Het [water] is vandaag koud.", "The water is cold today.")]),
    W("nl-tram", "twin",
      ("nl", "tram", "an electric vehicle on rails in the street", [(WOORDEN, "https://www.woorden.org/woord/tram"), (MUIS, "https://www.ensie.nl/betekenis/tram")]),
      ("en", "tram", "an electric vehicle on rails in the street", [(OX, "https://www.oxfordlearnersdictionaries.com/definition/english/tram"), (BR, "https://www.britannica.com/dictionary/tram")]),
      [("nl", "De [tram] stopt bij het station.", "The tram stops at the station.")]),
    W("nl-storm", "twin",
      ("nl", "storm", "very bad weather with strong wind", [(WOORDEN, "https://www.woorden.org/woord/storm"), (VD, "https://www.ensie.nl/van-dale/storm")]),
      ("en", "storm", "very bad weather with strong wind", [(BR, "https://www.britannica.com/dictionary/storm"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/storm_1")]),
      [("nl", "Er komt vannacht een [storm].", "A storm is coming tonight.")]),
    W("fr-orange", "twin",
      ("fr", "orange", "the fruit, and its colour", [(LAR, "https://www.larousse.fr/dictionnaires/francais/orange/56295"), (WIKTFR, "https://fr.wiktionary.org/wiki/orange")]),
      ("en", "orange", "the fruit, and its colour", [(BR, "https://www.britannica.com/dictionary/orange"), (MW, "https://www.merriam-webster.com/dictionary/Orange")]),
      [("fr", "Je bois un jus d'[orange].", "I'm drinking orange juice.")]),
    W("fr-ballet", "twin",
      ("fr", "ballet", "dancing performed on a stage", [(LAR, "https://www.larousse.fr/dictionnaires/francais/ballet/7696"), (WIKTFR, "https://fr.wiktionary.org/wiki/ballet")]),
      ("en", "ballet", "dancing performed on a stage", [(BR, "https://www.britannica.com/dictionary/ballet"), (MW, "https://www.merriam-webster.com/dictionary/ballet")]),
      [("fr", "Ce soir, nous allons voir un [ballet].", "Tonight we're going to see a ballet.")]),
    W("fr-garage", "twin",
      ("fr", "garage", "a building for cars, or a shop that repairs them", [(LAR, "https://www.larousse.fr/dictionnaires/francais/garage/36068"), (LARC, "https://www.larousse.fr/dictionnaires/college/garage/17721")]),
      ("en", "garage", "a building for cars, or a shop that repairs them", [(BR, "https://www.britannica.com/dictionary/garage"), (MW, "https://www.merriam-webster.com/dictionary/garaging")]),
      [("fr", "La voiture est au [garage].", "The car is at the garage.")]),
    W("fr-avalanche", "twin",
      ("fr", "avalanche", "a mass of snow rushing down a mountain", [(LAR, "https://www.larousse.fr/dictionnaires/francais/avalanche/6925"), (WIKTFR, "https://fr.wiktionary.org/wiki/avalanche")]),
      ("en", "avalanche", "a mass of snow rushing down a mountain", [(MW, "https://www.merriam-webster.com/dictionary/avalanche"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/avalanche")]),
      [("fr", "Une [avalanche] a fermé la route.", "An avalanche closed the road.")]),
    W("fr-parachute", "twin",
      ("fr", "parachute", "a big cloth that slows a fall from a plane", [(LAR, "https://www.larousse.fr/dictionnaires/francais/parachute/57848"), (WIKTFR, "https://fr.wiktionary.org/wiki/parachute")]),
      ("en", "parachute", "a big cloth that slows a fall from a plane", [(BR, "https://www.britannica.com/dictionary/parachute"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/parachute_1")]),
      [("fr", "Il saute en [parachute].", "He jumps with a parachute.")]),
    W("es-hospital", "twin",
      ("es", "hospital", "a place where sick people are cared for", [(RAE, "https://dle.rae.es/hospital"), (SD, "https://www.spanishdict.com/translate/hospital")]),
      ("en", "hospital", "a place where sick people are cared for", [(MW, "https://www.merriam-webster.com/dictionary/hospitals"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/hospital")]),
      [("es", "Mi tía trabaja en un [hospital].", "My aunt works in a hospital.")]),
    W("es-animal", "twin",
      ("es", "animal", "a living creature that is not a plant", [(RAE, "https://dle.rae.es/animal"), (SD, "https://www.spanishdict.com/translate/animal")]),
      ("en", "animal", "a living creature that is not a plant", [(MW, "https://www.merriam-webster.com/dictionary/animal"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/animal_1")]),
      [("es", "El perro es mi [animal] favorito.", "The dog is my favourite animal.")]),
    W("es-error", "twin",
      ("es", "error", "a mistake", [(RAE, "https://dle.rae.es/error"), (SD, "https://www.spanishdict.com/translate/error")]),
      ("en", "error", "a mistake", [(MW, "https://www.merriam-webster.com/dictionary/error"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/error")]),
      [("es", "Fue un pequeño [error].", "It was a small mistake.")]),
    W("es-piano", "twin",
      ("es", "piano", "the instrument with black and white keys", [(RAE, "https://dle.rae.es/piano"), (SD, "https://www.spanishdict.com/translate/piano")]),
      ("en", "piano", "the instrument with black and white keys", [(MW, "https://www.merriam-webster.com/dictionary/pianos"), (BR, "https://www.britannica.com/dictionary/piano")]),
      [("es", "Mi hermana toca el [piano].", "My sister plays the piano.")]),
    W("it-villa", "twin",
      ("it", "villa", "a large house with a garden", [(TREC, "https://www.treccani.it/vocabolario/villa/"), (DEM, "https://dizionario.internazionale.it/parola/villa")]),
      ("en", "villa", "a large house with a garden", [(MW, "https://www.merriam-webster.com/dictionary/villa"), (OX, "https://www.oxfordlearnersdictionaries.com/definition/english/villa")]),
      [("it", "La [villa] ha un grande giardino.", "The villa has a big garden.")]),
    W("it-paparazzi", "twin",
      ("it", "paparazzi", "photographers who chase famous people", [(TREC, "https://www.treccani.it/vocabolario/paparazzo/"), (DEM, "https://dizionario.internazionale.it/parola/paparazzo")]),
      ("en", "paparazzi", "photographers who chase famous people", [(MW, "https://www.merriam-webster.com/dictionary/paparazzi"), (BR, "https://www.britannica.com/dictionary/paparazzo")]),
      [("it", "I [paparazzi] aspettano l'attrice.", "The paparazzi are waiting for the actress.")]),
    W("pt-hotel", "twin",
      ("pt", "hotel", "a building where you pay to stay the night", [(PRI, "https://dicionario.priberam.org/hotel"), (INF, "https://www.infopedia.pt/dicionarios/lingua-portuguesa/hotel")]),
      ("en", "hotel", "a building where you pay to stay the night", [(MW, "https://www.merriam-webster.com/dictionary/hotel"), (OX, "https://www.oxfordlearnersdictionaries.com/us/definition/english/hotel")]),
      [("pt", "O [hotel] fica perto da praia.", "The hotel is near the beach.")]),
    W("es-it-cena", "twin",
      ("es", "cena", "dinner, the evening meal", [(RAE, "https://dle.rae.es/cena"), (SD, "https://www.spanishdict.com/translate/cena")]),
      ("it", "cena", "dinner, the evening meal", [(TREC, "https://www.treccani.it/vocabolario/cena/"), (DEM, "https://dizionario.internazionale.it/parola/cena")]),
      [("es", "La [cena] está lista.", "Dinner is ready."),
       ("it", "La [cena] è pronta.", "Dinner is ready.")]),
    W("es-it-casa", "twin",
      ("es", "casa", "a house, or home", [(RAE, "https://dle.rae.es/casa"), (SD, "https://www.spanishdict.com/translate/casa?langFrom=es")]),
      ("it", "casa", "a house, or home", [(TREC, "https://www.treccani.it/vocabolario/casa/"), (DEM, "https://dizionario.internazionale.it/parola/casa")]),
      [("es", "Mi [casa] es pequeña.", "My house is small."),
       ("it", "La mia [casa] è piccola.", "My house is small.")]),
    W("es-it-museo", "twin",
      ("es", "museo", "a building where art or old things are shown", [(RAE, "https://dle.rae.es/museo"), (SD, "https://www.spanishdict.com/translate/museo")]),
      ("it", "museo", "a building where art or old things are shown", [(TREC, "https://www.treccani.it/vocabolario/museo/"), (DEM, "https://dizionario.internazionale.it/parola/museo")]),
      [("es", "El [museo] abre a las diez.", "The museum opens at ten."),
       ("it", "Il [museo] apre alle dieci.", "The museum opens at ten.")]),
    W("es-pt-mesa", "twin",
      ("es", "mesa", "a table", [(RAE, "https://dle.rae.es/mesa"), (SD, "https://www.spanishdict.com/translate/mesa")]),
      ("pt", "mesa", "a table", [(PRI, "https://dicionario.priberam.org/pt-pt/mesa"), (INF, "https://www.infopedia.pt/dicionarios/lingua-portuguesa/mesa")]),
      [("es", "La [mesa] es de madera.", "The table is made of wood."),
       ("pt", "A [mesa] é de madeira.", "The table is made of wood.")]),
    W("es-pt-luz", "twin",
      ("es", "luz", "light (and electric power at home)", [(RAE, "https://dle.rae.es/luz"), (SD, "https://www.spanishdict.com/translate/luz")]),
      ("pt", "luz", "light (and electric power at home)", [(PRI, "https://dicionario.priberam.org/pt-pt/luz"), (INF, "https://www.infopedia.pt/dicionarios/lingua-portuguesa/luz")]),
      [("es", "Apaga la [luz], por favor.", "Turn off the light, please."),
       ("pt", "Apaga a [luz], por favor.", "Turn off the light, please.")]),
    W("sv-moped", "twin",
      ("sv", "moped", "a small motorbike", [(SYN, "https://www.synonymer.se/sv-en/moped"), (WOX, "https://ordbok.woxikon.se/sv-en/moped")]),
      ("en", "moped", "a small motorbike", [(MW, "https://www.merriam-webster.com/dictionary/moped"), (BR, "https://www.britannica.com/dictionary/mopeds")]),
      [("sv", "Han kör [moped] till skolan.", "He rides a moped to school.")]),
    W("sv-tunnel", "twin",
      ("sv", "tunnel", "a passage under the ground or through a hill", [(SYN, "https://www.synonymer.se/sv-en/tunnel"), (WOX, "https://ordbok.woxikon.se/sv-en/tunnel")]),
      ("en", "tunnel", "a passage under the ground or through a hill", [(MW, "https://www.merriam-webster.com/dictionary/tunnels"), (BR, "https://www.britannica.com/dictionary/tunnel")]),
      [("sv", "Tåget åker genom en lång [tunnel].", "The train goes through a long tunnel.")]),
    W("tr-golf", "twin",
      ("tr", "golf", "the game of hitting a small ball into holes", [(TUR, "https://tureng.com/en/turkish-english/golf"), (ZAR, "https://www.zargan.com/tr/q/golf-ceviri-nedir")]),
      ("en", "golf", "the game of hitting a small ball into holes", [(MW, "https://www.merriam-webster.com/dictionary/golf"), (BR, "https://www.britannica.com/dictionary/golf")]),
      [("tr", "Babam her pazar [golf] oynar.", "My dad plays golf every Sunday.")]),
]
