"""Years Apart: every event, with its date and its two sources.

Written from the reading of 5 October 2026 (night): every date was opened and read on two websites;
what each page said is in evidence.txt next to this file, in quotes.

Fields: label (on screen), stamp (album, at most 22 characters), topic (the colour of the stamp),
date (year, month, day; a negative year is BC: -30 is 30 BC; no year 0), prec (how exact the game takes it:
'day', 'month', 'year' or 'about'), sources (two, each a name and the address that was opened).
To add an event: read two sources, put the quotes into evidence.txt, add the event here.
"""

EVENTS = {
 'pyramid': dict(label='The Great Pyramid of Giza is finished', stamp='Great Pyramid', topic='place', date=(-2560, None, None), prec='about',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Giza_pyramid_complex'), ('History.com', 'https://www.history.com/articles/how-long-did-it-take-to-build-the-great-pyramid')]),
 'olympia': dict(label='The first recorded Olympic Games', stamp='First Olympics', topic='culture', date=(-776, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Ancient_Olympic_Games'), ('History.com', 'https://www.history.com/articles/olympic-games')]),
 'marathon': dict(label='The Battle of Marathon', stamp='Marathon', topic='empire', date=(-490, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Battle_of_Marathon'), ('National Geographic', 'https://www.nationalgeographic.com/history/history-magazine/article/battle-marathon-persia')]),
 'alexander': dict(label='Alexander the Great dies', stamp='Alexander dies', topic='empire', date=(-323, 6, None), prec='month',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Death_of_Alexander_the_Great'), ('National Geographic', 'https://www.nationalgeographic.com/history/article/how-did-alexander-the-great-die-river-styx')]),
 'qin': dict(label="Qin Shi Huang becomes China's first emperor", stamp="China's first emperor", topic='empire', date=(-221, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Qin_Shi_Huang'), ('National Geographic', 'https://www.nationalgeographic.com/culture/article/qin-shi-huangdi')]),
 'caesar': dict(label='Julius Caesar is assassinated', stamp="Caesar's last day", topic='empire', date=(-44, 3, 15), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Assassination_of_Julius_Caesar'), ('History.com', 'https://www.history.com/this-day-in-history/march-15/the-ides-of-march')]),
 'cleopatra': dict(label='Cleopatra dies', stamp='Cleopatra dies', topic='empire', date=(-30, 8, None), prec='month',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Death_of_Cleopatra'), ('History.com', 'https://www.history.com/this-day-in-history/august-10/cleopatra-commits-suicide')]),
 'pompeii': dict(label='Vesuvius buries Pompeii', stamp='Pompeii buried', topic='place', date=(79, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Eruption_of_Mount_Vesuvius_in_79_AD'), ('History.com', 'https://www.history.com/articles/pompeii')]),
 'colosseum': dict(label='The Colosseum opens', stamp='Colosseum opens', topic='place', date=(80, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Colosseum'), ('History.com', 'https://www.history.com/articles/colosseum')]),
 'rome-falls': dict(label="Rome's last western emperor is deposed", stamp="Rome's last emperor", topic='empire', date=(476, 9, 4), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Romulus_Augustulus'), ('History.com', 'https://www.history.com/this-day-in-history/september-4/western-roman-empire-falls')]),
 'hagia': dict(label='The Hagia Sophia is finished', stamp='Hagia Sophia', topic='place', date=(537, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Hagia_Sophia'), ('History.com', 'https://www.history.com/articles/hagia-sophia')]),
 'charlemagne': dict(label='Charlemagne is crowned emperor', stamp='Charlemagne crowned', topic='empire', date=(800, 12, 25), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Pope_Leo_III'), ('History.com', 'https://www.history.com/articles/charlemagne')]),
 'hastings': dict(label='The Battle of Hastings', stamp='Hastings', topic='empire', date=(1066, 10, 14), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Battle_of_Hastings'), ('English Heritage', 'https://www.english-heritage.org.uk/learn/histories/1066-and-the-norman-conquest/')]),
 'genghis': dict(label='Temüjin becomes Genghis Khan', stamp='Genghis Khan', topic='empire', date=(1206, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Genghis_Khan'), ('History.com', 'https://history.com/.amp/news/10-things-you-may-not-know-about-genghis-khan')]),
 'magna': dict(label='Magna Carta is sealed', stamp='Magna Carta', topic='empire', date=(1215, 6, 15), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Magna_Carta'), ('History.com', 'https://www.history.com/this-day-in-history/june-15/magna-carta-sealed')]),
 'black-death': dict(label='The Black Death reaches Sicily', stamp='The Black Death', topic='science', date=(1347, 10, None), prec='month',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Black_Death_in_Italy'), ('History.com', 'https://www.history.com/articles/black-death')]),
 'constantinople': dict(label='Constantinople falls to the Ottomans', stamp='Constantinople falls', topic='empire', date=(1453, 5, 29), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Constantinople'), ('History.com', 'https://www.history.com/articles/constantinople')]),
 'columbus': dict(label='Columbus reaches the Americas', stamp='Columbus lands', topic='journey', date=(1492, 10, 12), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Christopher_Columbus'), ('History.com', 'https://www.history.com/articles/christopher-columbus')]),
 'gama': dict(label='Vasco da Gama reaches India by sea', stamp='Da Gama in India', topic='journey', date=(1498, 5, 20), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Vasco_da_Gama'), ('History.com', 'https://www.history.com/this-day-in-history/may-20/vasco-da-gama-reaches-india')]),
 'cortes': dict(label='Cortés enters the Aztec capital', stamp='Cortés in Tenochtitlan', topic='journey', date=(1519, 11, 8), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Hern%C3%A1n_Cort%C3%A9s'), ('History.com', 'https://www.history.com/articles/hernan-cortes')]),
 'magellan': dict(label='The first voyage around the world ends', stamp='Round the world', topic='journey', date=(1522, 9, 6), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Magellan_expedition'), ('History.com', 'https://www.history.com/this-day-in-history/september-6/magellans-expedition-circumnavigates-globe')]),
 'copernicus': dict(label='Copernicus publishes his model of the universe', stamp="Copernicus's book", topic='science', date=(1543, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/De_revolutionibus_orbium_coelestium'), ('History.com', 'https://www.history.com/articles/nicolaus-copernicus')]),
 'east-india': dict(label='The East India Company gets its charter', stamp='East India Company', topic='empire', date=(1600, 12, 31), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/1600'), ('History.com', 'https://www.history.com/this-day-in-history/december-31/charter-granted-to-the-east-india-company')]),
 'tokugawa': dict(label='Tokugawa Ieyasu becomes shogun', stamp='Tokugawa shogun', topic='empire', date=(1603, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Tokugawa_Ieyasu'), ('History.com', 'https://www.history.com/topics/asian-history/meiji-restoration')]),
 'galileo': dict(label='Galileo turns his telescope to the Moon', stamp="Galileo's Moon", topic='science', date=(1609, 11, 30), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Galileo_Galilei'), ('History.com', 'https://www.history.com/this-day-in-history/november-30/galileo-begins-observing-the-moon')]),
 'shakespeare': dict(label='Shakespeare dies', stamp='Shakespeare dies', topic='culture', date=(1616, 4, 23), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/William_Shakespeare'), ('Shakespeare Birthplace Trust', 'https://www.shakespeare.org.uk/explore-shakespeare/shakespedia/william-shakespeare/when-did-shakespeare-die/')]),
 'fire-london': dict(label='The Great Fire of London', stamp='Great Fire of London', topic='place', date=(1666, 9, 2), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Great_Fire_of_London'), ('Royal Museums Greenwich', 'https://www.rmg.co.uk/stories/royal-history/great-fire-london')]),
 'principia': dict(label="Newton's Principia is published", stamp="Newton's Principia", topic='science', date=(1687, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Philosophi%C3%A6_Naturalis_Principia_Mathematica'), ('Library of Congress', 'https://www.loc.gov/item/2021667054/')]),
 'declaration': dict(label='The US Declaration of Independence', stamp='Independence declared', topic='empire', date=(1776, 7, 4), prec='day',
      sources=[('US National Archives', 'https://www.archives.gov/milestone-documents/declaration-of-independence'), ('Wikipedia', 'https://en.wikipedia.org/wiki/Signing_of_the_United_States_Declaration_of_Independence')]),
 'first-fleet': dict(label='The First Fleet arrives at Sydney Cove', stamp='The First Fleet', topic='journey', date=(1788, 1, 26), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/First_Fleet'), ('National Museum of Australia', 'https://digital-classroom.nma.gov.au/defining-moments/first-fleet-arrives-sydney-cove')]),
 'bastille': dict(label='The storming of the Bastille', stamp='The Bastille', topic='empire', date=(1789, 7, 14), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Bastille'), ('History.com', 'https://www.history.com/this-day-in-history/july-14/french-revolutionaries-storm-bastille')]),
 'rosetta': dict(label='The Rosetta Stone is found', stamp='Rosetta Stone', topic='culture', date=(1799, 7, None), prec='month',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Rosetta_Stone'), ('British Museum', 'https://www.britishmuseum.org/blog/everything-you-ever-wanted-know-about-rosetta-stone')]),
 'waterloo': dict(label='The Battle of Waterloo', stamp='Waterloo', topic='empire', date=(1815, 6, 18), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Battle_of_Waterloo'), ('National Army Museum', 'https://www.nam.ac.uk/explore/battle-waterloo')]),
 'railway': dict(label='The first public passenger railway opens', stamp='First railway', topic='invention', date=(1825, 9, 27), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Locomotion_No._1'), ('National Railway Museum', 'https://blog.railwaymuseum.org.uk/85/')]),
 'penny-black': dict(label="The world's first adhesive stamp goes on sale", stamp='The Penny Black', topic='invention', date=(1840, 5, 1), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Penny_Black'), ('Smithsonian Magazine', 'https://www.smithsonianmag.com/arts-culture/the-story-of-the-first-postage-stamp-14931961/')]),
 'darwin': dict(label='Darwin publishes On the Origin of Species', stamp='Origin of Species', topic='science', date=(1859, 11, 24), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/On_the_Origin_of_Species'), ('Darwin Correspondence Project', 'https://www.darwinproject.ac.uk/learning-resources/timeline')]),
 'meiji': dict(label="Japan's emperor is restored to power", stamp='Meiji Restoration', topic='empire', date=(1868, 1, 3), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Meiji_Restoration'), ('History.com', 'https://www.history.com/this-day-in-history/january-3/meiji-restoration-in-japan')]),
 'suez': dict(label='The Suez Canal opens', stamp='Suez Canal', topic='invention', date=(1869, 11, 17), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Suez_Canal'), ('History.com', 'https://www.history.com/this-day-in-history/november-17/suez-canal-opens')]),
 'telephone': dict(label='Bell is granted the telephone patent', stamp='The telephone', topic='invention', date=(1876, 3, 7), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Alexander_Graham_Bell'), ('Library of Congress', 'https://guides.loc.gov/chronicling-america-telephone-invention')]),
 'eiffel': dict(label='The Eiffel Tower is completed', stamp='Eiffel Tower', topic='place', date=(1889, 3, 31), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Eiffel_Tower'), ('La tour Eiffel', 'https://www.toureiffel.paris/en/news/130-years/1889-2019-130-years-amazement')]),
 'nintendo': dict(label='Nintendo is founded to make playing cards', stamp='Nintendo begins', topic='invention', date=(1889, None, None), prec='year',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Nintendo'), ('Nintendo', 'https://www.nintendo.co.jp/corporate/en/history/index.html')]),
 'olympics-1896': dict(label='The first modern Olympics open in Athens', stamp='Athens 1896', topic='culture', date=(1896, 4, 6), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/1896_Summer_Olympics'), ('History.com', 'https://www.history.com/this-day-in-history/april-6')]),
 'wright': dict(label="The Wright brothers' first powered flight", stamp='First flight', topic='invention', date=(1903, 12, 17), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Wright_brothers'), ('Smithsonian Air and Space', 'https://airandspace.si.edu/stories/editorial/wright-brothers-made-history-kitty-hawk')]),
 'titanic': dict(label='The Titanic sinks', stamp='Titanic sinks', topic='journey', date=(1912, 4, 15), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Titanic'), ('Royal Museums Greenwich', 'https://www.rmg.co.uk/stories/maritime-history/rms-titanic-facts')]),
 'panama': dict(label='The Panama Canal opens', stamp='Panama Canal', topic='invention', date=(1914, 8, 15), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Panama_Canal'), ('History.com', 'https://www.history.com/this-day-in-history/august-15/panama-canal-open-to-traffic')]),
 'tutankhamun': dict(label="The steps to Tutankhamun's tomb are found", stamp="Tutankhamun's tomb", topic='culture', date=(1922, 11, 4), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Discovery_of_the_tomb_of_Tutankhamun'), ('History.com', 'https://www.history.com/this-day-in-history/november-4/entrance-to-king-tuts-tomb-discovered')]),
 'penicillin': dict(label='Fleming discovers penicillin', stamp='Penicillin', topic='science', date=(1928, 9, 3), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Discovery_of_penicillin'), ('History.com', 'https://www.history.com/this-day-in-history/september-3/penicillin-discovered')]),
 'world-cup': dict(label='The first football World Cup kicks off', stamp='First World Cup', topic='culture', date=(1930, 7, 13), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/1930_FIFA_World_Cup'), ('History.com', 'https://www.history.com/this-day-in-history/july-13/first-world-cup')]),
 'ww2-end': dict(label='The Second World War ends', stamp="War's end, 1945", topic='empire', date=(1945, 9, 2), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/VJ-Day'), ('US National Archives', 'https://www.archives.gov/milestone-documents/surrender-of-japan')]),
 'india': dict(label='India becomes independent', stamp='Indian independence', topic='empire', date=(1947, 8, 15), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Independence_Day_(India)'), ('Know India (Government of India)', 'https://knowindia.india.gov.in/independence-day-celebration/index.php')]),
 'dna': dict(label='The double helix of DNA is published', stamp='The double helix', topic='science', date=(1953, 4, 25), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Molecular_Structure_of_Nucleic_Acids:_A_Structure_for_Deoxyribose_Nucleic_Acid'), ('Nature', 'https://www.nature.com/articles/171737a0')]),
 'everest': dict(label='Hillary and Tenzing reach the top of Everest', stamp='Top of Everest', topic='journey', date=(1953, 5, 29), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/1953_British_Mount_Everest_expedition'), ('National Geographic', 'https://www.nationalgeographic.com/adventure/article/sir-edmund-hillary-tenzing-norgay-1953')]),
 'sputnik': dict(label='Sputnik 1, the first satellite, is launched', stamp='Sputnik', topic='science', date=(1957, 10, 4), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Sputnik_1'), ('NASA', 'https://www.nasa.gov/history/65-years-ago-sputnik-ushers-in-the-space-age/')]),
 'gagarin': dict(label='Gagarin is the first person in space', stamp='Gagarin in space', topic='science', date=(1961, 4, 12), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Yuri_Gagarin'), ('NASA', 'https://www.nasa.gov/history/remembering-yuri-gagarin-50-years-later/')]),
 'moon': dict(label='Apollo 11 lands on the Moon', stamp='Moon landing', topic='science', date=(1969, 7, 20), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Apollo_11'), ('NASA', 'https://www.nasa.gov/learning-resources/for-kids-and-students/what-was-the-apollo-program-grades-k-4/')]),
 'star-wars': dict(label='Star Wars opens in American cinemas', stamp='Star Wars', topic='culture', date=(1977, 5, 25), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Star_Wars_(film)'), ('History.com', 'https://www.history.com/this-day-in-history/may-25/star-wars-opens')]),
 'berlin-wall': dict(label='The Berlin Wall falls', stamp='The Wall falls', topic='empire', date=(1989, 11, 9), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall'), ('Berlin.de', 'https://www.berlin.de/en/history/8482274-8619314-opening-and-fall-of-the-berlin-wall.en.html')]),
 'hubble': dict(label='The Hubble Space Telescope is launched', stamp='Hubble', topic='science', date=(1990, 4, 24), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Hubble_Space_Telescope'), ('NASA', 'https://science.nasa.gov/mission/hubble/overview/hubble-timeline/hubble-history-timeline-full-text/')]),
 'google': dict(label='Google becomes a company', stamp='Google', topic='invention', date=(1998, 9, 4), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/History_of_Google'), ('Google', 'https://blog.google/company-news/inside-google/company-announcements/marking-20ish-years-google/')]),
 'wikipedia': dict(label='Wikipedia goes online', stamp='Wikipedia', topic='invention', date=(2001, 1, 15), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/Wikipedia'), ('timeanddate.com', 'https://www.timeanddate.com/on-this-day/january/15')]),
 'iphone': dict(label='The first iPhone goes on sale', stamp='The first iPhone', topic='invention', date=(2007, 6, 29), prec='day',
      sources=[('Wikipedia', 'https://en.wikipedia.org/wiki/IPhone_(1st_generation)'), ('Apple', 'https://www.apple.com/newsroom/2007/06/28iPhone-Premieres-This-Friday-Night-at-Apple-Retail-Stores/')]),
}
