"""Years Apart: the puzzles. Each one is a line from an older event (left) to a newer one (right),
and a third event (mid) that happened in between. The dates of all three are in events.py.

The sentence under the answer is written here with placeholders that build.py fills in from the dates,
so that every number in it is worked out, never typed:
    {LM}  years from the left event to the middle one
    {MR}  years from the middle event to the right one
    {LR}  years from the left event to the right one
A number becomes "about N" when one of its two events has an approximate date.
"claim" says what the sentence states about the middle event, and build.py checks it against the dates:
    'L'     it is closer in time to the left event       'R'  closer to the right event
    'half'  it is almost halfway (within 1 percent of the line; "almost exactly halfway" only within 0.3 percent)
    None    no such claim

New puzzles go at the END of ORDER. The order of puzzles that are live never changes, and neither does an id.
"""

PUZZLES = [
 dict(id='cleopatra-pyramid-moon', left='pyramid', mid='cleopatra', right='moon', claim='R',
      fact="Cleopatra died {LM} years after the Great Pyramid was finished, and {MR} years before the Moon landing. She lived closer in time to the Moon landing than to the pyramid's building."),
 dict(id='olympia-pyramid-moon', left='pyramid', mid='olympia', right='moon', claim=None,
      fact="When the first recorded Olympic Games were held, the Great Pyramid was already {LM} years old."),
 dict(id='columbus-pyramid-moon', left='pyramid', mid='columbus', right='moon', claim='R',
      fact="Columbus reached the Americas {LM} years after the Great Pyramid was finished, and only {MR} years before the Moon landing."),
 dict(id='marathon-pyramid-colosseum', left='pyramid', mid='marathon', right='colosseum', claim='R',
      fact="The Battle of Marathon came {LM} years after the Great Pyramid was finished, but only {MR} years before the Colosseum opened."),
 dict(id='marathon-olympia-moon', left='olympia', mid='marathon', right='moon', claim='L',
      fact="The Battle of Marathon was fought {LM} years after the first recorded Olympic Games, and {MR} years before the Moon landing."),
 dict(id='hagia-olympia-athens', left='olympia', mid='hagia', right='olympics-1896', claim='half',
      fact="The first modern Olympics came {LR} years after the first recorded ones. The Hagia Sophia was finished almost halfway between them."),
 dict(id='pompeii-caesar-moon', left='caesar', mid='pompeii', right='moon', claim='L',
      fact="Vesuvius buried Pompeii only {LM} years after Julius Caesar was killed, and {MR} years before the Moon landing."),
 dict(id='romefalls-caesar-columbus', left='caesar', mid='rome-falls', right='columbus', claim='L',
      fact="Rome's last western emperor was deposed {LM} years after Julius Caesar was killed, and {MR} years before Columbus reached the Americas."),
 dict(id='waterloo-caesar-iphone', left='caesar', mid='waterloo', right='iphone', claim='R',
      fact="The Battle of Waterloo came {LM} years after Julius Caesar was killed, but only {MR} years before the first iPhone."),
 dict(id='colosseum-marathon-constantinople', left='marathon', mid='colosseum', right='constantinople', claim='L',
      fact="The Colosseum opened {LM} years after the Battle of Marathon, and {MR} years before Constantinople fell to the Ottomans."),
 dict(id='qin-marathon-hagia', left='marathon', mid='qin', right='hagia', claim='L',
      fact="China got its first emperor {LM} years after the Battle of Marathon, and {MR} years before the Hagia Sophia was finished."),
 dict(id='pompeii-alexander-charlemagne', left='alexander', mid='pompeii', right='charlemagne', claim='L',
      fact="Vesuvius buried Pompeii {LM} years after Alexander the Great died, and {MR} years before Charlemagne was crowned."),
 dict(id='romefalls-qin-moon', left='qin', mid='rome-falls', right='moon', claim='L',
      fact="Rome's last western emperor was deposed {LM} years after China got its first emperor, and {MR} years before the Moon landing."),
 dict(id='hastings-romefalls-moon', left='rome-falls', mid='hastings', right='moon', claim='L',
      fact="The Battle of Hastings came {LM} years after Rome's last western emperor was deposed, and {MR} years before the Moon landing."),
 dict(id='principia-romefalls-moon', left='rome-falls', mid='principia', right='moon', claim='R',
      fact="Newton's Principia came out {LM} years after Rome's last western emperor was deposed, and {MR} years before the Moon landing."),
 dict(id='hastings-hagia-constantinople', left='hagia', mid='hastings', right='constantinople', claim='R',
      fact="The Battle of Hastings came {LM} years after the Hagia Sophia was finished, and {MR} years before Constantinople fell to the Ottomans."),
 dict(id='magna-charlemagne-columbus', left='charlemagne', mid='magna', right='columbus', claim='R',
      fact="Magna Carta was sealed {LM} years after Charlemagne was crowned, and {MR} years before Columbus reached the Americas."),
 dict(id='firelondon-hastings-moon', left='hastings', mid='fire-london', right='moon', claim='R',
      fact="The Great Fire of London broke out {LM} years after the Battle of Hastings, and {MR} years before the Moon landing."),
 dict(id='magna-hastings-iphone', left='hastings', mid='magna', right='iphone', claim='L',
      fact="Magna Carta was sealed only {LM} years after the Battle of Hastings, and {MR} years before the first iPhone."),
 dict(id='shakespeare-magna-iphone', left='magna', mid='shakespeare', right='iphone', claim='half',
      fact="Shakespeare died almost halfway between Magna Carta and the first iPhone: {LM} years after one and {MR} years before the other."),
 dict(id='titanic-magna-moon', left='magna', mid='titanic', right='moon', claim='R',
      fact="The Titanic sank {LM} years after Magna Carta was sealed, and only {MR} years before the Moon landing."),
 dict(id='blackdeath-genghis-constantinople', left='genghis', mid='black-death', right='constantinople', claim='R',
      fact="The Black Death reached Sicily {LM} years after Temüjin became Genghis Khan, and {MR} years before Constantinople fell."),
 dict(id='columbus-blackdeath-firelondon', left='black-death', mid='columbus', right='fire-london', claim='L',
      fact="Columbus reached the Americas {LM} years after the Black Death arrived in Sicily, and {MR} years before the Great Fire of London."),
 dict(id='wright-constantinople-moon', left='constantinople', mid='wright', right='moon', claim='R',
      fact="The Wright brothers flew {LM} years after Constantinople fell, and just {MR} years before the Moon landing."),
 dict(id='magellan-columbus-moon', left='columbus', mid='magellan', right='moon', claim='L',
      fact="The first voyage around the world ended just {LM} years after Columbus reached the Americas, and {MR} years before the Moon landing."),
 dict(id='shakespeare-columbus-moon', left='columbus', mid='shakespeare', right='moon', claim='L',
      fact="Shakespeare died {LM} years after Columbus reached the Americas, and {MR} years before the Moon landing."),
 dict(id='pennyblack-columbus-iphone', left='columbus', mid='penny-black', right='iphone', claim='R',
      fact="The Penny Black went on sale {LM} years after Columbus reached the Americas, and {MR} years before the first iPhone."),
 dict(id='cortes-gama-shakespeare', left='gama', mid='cortes', right='shakespeare', claim='L',
      fact="Cortés entered the Aztec capital {LM} years after Vasco da Gama reached India by sea, and {MR} years before Shakespeare died."),
 dict(id='galileo-copernicus-hubble', left='copernicus', mid='galileo', right='hubble', claim='L',
      fact="Galileo turned his telescope to the Moon {LM} years after Copernicus published his model, and {MR} years before Hubble was launched."),
 dict(id='principia-copernicus-sputnik', left='copernicus', mid='principia', right='sputnik', claim='L',
      fact="Newton's Principia came out {LM} years after Copernicus published his model of the universe, and {MR} years before Sputnik."),
 dict(id='railway-galileo-sputnik', left='galileo', mid='railway', right='sputnik', claim='R',
      fact="The first public passenger railway opened {LM} years after Galileo looked at the Moon, and {MR} years before Sputnik was launched."),
 dict(id='declaration-shakespeare-darwin', left='shakespeare', mid='declaration', right='darwin', claim='R',
      fact="The Declaration of Independence came {LM} years after Shakespeare died, and {MR} years before Darwin's On the Origin of Species."),
 dict(id='bastille-tokugawa-meiji', left='tokugawa', mid='bastille', right='meiji', claim='R',
      fact="The Bastille was stormed {LM} years after Tokugawa Ieyasu became shogun, and {MR} years before Japan's emperor was restored to power."),
 dict(id='bastille-firelondon-titanic', left='fire-london', mid='bastille', right='titanic', claim='half',
      fact="The storming of the Bastille falls almost exactly halfway between the Great Fire of London and the Titanic: {LM} years after one, {MR} before the other."),
 dict(id='pennyblack-declaration-moon', left='declaration', mid='penny-black', right='moon', claim='L',
      fact="The Penny Black went on sale {LM} years after the Declaration of Independence, and {MR} years before the Moon landing."),
 dict(id='firstfleet-magellan-moon', left='magellan', mid='first-fleet', right='moon', claim='R',
      fact="The First Fleet arrived at Sydney Cove {LM} years after the first voyage around the world ended, and {MR} years before the Moon landing."),
 dict(id='waterloo-bastille-iphone', left='bastille', mid='waterloo', right='iphone', claim='L',
      fact="The Battle of Waterloo came just {LM} years after the storming of the Bastille, and {MR} years before the first iPhone."),
 dict(id='rosetta-columbus-tutankhamun', left='columbus', mid='rosetta', right='tutankhamun', claim='R',
      fact="The Rosetta Stone was found {LM} years after Columbus reached the Americas, and {MR} years before the steps to Tutankhamun's tomb."),
 dict(id='nintendo-waterloo-moon', left='waterloo', mid='nintendo', right='moon', claim=None,
      fact="Nintendo began in 1889, making playing cards: {LM} years after the Battle of Waterloo, and {MR} years before the Moon landing."),
 dict(id='eiffel-waterloo-ww2', left='waterloo', mid='eiffel', right='ww2-end', claim='R',
      fact="The Eiffel Tower was completed {LM} years after the Battle of Waterloo, and {MR} years before the Second World War ended."),
 dict(id='telephone-railway-moon', left='railway', mid='telephone', right='moon', claim='L',
      fact="Bell was granted the telephone patent {LM} years after the first public passenger railway opened, and {MR} years before the Moon landing."),
 dict(id='darwin-principia-moon', left='principia', mid='darwin', right='moon', claim='R',
      fact="Darwin's On the Origin of Species came out {LM} years after Newton's Principia, and {MR} years before the Moon landing."),
 dict(id='suez-bastille-ww2', left='bastille', mid='suez', right='ww2-end', claim='R',
      fact="The Suez Canal opened {LM} years after the storming of the Bastille, and {MR} years before the Second World War ended."),
 dict(id='meiji-railway-india', left='railway', mid='meiji', right='india', claim='L',
      fact="Japan's emperor was restored to power {LM} years after the first public passenger railway opened, and {MR} years before India became independent."),
 dict(id='panama-suez-moon', left='suez', mid='panama', right='moon', claim='L',
      fact="The Panama Canal opened {LM} years after the Suez Canal, and {MR} years before the Moon landing."),
 dict(id='moon-telephone-iphone', left='telephone', mid='moon', right='iphone', claim='R',
      fact="The Moon landing came {LM} years after Bell's telephone patent, and only {MR} years before the first iPhone."),
 dict(id='worldcup-athens-moon', left='olympics-1896', mid='world-cup', right='moon', claim='L',
      fact="The first football World Cup kicked off {LM} years after the first modern Olympics, and {MR} years before the Moon landing."),
 dict(id='titanic-wright-moon', left='wright', mid='titanic', right='moon', claim=None,
      fact="The Titanic sank only {LM} years after the Wright brothers' first powered flight. Just {LR} years separate that flight from the Moon landing."),
 dict(id='sputnik-wright-iphone', left='wright', mid='sputnik', right='iphone', claim='R',
      fact="Sputnik was launched {LM} years after the Wright brothers' first powered flight, and {MR} years before the first iPhone."),
 dict(id='everest-titanic-moon', left='titanic', mid='everest', right='moon', claim='R',
      fact="Hillary and Tenzing reached the top of Everest {LM} years after the Titanic sank, and {MR} years before the Moon landing."),
 dict(id='dna-tutankhamun-moon', left='tutankhamun', mid='dna', right='moon', claim='R',
      fact="The double helix of DNA was published {LM} years after the steps to Tutankhamun's tomb were found, and {MR} years before the Moon landing."),
 dict(id='penicillin-titanic-moon', left='titanic', mid='penicillin', right='moon', claim='L',
      fact="Fleming discovered penicillin {LM} years after the Titanic sank, and {MR} years before the Moon landing."),
 dict(id='moon-ww2-berlinwall', left='ww2-end', mid='moon', right='berlin-wall', claim='R',
      fact="The Moon landing came {LM} years after the Second World War ended, and {MR} years before the Berlin Wall fell."),
 dict(id='eastindia-gama-india', left='gama', mid='east-india', right='india', claim='L',
      fact="The East India Company got its charter {LM} years after Vasco da Gama reached India by sea, and {MR} years before India became independent."),
 dict(id='berlinwall-sputnik-iphone', left='sputnik', mid='berlin-wall', right='iphone', claim='R',
      fact="The Berlin Wall fell {LM} years after Sputnik was launched, and {MR} years before the first iPhone."),
 dict(id='hubble-gagarin-wikipedia', left='gagarin', mid='hubble', right='wikipedia', claim='R',
      fact="Hubble was launched {LM} years after Gagarin's flight, and {MR} years before Wikipedia went online."),
 dict(id='starwars-moon-iphone', left='moon', mid='star-wars', right='iphone', claim='L',
      fact="Star Wars came out only {LM} years after the Moon landing, and {MR} years before the first iPhone."),
 dict(id='google-berlinwall-iphone', left='berlin-wall', mid='google', right='iphone', claim='half',
      fact="Google became a company almost exactly halfway between the fall of the Berlin Wall and the first iPhone: {LM} years after one, {MR} before the other."),
 dict(id='wikipedia-moon-iphone', left='moon', mid='wikipedia', right='iphone', claim='R',
      fact="Wikipedia went online {LM} years after the Moon landing, and only {MR} years before the first iPhone."),
 dict(id='athens-waterloo-ww2', left='waterloo', mid='olympics-1896', right='ww2-end', claim='R',
      fact="The first modern Olympics opened {LM} years after the Battle of Waterloo, and {MR} years before the Second World War ended."),
 dict(id='telephone-pennyblack-titanic', left='penny-black', mid='telephone', right='titanic', claim='half',
      fact="Bell's telephone patent came almost exactly halfway between the Penny Black and the sinking of the Titanic: {LM} years after one, {MR} before the other."),
 dict(id='genghis-qin-columbus', left='qin', mid='genghis', right='columbus', claim='R',
      fact="Temüjin became Genghis Khan {LM} years after China got its first emperor, and {MR} years before Columbus reached the Americas."),
 dict(id='qin-alexander-caesar', left='alexander', mid='qin', right='caesar', claim='L',
      fact="China got its first emperor {LM} years after Alexander the Great died, and {MR} years before Julius Caesar was killed."),
 dict(id='hagia-cleopatra-constantinople', left='cleopatra', mid='hagia', right='constantinople', claim='L',
      fact="The Hagia Sophia was finished {LM} years after Cleopatra died, and {MR} years before Constantinople fell to the Ottomans."),
]

# The order of play (C). Day 1 is the first id. Written by order.py, which keeps neighbours apart
# (see the rules at its top). Never reorder ids that are live; new ids go at the end.
ORDER = ['cleopatra-pyramid-moon', 'colosseum-marathon-constantinople', 'shakespeare-magna-iphone',
         'pompeii-caesar-moon', 'google-berlinwall-iphone', 'titanic-wright-moon',
         'waterloo-caesar-iphone', 'rosetta-columbus-tutankhamun', 'nintendo-waterloo-moon',
         'hubble-gagarin-wikipedia', 'pennyblack-declaration-moon', 'bastille-firelondon-titanic',
         'wikipedia-moon-iphone', 'hagia-olympia-athens', 'moon-telephone-iphone',
         'columbus-blackdeath-firelondon', 'berlinwall-sputnik-iphone', 'suez-bastille-ww2',
         'magellan-columbus-moon', 'bastille-tokugawa-meiji', 'telephone-railway-moon',
         'athens-waterloo-ww2', 'principia-romefalls-moon', 'hagia-cleopatra-constantinople',
         'columbus-pyramid-moon', 'declaration-shakespeare-darwin', 'panama-suez-moon',
         'hastings-hagia-constantinople', 'titanic-magna-moon', 'qin-alexander-caesar',
         'wright-constantinople-moon', 'cortes-gama-shakespeare', 'firelondon-hastings-moon',
         'genghis-qin-columbus', 'galileo-copernicus-hubble', 'magna-charlemagne-columbus',
         'penicillin-titanic-moon', 'marathon-pyramid-colosseum', 'starwars-moon-iphone',
         'romefalls-caesar-columbus', 'worldcup-athens-moon', 'qin-marathon-hagia',
         'firstfleet-magellan-moon', 'meiji-railway-india', 'darwin-principia-moon',
         'eastindia-gama-india', 'moon-ww2-berlinwall', 'waterloo-bastille-iphone',
         'olympia-pyramid-moon', 'pennyblack-columbus-iphone', 'marathon-olympia-moon',
         'railway-galileo-sputnik', 'romefalls-qin-moon', 'telephone-pennyblack-titanic',
         'shakespeare-columbus-moon', 'sputnik-wright-iphone', 'hastings-romefalls-moon',
         'blackdeath-genghis-constantinople', 'pompeii-alexander-charlemagne', 'dna-tutankhamun-moon',
         'magna-hastings-iphone', 'eiffel-waterloo-ww2', 'everest-titanic-moon',
         'principia-copernicus-sputnik']
