"""Your Call: the moments added on 4 October 2026 (days 24 to 72), as written after checking.

Every moment here was checked against two websites, each opened and read. What each page said, in quotes,
is in evidence.txt next to this file. build.py appends these moments to your-call/puzzles.js in the order
of ORDER (at the end of this file). The 23 moments that were already live stay exactly as they are.

Fields (as in puzzles.js):
  id        never changes once the moment is live
  year      a number, or text for years before Christ ("480 BC")
  place     short (at most about 16 characters): the seat of government, not always the exact spot
  colour    red war and peace, violet justice and rights, teal everyday life, green money and work,
            blue borders and territory, magenta society
  pov       at most about 35 words, plain language, ends with "You are the ...", no name of the leader, no hint
  choices   three, each at most 9 words and about 45 characters
  real      which choice the real leader made (0, 1 or 2)
  who       the leader (for the record; not shown)
  short     the name on screen: starts a sentence, so a proper name with a capital letter
  did, next one or two short sentences each; every date, number and name stands in a linked source
  stamp     a few words naming the moment
  sources   two, from two different websites: (name, address)
  check     a note for Khayyam, never shown: whether the two other choices are in the record or only plausible
"""
CHECKED = '2026-10-04'   # the day the two sources of each moment were read

def M(id, year, place, colour, pov, choices, real, who, short, did, next, stamp, sources, check):
    return dict(id=id, year=year, place=place, colour=colour, pov=pov, choices=choices, real=real, who=who,
                short=short, did=did, next=next, stamp=stamp,
                sources=[{'name': n, 'url': u} for n, u in sources], checked=CHECKED, check=check)

W = 'https://en.wikipedia.org/wiki/'

MOMENTS = [
    M('480bc-salamis', '480 BC', 'Athens', 'red',
      "A huge Persian army is marching on your city. An oracle has told Athens to trust in its 'wooden walls', and the city has a large new fleet. You are an Athenian general.",
      ["Defend the city from its walls", "Leave the city and fight at sea", "Seek terms with the Persian king"], 1,
      'Themistocles', 'Themistocles',
      "Themistocles had Athens evacuated: the 'wooden walls' were its ships. In 480 BC the Greek fleet beat the Persians in the narrow strait of Salamis.",
      "Xerxes went back to Asia with part of his army. The rest was defeated the next year at Plataea.",
      'The battle of Salamis',
      [('TheCollector', 'https://www.thecollector.com/themistocles-battle-of-salamis/'), ('Wikipedia', W + 'Themistocles')],
      "Option 1 is close to the record: a small number of Athenians barricaded themselves on the Acropolis. Option 3 is plausible: some Greek cities, Argos the most notable, sided with Persia (Wikipedia, Second Persian invasion of Greece)."),

    M('49bc-rubicon', '49 BC', 'Rubicon', 'red',
      "Your war in Gaul is won. The Senate orders you to disband your army and return to Rome, losing the immunity your office gives you. You are the governor of Gaul.",
      ["Disband your army and go to Rome", "Stay in Gaul and keep negotiating", "Cross into Italy with your army"], 2,
      'Julius Caesar', 'Caesar',
      "In January 49 BC Caesar led the 13th Legion across the Rubicon into Italy. Under the law of the Republic, that was an act of war.",
      "Pompey, the consuls and much of the Senate fled Rome. The civil war that followed made Caesar dictator for life.",
      'Caesar crosses the Rubicon',
      [('National Geographic', 'https://www.nationalgeographic.com/history/history-magazine/article/julius-caesar-crossing-rubicon-rome'), ('Wikipedia', W + 'Crossing_the_Rubicon')],
      "Option 1 is what the Senate ordered (both sources). Option 2 is plausible only: neither source describes the talks."),

    M('1077-canossa', 1077, 'Canossa', 'magenta',
      "You have broken with the pope. He has excommunicated you, and your princes swear not to recognise you unless the ban is lifted within a year. You are the king of Germany.",
      ["Fight the princes who defy you", "Go to the pope and ask forgiveness", "Replace the pope with your own"], 1,
      'Henry IV', 'Henry',
      "Henry went to the castle of Canossa, where the pope was staying, and waited at the gate as a penitent for three days. On 28 January 1077 the pope absolved him.",
      "Henry soon renewed the conflict and was excommunicated again. He won a civil war, invaded Rome and replaced the pope with one of his own.",
      'Henry IV at Canossa',
      [('Catholic Encyclopedia', 'https://www.newadvent.org/cathen/03298a.htm'), ('Wikipedia', W + 'Road_to_Canossa')],
      "Options 1 and 3 both happened later: Henry fought a civil war against Duke Rudolph of Swabia and replaced Gregory with Antipope Clement III. In January 1077 they were the alternatives to submitting."),

    M('1215-magna-carta', 1215, 'Runnymede', 'violet',
      "A group of your barons has rebelled. They say you rule as you please, commit crimes and impose huge unjust penalties, and they have set out their demands. You are the king of England.",
      ["Crush the rebels by force", "Ask the pope to condemn the rebels", "Seal an agreement with the barons"], 2,
      'King John', 'John',
      "On 15 June 1215 John met the barons at Runnymede on the Thames and sealed their agreement. It became known as Magna Carta.",
      "It promised that no free man would be imprisoned without the lawful judgement of his peers. After John died in 1216, his son Henry III reissued it.",
      'King John seals Magna Carta',
      [('The National Archives', 'https://www.nationalarchives.gov.uk/explore-the-collection/explore-by-time-period/medieval/magna-carta/'), ('History.com', 'https://www.history.com/this-day-in-history/june-15/magna-carta-sealed')],
      "Options 1 and 2 are plausible only: the two sources do not describe the alternatives."),

    M('1698-beard-tax', 1698, 'Moscow', 'teal',
      "You have just returned from a great embassy abroad and want to modernise your country. Your nobles wear beards, as tradition and the Church expect. You are the tsar of Russia.",
      ["Leave the beards alone", "Ban beards outright", "Make men pay to keep a beard"], 2,
      'Peter the Great', 'Peter',
      "In 1698 Peter set up a beard tax, and men who paid it had to carry a token. He also shaved some of his guests' beards himself.",
      "Rich merchants paid up to 100 roubles a year. Many resisted, and the tax lasted until Catherine the Great repealed it in 1772.",
      'Peter taxes beards',
      [('Smithsonian Magazine', 'https://www.smithsonianmag.com/smart-news/why-tsar-peter-great-established-beard-tax-180964693/'), ('Wikipedia', W + 'Beard_tax')],
      "Option 2 is close to the record: from 1705 all Russians except monks and peasants had to shave (Russia Beyond, read too). Option 1 is plausible only."),

    M('1793-macartney', 1793, 'Beijing', 'green',
      "A British envoy asks you for more ports open to British trade, a permanent embassy in your capital and a small island off your coast for British merchants. You are the emperor of China.",
      ["Grant the British requests", "Open one more port, nothing else", "Turn down every request"], 2,
      'Qianlong Emperor', 'Qianlong',
      "Qianlong rejected all of the requests. In a letter to King George III he wrote that his empire possessed all things and had no need of foreign manufactures.",
      "The embassy went home to London without a single concession. It foreshadowed growing British pressure on China to open up to trade.",
      'China turns Britain away',
      [('Oregon State University', 'https://open.oregonstate.education/middleearlymodernages/chapter/emperor-qianlong-letter/'), ('Wikipedia', W + 'Macartney_Embassy')],
      "Options 1 and 2 are plausible only."),

    M('1812-moscow', 1812, 'Fili', 'red',
      "Napoleon has won a bloody battle at Borodino and is marching on Moscow. Your generals are split: fight again before the city, or retreat. You are the commander of the Russian army.",
      ["Fight another battle before Moscow", "Give up Moscow to save the army", "Ask Napoleon for peace terms"], 1,
      'Mikhail Kutuzov', 'Kutuzov',
      "At a council in the village of Fili on 13 September 1812, Kutuzov chose to abandon Moscow. With the loss of Moscow, he said, Russia was not lost.",
      "The French army entered Moscow but left it on 19 October. Of some 600,000 men, only a few tens of thousands escaped from Russia by December.",
      'Kutuzov gives up Moscow',
      [('Russia Beyond', 'https://www.rbth.com/history/334440-russian-military-leader-crushed-napoleon'), ('Wikipedia', W + 'Council_at_Fili')],
      "Option 1 is in the record: Bennigsen proposed to regroup and attack at once. Option 3 is plausible only."),

    M('1822-brazil', 1822, 'Rio de Janeiro', 'blue',
      "Portugal's parliament wants to return Brazil to its old colonial status. It has stripped you of your remaining powers and ordered you back to Portugal. You are the prince regent of Brazil.",
      ["Obey and sail back to Portugal", "Declare Brazil independent", "Stay on as Portugal's regent"], 1,
      'Pedro I', 'Pedro',
      "On 7 September 1822, by the Ipiranga brook, Pedro cried 'Independence or death!' and proclaimed Brazil's independence from Portugal.",
      "He was acclaimed emperor on 12 October 1822. After fighting that lasted until 1824, Portugal recognised Brazil's independence in 1825.",
      'Brazil declares independence',
      [('TheCollector', 'https://www.thecollector.com/how-brazil-won-independence-portugal/'), ('Wikipedia', W + 'Independence_of_Brazil')],
      "Option 1 is what the Portuguese parliament (the Cortes) ordered. Option 3 is close to the record: in January 1822 Pedro had refused to leave ('I will stay') while still ruling as regent."),

    M('1839-opium', 1839, 'Beijing', 'green',
      "Millions of your subjects are addicted to opium sold by British merchants. Some officials say you should tax the trade and profit from it. You are the emperor of China.",
      ["Legalise and tax the opium trade", "Ask Britain to halt the shipments", "Stop the trade and punish dealers"], 2,
      'Daoguang Emperor', 'Daoguang',
      "Daoguang decided to stop the trade and sent Lin Zexu to Canton. Lin seized about 20,000 chests from British traders and, from 3 June 1839, destroyed them.",
      "Britain used Lin's actions as a reason for war. The First Opium War lasted until 1842 and forced China to open to foreign trade.",
      'China destroys the opium',
      [('Asia Society', 'https://sites.asiasociety.org/chinawealthpower/chinas-first-drug-czar/'), ('Wikipedia', W + 'Destruction_of_opium_at_Humen')],
      "Option 1 is in the record: some officials argued that a tax on opium would profit the treasury. Option 2 is plausible only."),

    M('1848-denmark', 1848, 'Copenhagen', 'violet',
      "You became king two months ago and already face demands for a constitution. Now a mass meeting in the capital wants a new government that includes the liberals. You are the king of Denmark.",
      ["Refuse and keep absolute power", "Promise reforms in a few years", "Accept and end absolute rule"], 2,
      'Frederick VII', 'Frederick',
      "The next day Frederick accepted the demand, and with it the end of absolute rule. On 5 June 1849 Denmark gained its first free constitution.",
      "The constitution set up a parliament and made Denmark a constitutional monarchy. Frederick became one of its most beloved kings.",
      'Denmark ends absolute rule',
      [('National Museum of Denmark', 'https://en.natmus.dk/historical-knowledge/denmark/the-nation-state-1848-1915/'), ('Wikipedia', W + 'Frederick_VII_of_Denmark')],
      "Options 1 and 2 are plausible only."),

    M('1861-serfs', 1861, 'St Petersburg', 'violet',
      "Defeat in the Crimean War has shown how weak your country is. More than 20 million of your people are serfs, who are not free. You are the emperor of Russia.",
      ["Free the serfs by decree", "Ease serfdom step by step", "Keep serfdom to calm the nobles"], 0,
      'Alexander II', 'Alexander II',
      "On 3 March 1861 Alexander freed the serfs by manifesto. Better from above, he said, than to wait for it to come from below.",
      "Peasants had to pay for their land over 49 years, and in many places there was unrest. In 1881 revolutionaries assassinated Alexander.",
      'Russia frees its serfs',
      [('Smithsonian Magazine', 'https://www.smithsonianmag.com/history/before-lincoln-issued-the-emancipation-proclamation-this-russian-czar-freed-20-million-serfs-180980652/'), ('Wikipedia', W + 'Emancipation_reform_of_1861')],
      "Options 2 and 3 are plausible only."),

    M('1914-belgium', 1914, 'Brussels', 'red',
      "Germany demands free passage for its armies through your neutral country to attack France. If you agree, it promises to restore everything after the war. You are the king of the Belgians.",
      ["Let the German armies pass", "Refuse and defend the border", "Protest, but do not fight"], 1,
      'Albert I', 'Albert',
      "On 3 August 1914 Albert's government refused, calling the threat a flagrant violation of international law. The next day German troops invaded.",
      "The invasion brought Britain into the war. By November 1914 most of Belgium was under German occupation.",
      'Belgium refuses Germany',
      [('First World War.com', 'https://www.firstworldwar.com/source/belgium_germanrequest.htm'), ('Wikipedia', W + 'German_invasion_of_Belgium_(1914)')],
      "The sources name the Belgian government as the body that refused; the king was head of state and became commander-in-chief of the army. Option 1 is what Germany demanded. Option 3 is plausible only."),

    M('1921-treaty', 1921, 'London', 'blue',
      "In London, Britain offers your country self-government as the Irish Free State, with an oath to the Crown. Sign now, it says, or face 'immediate and terrible war'. You are an Irish negotiator.",
      ["Sign the treaty", "Refuse and go back to war", "Ask for time to consult Dublin"], 0,
      'Michael Collins', 'Collins',
      "Collins signed the Anglo-Irish Treaty at 2:20 in the morning on 6 December 1921. He said he might have signed his own death warrant.",
      "The Irish parliament approved it by 64 votes to 57. Collins was killed in August 1922, in an ambush by opponents of the treaty.",
      'The Anglo-Irish Treaty',
      [('The Irish Times', 'https://www.irishtimes.com/culture/heritage/anglo-irish-treaty-signatories-who-s-who-on-both-sides-1.4557268'), ('Wikipedia', W + 'Michael_Collins_(Irish_leader)')],
      "Option 2 is close to the record: opponents of the treaty fought on, and Collins was killed by anti-Treaty forces. Option 3 is plausible only."),

    M('1922-rome', 1922, 'Rome', 'magenta',
      "Thousands of armed fascists are marching on your capital and demand that their leader be made prime minister. Your government asks you to sign a state of siege. You are the king of Italy.",
      ["Sign it and let the army stop them", "Call new elections at once", "Refuse and appoint their leader"], 2,
      'Victor Emmanuel III', 'Victor Emmanuel',
      "Victor Emmanuel refused to sign the order. On 30 October 1922 he appointed Mussolini prime minister.",
      "In a speech on 3 January 1925 Mussolini took responsibility for the murder of a socialist leader. That speech is seen as the start of his dictatorship.",
      'Mussolini made prime minister',
      [('History.com', 'https://www.history.com/articles/mussolini-italy-fascism'), ('Wikipedia', W + 'March_on_Rome')],
      "Option 1 is what the prime minister, Luigi Facta, asked for. Option 2 is plausible only."),

    M('1930-salt', 1930, 'Ahmedabad', 'violet',
      "You plan civil disobedience against British rule and must choose the first target. One colleague wants a boycott of land taxes. British law forbids Indians to collect or sell salt. You are the movement's leader.",
      ["Refuse to pay the land tax", "Break the salt law in public", "Hold talks with the viceroy first"], 1,
      'Mahatma Gandhi', 'Gandhi',
      "Gandhi set out on 12 March 1930 with 78 followers and walked 240 miles to the sea at Dandi. On 6 April he broke the salt law there.",
      "Millions broke the salt laws, and more than 60,000 people were arrested. Gandhi was jailed in May, but in 1931 he negotiated with the viceroy.",
      "Gandhi's salt march",
      [('History.com', 'https://www.history.com/articles/salt-march'), ('Wikipedia', W + 'Salt_March')],
      "Option 1 is in the record: Sardar Patel suggested a land revenue boycott instead. Option 3 is plausible only."),

    M('1938-oil', 1938, 'Mexico City', 'green',
      "Foreign oil companies refuse to obey your Supreme Court, which has ordered them to raise their workers' wages and improve conditions. They say it would bankrupt them. You are the president of Mexico.",
      ["Back down to keep foreign investors", "Fine the companies until they pay", "Nationalise the oil companies"], 2,
      'Lázaro Cárdenas', 'Cárdenas',
      "On 18 March 1938 Cárdenas expropriated nearly all the foreign oil companies. Five days later, 200,000 people rallied in his support, according to the press.",
      "In June 1938 he created the state oil company, Pemex. In 1942 Mexico agreed to pay American firms about 29 million dollars in compensation.",
      'Mexico takes over its oil',
      [('US Office of the Historian', 'https://history.state.gov/milestones/1937-1945/mexican-oil'), ('Wikipedia', W + 'Mexican_oil_expropriation')],
      "Options 1 and 2 are plausible only."),

    M('1940-visas', 1940, 'Kaunas', 'violet',
      "Jewish refugees fleeing persecution crowd outside your consulate, begging for transit visas. Your ministry in Tokyo says visas only for people with papers for a final destination. You are the Japanese vice-consul in Lithuania.",
      ["Follow the ministry's rules", "Write visas for everyone who asks", "Ask Tokyo again and wait"], 1,
      'Chiune Sugihara', 'Sugihara',
      "Sugihara wrote visas by hand anyway, reportedly for 18 to 20 hours a day. From 18 July to 28 August 1940 he issued more than 2,100 of them.",
      "Many refugees crossed the Soviet Union and sailed to Kobe in Japan. In 1984 Yad Vashem named Sugihara Righteous Among the Nations.",
      "Sugihara's visas",
      [('Smithsonian Magazine', 'https://www.smithsonianmag.com/history/this-heroic-japanese-diplomat-defied-his-government-to-save-thousands-of-jewish-refugees-from-the-holocaust-180987067/'), ('Wikipedia', W + 'Chiune_Sugihara')],
      "Option 3 is close to the record: he asked Tokyo for instructions first (three times according to Wikipedia, twice according to Smithsonian). Option 1 is plausible only."),

    M('1861-sumter', 1861, 'Washington', 'red',
      "The new Confederacy expects you to give up Fort Sumter, a federal fort in the harbour of Charleston. Its garrison is running short of food and supplies. You are the president of the United States.",
      ["Withdraw the garrison", "Send warships and reinforcements", "Send food, but no troops or guns"], 2,
      'Abraham Lincoln', 'Lincoln',
      "On 6 April 1861 Lincoln announced that he would send the fort provisions only. No men, arms or ammunition would follow unless the attempt was resisted.",
      "Confederate guns opened fire at 4:30 in the morning on 12 April, and the fort surrendered the next day. Lincoln then called for 75,000 volunteers.",
      'Lincoln supplies Fort Sumter',
      [('National Park Service', 'https://www.nps.gov/articles/battle-of-fort-sumter-april-1861.htm'), ('Wikipedia', W + 'Battle_of_Fort_Sumter')],
      "Option 1 is close to the record: the Confederates had hoped the fort would be evacuated (National Park Service). Option 2 is plausible only."),

    M('1933-banks', 1933, 'Washington', 'green',
      "Thousands of banks have failed, and frightened people are rushing to withdraw their savings before more banks close. You have just taken office. You are the president of the United States.",
      ["Close every bank for a few days", "Guarantee all deposits at once", "Let the weak banks fail"], 0,
      'Franklin D. Roosevelt', 'Roosevelt',
      "On 6 March 1933 Roosevelt ordered every bank to suspend business. Congress passed an emergency banking law on 9 March, the day it was introduced.",
      "On 12 March he explained it in his first fireside chat on the radio. When the banks reopened, Americans returned 1 billion dollars to them within a week.",
      'Roosevelt closes the banks',
      [('Federal Reserve History', 'https://www.federalreservehistory.org/essays/bank-holiday-of-1933'), ('Wikipedia', W + 'Emergency_Banking_Act_of_1933')],
      "Options 2 and 3 are plausible only. Some 4,000 banks never reopened (Federal Reserve History)."),

    M('1946-nhs', 1946, 'London', 'teal',
      "Britain's hospitals are run either by charities or by local councils. Your government plans a national health service, free for everyone. You are the minister of health.",
      ["Take all hospitals into public hands", "Leave hospitals with local councils", "Pay charity hospitals to treat all"], 0,
      'Aneurin Bevan', 'Bevan',
      "Bevan's National Health Service Act of 1946 brought the charity and council hospitals into national public ownership, run by regional boards.",
      "The National Health Service started on 5 July 1948. The Act said that its services should be free of charge.",
      "Britain's free health service",
      [('UK Parliament', 'https://www.parliament.uk/about/living-heritage/transformingsociety/livinglearning/coll-9-health1/health-01/'), ('Wikipedia', W + 'National_Health_Service_Act_1946')],
      "Options 2 and 3 are plausible only: the two pages do not describe the alternatives Bevan weighed."),

    M('1956-speech', 1956, 'Moscow', 'magenta',
      "Under the late Stalin, purges led to the torture and execution of innocent party members, yet a cult still surrounds him. Your party congress ends today. You are the Soviet party leader.",
      ["Keep praising Stalin in public", "Denounce Stalin's crimes to the party", "Quietly free prisoners, say nothing"], 1,
      'Nikita Khrushchev', 'Khrushchev',
      "On 25 February 1956, at a closed session, Khrushchev condemned Stalin's purges and the cult around him. The speech was meant to stay secret.",
      "A copy reached the West and was sent to the New York Times. Protests broke out in Poland and Hungary that year, and in Hungary Soviet troops intervened.",
      'Khrushchev denounces Stalin',
      [('US Office of the Historian', 'https://history.state.gov/milestones/1953-1960/khrushchev-20th-congress'), ('Wikipedia', W + '20th_Congress_of_the_Communist_Party_of_the_Soviet_Union')],
      "Options 1 and 3 are plausible only."),

    M('1956-brasilia', 1956, 'Rio de Janeiro', 'blue',
      "Brazil's constitution of 1891 said that the capital should move from Rio de Janeiro to a place near the centre of the country. It never has. You are the new president of Brazil.",
      ["Build a new capital in the interior", "Keep the capital in Rio", "Move a few ministries inland"], 0,
      'Juscelino Kubitschek', 'Kubitschek',
      "Keeping a campaign pledge, Kubitschek began building Brasília when he took office in January 1956. It was built in 41 months and opened on 21 April 1960.",
      "Lúcio Costa planned the city and Oscar Niemeyer designed most of its public buildings. Brasília became a World Heritage Site in 1987.",
      'Brazil builds Brasília',
      [('UNESCO World Heritage Centre', 'https://whc.unesco.org/en/list/445/'), ('Wikipedia', W + 'Bras%C3%ADlia')],
      "Options 2 and 3 are plausible only."),

    M('1961-moon', 1961, 'Washington', 'magenta',
      "A Soviet cosmonaut has become the first human in space, greatly embarrassing your country. Your first astronaut made only a short flight, without orbiting the Earth. You are the president of the United States.",
      ["Leave space to the scientists", "Focus on cheaper satellites", "Set the goal of a Moon landing"], 2,
      'John F. Kennedy', 'Kennedy',
      "On 25 May 1961 Kennedy asked Congress to commit the nation to landing a man on the Moon, and returning him safely, before the decade was out.",
      "He asked for 7 to 9 billion dollars more over five years. On 20 July 1969 Neil Armstrong stepped onto the Moon.",
      'Kennedy picks the Moon',
      [('NASA', 'https://www.nasa.gov/history/the-decision-to-go-to-the-moon/'), ('JFK Library', 'https://www.jfklibrary.org/learn/about-jfk/jfk-in-history/space-program')],
      "Options 1 and 2 are plausible only."),

    M('1961-wall', 1961, 'East Berlin', 'blue',
      "About 3.5 million people, a fifth of your population, have left for the West, and in Berlin the border is still open. You are the leader of East Germany.",
      ["Seal the border with a barrier", "Raise wages to make people stay", "Let people leave freely"], 0,
      'Walter Ulbricht', 'Ulbricht',
      "On 13 August 1961 Berliners woke to find that, on Ulbricht's orders, a barbed wire fence had gone up overnight. It became the Berlin Wall.",
      "Only two months earlier he had said that no one intended to build a wall. It stood until 9 November 1989.",
      'The Berlin Wall goes up',
      [('US Office of the Historian', 'https://history.state.gov/milestones/1953-1960/berlin-crises'), ('Wikipedia', W + 'Berlin_Wall')],
      "Options 2 and 3 are plausible only."),

    M('1964-flag', 1964, 'Ottawa', 'magenta',
      "Canada flies the Union Jack, or the Red Ensign, which combines the Union Jack with Canada's shield. The country's centennial is three years away. You are the prime minister of Canada.",
      ["Keep the Red Ensign", "Hold a referendum on the flag", "Adopt a new flag of its own"], 2,
      'Lester B. Pearson', 'Pearson',
      "Pearson had promised a new flag. A committee went through a few thousand designs, and in December 1964 Parliament approved the red maple leaf.",
      "Queen Elizabeth II proclaimed it in January 1965. On 15 February it was raised over Parliament Hill for the first time.",
      "Canada's maple leaf flag",
      [('Government of Canada', 'https://www.canada.ca/en/canadian-heritage/services/flag-canada-history.html'), ('History.com', 'https://www.history.com/this-day-in-history/february-15/canada-adopts-maple-leaf-flag')],
      "Option 1 is the flag that was in use. Option 2 is plausible only."),

    M('1970-october', 1970, 'Ottawa', 'violet',
      "Separatist militants have kidnapped a British diplomat and a Quebec minister and demand prisoners freed. Quebec's premier asks you for emergency powers to arrest suspects. You are the prime minister of Canada.",
      ["Invoke wartime emergency powers", "Negotiate with the kidnappers", "Leave it to the Quebec police"], 0,
      'Pierre Trudeau', 'Trudeau',
      "On 16 October 1970 Trudeau invoked the War Measures Act, letting police arrest and detain people on suspicion alone. In all, 497 people were arrested.",
      "The next day the kidnappers announced that they had killed the minister, Pierre Laporte. The diplomat, James Cross, was freed on 3 December.",
      "Trudeau's War Measures Act",
      [('CBC Archives', 'https://www.cbc.ca/archives/just-watch-me-when-pierre-trudeau-confronted-the-october-crisis-1.4676740'), ('Wikipedia', W + 'October_Crisis')],
      "Option 2 is plausible: the kidnappers had published demands (23 prisoners freed, a plane, money). Option 3 is plausible only. In a December 1970 Gallup poll 89 percent of English-speaking and 86 percent of French-speaking Canadians supported the measure."),

    M('1973-carfree', 1973, 'The Hague', 'teal',
      "Oil-producing countries are boycotting your country because it supported Israel in the Yom Kippur War. You must cut oil use fast. You are the prime minister of the Netherlands.",
      ["Ban driving on Sundays", "Raise petrol prices sharply", "Wait for the boycott to end"], 0,
      'Joop den Uyl', 'Den Uyl',
      "Den Uyl's government banned driving on Sundays and rationed fuel. Only essential workers, doctors and emergency services were allowed to drive.",
      "On the empty motorways people cycled, rode horses and even had picnics. On television Den Uyl said things would never return to the way they were.",
      'Car-free Sundays',
      [('IamExpat', 'https://www.iamexpat.nl/expat-info/dutch-news/history-amsterdam-car-free-sundays'), ('Wikipedia', W + 'Joop_den_Uyl')],
      "Options 2 and 3 are plausible only. The second source (IamExpat, an expat news site) is weak but says what is used: the Sunday ban, who could still drive, and picnics on the motorways."),

    M('1950-schuman', 1950, 'Paris', 'green',
      "Five years after the Second World War, France must decide how to live with West Germany. Coal and steel are the most important materials for making weapons. You are the foreign minister of France.",
      ["Keep strict limits on German industry", "Pool French and German coal and steel", "Seek a military pact against Germany"], 1,
      'Robert Schuman', 'Schuman',
      "On 9 May 1950 Schuman proposed placing French and West German coal and steel production under a single authority. He had drawn up the plan with Jean Monnet.",
      "The idea was that a country without control over coal and steel could not fight a war. In 1951 six countries signed the treaty that put it into practice.",
      'Europe pools coal and steel',
      [('European Union', 'https://european-union.europa.eu/principles-countries-history/history-eu/eu-pioneers/robert-schuman_en'), ('Wikipedia', W + 'Schuman_Declaration')],
      "Options 1 and 3 are plausible only: the pages read do not describe the alternatives."),

    M('1854-japan', 1854, 'Edo', 'blue',
      "American warships have come back for an answer: they want ports for supplies and protection for shipwrecked sailors. Your lords are split down the middle. You are the head of the shogun's council.",
      ["Refuse and prepare to fight", "Open the country to trade", "Open two ports, but no trade"], 2,
      'Abe Masahiro', 'Abe',
      "Abe's envoy signed the Convention of Kanagawa on 31 March 1854. Japan opened two ports, Shimoda and Hakodate, but the treaty gave no right to trade.",
      "Abe was forced to resign in 1855. A real trade treaty with the United States followed in 1858, and in 1868 the emperor took formal control of Japan.",
      'Japan opens two ports',
      [('US Office of the Historian', 'https://history.state.gov/milestones/1830-1860/opening-to-japan'), ('Wikipedia', W + 'Abe_Masahiro')],
      "Option 1 is in the record: of 61 known replies from the lords, 19 opposed accepting the American demands and 19 favoured it. Option 2 came only with the treaty of 1858."),

    M('1977-sadat', 1977, 'Cairo', 'red',
      "Israel has occupied your country's Sinai Peninsula since 1967. In 1973 you went to war to win it back. Now you want peace, and the land. You are the president of Egypt.",
      ["Go to Jerusalem and speak to Israel", "Prepare for another war", "Wait for a peace conference"], 0,
      'Anwar Sadat', 'Sadat',
      "Sadat flew to Israel, the first Arab leader to visit officially. On 20 November 1977 he spoke to the Knesset in Jerusalem and proposed peace.",
      "Egypt and Israel signed a peace treaty in 1979, and Sadat and Begin won the Nobel Peace Prize. In 1981 Sadat was assassinated during a parade in Cairo.",
      'Sadat goes to Jerusalem',
      [('History.com', 'https://www.history.com/speeches/egypts-anwar-el-sadat-speaks-to-israeli-parliament'), ('Wikipedia', W + 'Anwar_Saddat')],
      "Options 2 and 3 are plausible only. Egypt's foreign minister resigned in protest before the visit, and Egypt was suspended from the Arab League from 1979 to 1989."),

    M('1985-nuclear-free', 1985, 'Wellington', 'red',
      "You were elected on a nuclear-free policy. Now your main ally wants to send a warship but will neither confirm nor deny that it is nuclear-capable. You are the prime minister of New Zealand.",
      ["Let the warship visit", "Refuse it entry", "Accept it, but ask for assurances"], 1,
      'David Lange', 'Lange',
      "On 4 February 1985 the government said no. Lange said the ship's arrival would be seen as a surrender, whatever the truth of its armaments.",
      "The United States ended its security guarantee to New Zealand. In 1987 a law made New Zealand's land and sea nuclear-free.",
      'A nuclear-free New Zealand',
      [('NZHistory', 'https://nzhistory.govt.nz/page/uss-buchanan-refused-entry-new-zealand'), ('Wikipedia', W + 'New_Zealand_nuclear-free_zone')],
      "Options 1 and 3 are plausible only. The stand was popular: by the end of 1985 nearly 40 towns and boroughs had declared themselves nuclear-free (NZHistory)."),

    M('1991-semipalatinsk', 1991, 'Alma-Ata', 'red',
      "From 1949 to 1989 the Soviet Union set off more than 450 nuclear explosions in your republic, and fallout affected 1.5 million people. The test site is still open. You are the president of Kazakhstan.",
      ["Close the test site for good", "Leave it to Moscow to decide", "Keep it as a bargaining chip"], 0,
      'Nursultan Nazarbayev', 'Nazarbayev',
      "On 29 August 1991, months before Kazakhstan became independent, Nazarbayev's government closed the Semipalatinsk test site.",
      "Kazakhstan went on to give up nuclear weapons entirely. The United Nations later made 29 August the International Day against Nuclear Tests.",
      'Kazakhstan ends the tests',
      [('CTBTO', 'https://www.ctbto.org/sites/default/files/Documents/Spectrum_24_page7-8.pdf'), ('Wikipedia', W + 'Semipalatinsk_Test_Site')],
      "Options 2 and 3 are plausible only. A protest movement, Nevada-Semipalatinsk, had been founded in 1989 (Wikipedia)."),

    M('1983-petrov', 1983, 'Near Moscow', 'red',
      "Three weeks after your military shot down a Korean airliner, the screen flashes 'LAUNCH': the satellites report an American missile, then four more. You are the duty officer of the Soviet early-warning centre.",
      ["Report a nuclear attack", "Wait for radar to confirm", "Report it as a false alarm"], 2,
      'Stanislav Petrov', 'Petrov',
      "Petrov reported the alert as a false alarm. He had been trained that an American attack would involve hundreds of missiles, and ground radar showed nothing.",
      "He was right: sunlight on high clouds had fooled the satellites. Petrov got no reward, and in 2013 he received the Dresden Peace Prize.",
      "Petrov's false alarm",
      [('History.com', 'https://www.history.com/articles/nuclear-attack-warning-cold-war-petrov'), ('Wikipedia', W + 'Stanislav_Petrov')],
      "Option 1 is what military protocol expected: his decision went against Soviet military protocol (Wikipedia). Option 2 is close to the record: ground radar confirmed nothing even after minutes of delay."),

    M('1957-little-rock', 1957, 'Washington', 'violet',
      "Arkansas's governor used the National Guard to keep nine Black students out of a white high school. Now a mob of 400 threatens them at the school. You are the president of the United States.",
      ["Send federal troops to the school", "Leave it to the state of Arkansas", "Ask the students to wait a year"], 0,
      'Dwight D. Eisenhower', 'Eisenhower',
      "Eisenhower put the Arkansas National Guard under federal command and sent in the army. On 25 September 1957 the nine entered the school, escorted by the 101st Airborne Division.",
      "Troops stayed all year, and in May 1958 Ernest Green became the school's first Black graduate. That September the governor closed Little Rock's high schools rather than integrate them.",
      'Troops to Little Rock',
      [('Eisenhower Library', 'https://www.eisenhowerlibrary.gov/research/online-documents/civil-rights-little-rock-school-integration-crisis'), ('History.com', 'https://www.history.com/this-day-in-history/september-25/central-high-school-integrated')],
      "Options 2 and 3 are plausible only."),

    M('1981-patco', 1981, 'Washington', 'green',
      "Almost 13,000 air traffic controllers have gone on strike for higher pay and a shorter week. Strikes by federal workers are against the law. You are the president of the United States.",
      ["Fire strikers who stay out", "Raise their pay to end it", "Let the courts deal with it"], 0,
      'Ronald Reagan', 'Reagan',
      "Reagan gave them 48 hours to return. On 5 August 1981 the government began firing the more than 11,000 who had not, and banned them from the job for life.",
      "The union lost its official status in October. Large private firms later followed his example and hired replacements for strikers.",
      'Reagan fires the controllers',
      [('History.com', 'https://www.history.com/this-day-in-history/august-5/reagan-fires-11359-air-traffic-controllers'), ('Wikipedia', W + 'Professional_Air_Traffic_Controllers_Organization_(1968)')],
      "Options 2 and 3 are plausible only. The number fired differs between the sources (History.com 11,359, Wikipedia 11,345), so the moment says 'more than 11,000'."),

    M('1994-ukraine', 1994, 'Kyiv', 'red',
      "Your new country holds the third-largest nuclear arsenal in the world, left behind by the Soviet Union. Some say you should keep it as a deterrent against Russia. You are the president of Ukraine.",
      ["Keep the weapons as a deterrent", "Give them up for security promises", "Keep a few, give up the rest"], 1,
      'Leonid Kravchuk', 'Kravchuk',
      "In January 1994 Kravchuk's Ukraine agreed to give up all its nuclear weapons, in return for economic support and security assurances from the United States and Russia.",
      "The Budapest Memorandum of 5 December 1994 confirmed the assurances. Ukraine sent its last nuclear warhead to Russia on 1 June 1996.",
      'Ukraine gives up the bomb',
      [('Arms Control Association', 'https://www.armscontrol.org/factsheets/ukraine-nuclear-weapons-and-security-assurances-glance'), ('Wikipedia', W + 'Leonid_Kravchuk')],
      "Option 1 is in the record: some felt Russia was still a threat and that Ukraine should keep the weapons as a deterrent. Option 3 is plausible only. Russia annexed Crimea in 2014, in violation of the memorandum (Wikipedia, Budapest Memorandum)."),

    M('1974-pardon', 1974, 'Washington', 'violet',
      "Your predecessor resigned a month ago over the Watergate scandal. He may face criminal charges, and the country is deeply divided. You are the president of the United States.",
      ["Pardon him after a trial", "Let the courts take their course", "Pardon him fully"], 2,
      'Gerald Ford', 'Ford',
      "On 8 September 1974 Ford gave Richard Nixon a 'full, free, and absolute' pardon for any crimes he had committed in office.",
      "His approval rating fell from 71 to 50 percent, and he narrowly lost the 1976 election. In 2001 he received the Profile in Courage Award for the pardon.",
      'Ford pardons Nixon',
      [('History.com', 'https://www.history.com/this-day-in-history/september-8/ford-pardons-nixon'), ('Wikipedia', W + 'Pardon_of_Richard_Nixon')],
      "Options 1 and 2 are plausible only. Ford's press secretary resigned in protest (Wikipedia)."),
    M('1958-guinea', 1958, 'Conakry', 'blue',
      "France is holding a referendum across the French Union on a new French constitution. Your party won all but four seats in Guinea's assembly last year. You are the leader of Guinea's largest party.",
      ["Campaign for yes, stay with France", "Let people vote without advice", "Campaign for no and independence"], 2,
      'Ahmed Sékou Touré', 'Sékou Touré',
      "Sékou Touré's party campaigned for no. On 28 September 1958 more than 95 percent of Guinea's voters rejected the constitution, and on 2 October Guinea declared independence.",
      "France withdrew completely and halted all aid. Guinea, with Touré as its first leader, turned to the Soviet Union for help.",
      'Guinea votes no',
      [('History.com', 'https://www.history.com/this-day-in-history/october-2/the-cold-war-comes-to-africa-as-guinea-gains-its-independence'), ('Wikipedia', W + '1958_Guinean_constitutional_referendum')],
      "Options 1 and 2 are plausible only."),

    M('1998-malaysia', 1998, 'Kuala Lumpur', 'green',
      "Speculators have sent your currency plunging, foreign money has fled, and your stock market has lost over three quarters of its value. The IMF has its own advice. You are the prime minister of Malaysia.",
      ["Follow the IMF's advice", "Fix the currency, control capital", "Let the currency float and wait"], 1,
      'Mahathir Mohamad', 'Mahathir',
      "Mahathir defied the IMF. In September 1998 he pegged the ringgit at 3.80 to the US dollar, banned offshore trading of it and brought in capital controls.",
      "The same month he dismissed his finance minister, Anwar Ibrahim. Malaysia recovered from the crisis faster than its Southeast Asian neighbours.",
      "Malaysia's capital controls",
      [('IMF', 'https://www.imf.org/external/np/exr/ib/2000/062300.HTM'), ('Wikipedia', W + 'Mahathir_Mohamad')],
      "Option 1 is what the IMF recommended. Option 3 is plausible only. The IMF notes that Malaysia's conditions were stronger at the outset than those of the other crisis countries."),

    M('1999-east-timor', 1999, 'Jakarta', 'blue',
      "Your country invaded East Timor in 1975 and annexed it the next year, but the United Nations has never recognised the annexation. You are the president of Indonesia.",
      ["Keep East Timor as it is", "Let East Timor vote on its future", "Offer autonomy, but no vote"], 1,
      'B. J. Habibie', 'Habibie',
      "In January 1999 Habibie announced that East Timor could vote. On 30 August 1999, 78.5 percent rejected autonomy within Indonesia.",
      "Mass violence followed the vote until an Australian-led force restored order. East Timor became independent on 20 May 2002.",
      'East Timor votes',
      [('United Nations', 'https://peacekeeping.un.org/sites/default/files/past/etimor/Untaetchrono.html'), ('Wikipedia', W + '1999_East_Timorese_independence_referendum')],
      "Option 3 is close to the record: the ballot offered special autonomy within Indonesia, which 21.5 percent accepted. Option 1 is plausible only."),

    M('1888-golden-law', 1888, 'Rio de Janeiro', 'violet',
      "Your father, the emperor, is in Europe for medical care, and you rule in his place. Children of enslaved mothers are already born free, but slavery itself goes on. You are the regent of Brazil.",
      ["Abolish slavery at once", "Free slaves gradually, with payment", "Leave it to the emperor's return"], 0,
      'Isabel, Princess Imperial', 'Isabel',
      "On 13 May 1888 Isabel signed the Golden Law, which ended slavery in Brazil completely. Brazil was the last country in the Western Hemisphere to ban it.",
      "The monarchy lost the support of the slave-owning planters. On 15 November 1889 a military coup deposed her father, and the family went into exile in Europe.",
      'Brazil ends slavery',
      [('National Geographic', 'https://www.nationalgeographic.com/history/article/their-identity-was-forged-through-resistance-inside-the-lives-of-brazils-quilombos'), ('Wikipedia', W + 'Isabel,_Princess_Imperial_of_Brazil')],
      "Option 2 is close to the record: earlier laws had moved step by step, such as the Law of Free Birth of 1871. Option 3 is plausible only. About 4.8 million enslaved Africans had been brought to Brazil (National Geographic)."),

    M('1973-embargo', 1973, 'Riyadh', 'green',
      "Egypt has gone to war with Israel, and the United States is resupplying the Israeli army. Your kingdom's oil goes to markets all over the world. You are the king of Saudi Arabia.",
      ["Keep selling oil as usual", "Cut oil sales to punish the US", "Send troops to help Egypt"], 1,
      'King Faisal', 'Faisal',
      "Faisal withdrew Saudi oil from world markets and was the main force behind the Arab oil embargo against the United States.",
      "By the end of the embargo in March 1974 the price of oil had risen from 3 dollars a barrel to nearly 12. Faisal was assassinated a year later.",
      'The Arab oil embargo',
      [('US Office of the Historian', 'https://history.state.gov/milestones/1969-1976/oil-embargo'), ('Wikipedia', W + 'Faisal_of_Saudi_Arabia')],
      "Options 1 and 3 are plausible only. The embargo was imposed by the Arab members of OPEC together; the Office of the Historian does not name Faisal, Wikipedia calls him its primary force."),

    M('1951-iran-oil', 1951, 'Tehran', 'green',
      "A British company holds the exclusive right to Iran's oil, and since 1914 the British government has owned most of it. You are a leading member of Iran's parliament.",
      ["Nationalise the oil company", "Demand a bigger share of profits", "Keep the agreement in place"], 0,
      'Mohammad Mosaddegh', 'Mosaddegh',
      "In March 1951 Mosaddegh nationalised the Anglo-Iranian Oil Company and cancelled its concession. In April parliament made him prime minister.",
      "Britain blockaded Iran's oil, and production almost stopped. In August 1953 a coup backed by the CIA overthrew him, and he died under house arrest in 1967.",
      'Iran nationalises its oil',
      [('History.com', 'https://www.history.com/this-day-in-history/august-19/cia-assisted-coup-overthrows-government-of-iran'), ('Wikipedia', W + 'Mohammad_Mosaddegh')],
      "Option 2 is close to the record: his law set aside 25 percent of net oil profits for the company's claims for compensation (Wikipedia). Option 3 is plausible only."),

    M('1999-mandela', 1999, 'Pretoria', 'magenta',
      "Your first five-year term as your country's first democratically elected president is ending. The constitution allows two terms. You are the president of South Africa.",
      ["Run for a second term", "Change the rules and stay on", "Step down after one term"], 2,
      'Nelson Mandela', 'Mandela',
      "Mandela did not seek re-election. True to his promise, he stepped down in 1999 after one term.",
      "Thabo Mbeki succeeded him on 16 June 1999. Mandela went on to work through his foundations and died in Johannesburg on 5 December 2013.",
      'Mandela steps down',
      [('Nelson Mandela Foundation', 'https://www.nelsonmandela.org/biography'), ('Wikipedia', W + 'Presidency_of_Nelson_Mandela')],
      "Options 1 and 2 are plausible only. His age was part of his decision (Wikipedia)."),

    M('1988-chile', 1988, 'Santiago', 'violet',
      "You have ruled for 15 years. In a referendum on whether you stay eight more, the No has won. A draft decree would give you emergency powers. You are the military ruler of Chile.",
      ["Accept the result", "Use emergency powers to stay", "Call a new vote next year"], 0,
      'Augusto Pinochet', 'Pinochet',
      "Pinochet reportedly considered staying, but the air force commander admitted the No had won and refused the decree outright. Without the junta's backing, Pinochet accepted the result.",
      "Patricio Aylwin won the election of December 1989 and took office on 11 March 1990. Pinochet stayed head of the army until 1998, when he was arrested in London.",
      'Chile votes No',
      [('History.com', 'https://www.history.com/articles/augusto-pinochet'), ('Wikipedia', W + '1988_Chilean_presidential_referendum')],
      "Option 2 is in the record: Pinochet reportedly considered an auto-coup, and a draft decree for emergency powers existed. Option 3 is plausible only. He accepted the result because the junta would not back him."),

    M('1893-nz-vote', 1893, 'Wellington', 'violet',
      "Parliament has passed a bill giving all women the vote, by 20 votes to 18 in the upper house. Eighteen councillors ask you to withhold your consent. You are the governor of New Zealand.",
      ["Sign it into law", "Withhold consent as asked", "Send it back to Parliament"], 0,
      'Lord Glasgow', 'Lord Glasgow',
      "On 19 September 1893 Lord Glasgow consented. The Electoral Act gave all women in New Zealand aged 21 or older the right to vote.",
      "New Zealand became the first self-governing country where women could vote in parliamentary elections. They voted for the first time on 28 November 1893.",
      'New Zealand women vote',
      [('NZHistory', 'https://nzhistory.govt.nz/politics/womens-suffrage'), ('Wikipedia', W + 'Women%27s_suffrage_in_New_Zealand')],
      "Option 2 is what 18 legislative councillors asked for. Option 3 is plausible only. The premier, Richard Seddon, had tried to defeat the bill in the upper house (Wikipedia)."),

    M('1783-washington', 1783, 'Annapolis', 'magenta',
      "You have spent eight years away from home leading the army, and last spring you put down the Newburgh conspiracy. The war is over. You are the commander in chief of the Continental Army.",
      ["Use the army to take power", "Stay on as commander in peacetime", "Resign and go home"], 2,
      'George Washington', 'Washington',
      "On 23 December 1783 Washington handed back his commission to Congress in Annapolis. The next day he was home at Mount Vernon for his first Christmas in eight years.",
      "King George III is said to have remarked that if he did that, he would be the greatest man in the world. Later Washington was unanimously elected the first president.",
      'Washington goes home',
      [('Mount Vernon', 'https://edit.mountvernon.org/digital-encyclopedia/article/resignation-of-military-commission'), ('University of Wisconsin', 'https://csac.history.wisc.edu/2025/05/13/george-washington-surrenders-his-commission-to-congress-23-december-1783/')],
      "Options 1 and 2 are plausible only. Neither source says that he was offered power."),

    M('1970-nigeria', 1970, 'Lagos', 'red',
      "After two and a half years of civil war, the breakaway state of Biafra has surrendered. More than a million people have died, many of hunger. You are the head of Nigeria's military government.",
      ["Punish Biafra's leaders and fighters", "Declare no victor and no vanquished", "Keep the east under military rule"], 1,
      'Yakubu Gowon', 'Gowon',
      "In accepting Biafra's surrender in January 1970, Gowon declared that there would be no victor and no vanquished. Most of those who had joined the uprising received an amnesty.",
      "The years after were declared a time of rehabilitation, reconstruction and reconciliation. In July 1975 Gowon was overthrown in a coup while he was abroad.",
      'No victor, no vanquished',
      [('History.com', 'https://www.history.com/this-day-in-history/July-6/civil-war-in-nigeria'), ('Wikipedia', W + 'Yakubu_Gowon')],
      "Options 1 and 3 are plausible only. History.com confirms the war, its end and the hunger; Gowon's words and the amnesty are on Wikipedia. Death tolls differ (History.com about a million civilians, Wikipedia three million Biafrans), so the pov says only more than a million."),

    M('1986-marcos', 1986, 'Manila', 'violet',
      "You were declared winner of a snap election marred by fraud. Two top officials have defected, and over two million people are protesting in Manila. You are the president of the Philippines.",
      ["Order the troops to clear them", "Hold fire and leave the country", "Hold fire and stay in the palace"], 1,
      'Ferdinand Marcos', 'Marcos',
      "'My order is not to attack,' Marcos said. Around midnight on 25 February 1986 his family left the palace by US helicopter.",
      "An American senator had advised him to 'cut and cut cleanly'. Marcos arrived in Hawaii on 26 February.",
      'People Power in Manila',
      [('Official Gazette', 'https://www.officialgazette.gov.ph/2014/02/25/edsa-elsewhere-the-1986-people-power-revolution/'), ('Wikipedia', W + 'People_Power_Revolution')],
      "Option 1 is close to the record: a general was ordered four times to fire on the rebels' camp and refused (Wikipedia). Option 3 is plausible only. The second source (the Official Gazette of the Philippines) confirms the snap election, the crowds on EDSA and Marcos leaving the palace, not his orders."),
]

# Region of every moment, for the neighbour rule in build.py (not written to puzzles.js).
REGION = {
    # the 23 live moments
    '1962-cuba': 'US', '1995-trc': 'Africa', '1963-sweden': 'Europe', '1918-brest-litovsk': 'Europe', '1936-abdication': 'Europe',
    '1803-louisiana': 'Europe', '1443-hangul': 'Asia', '1975-emergency': 'Asia', '1996-gun-laws': 'Oceania', '1948-costa-rica-army': 'Americas',
    '1991-india-reforms': 'Asia', '1965-singapore': 'Asia', '1893-wuchale': 'Africa', '1867-alaska': 'Europe', '1971-gold': 'US',
    '1975-dismissal': 'Oceania', '1992-chewing-gum': 'Asia', '1956-suez': 'Middle East', '1582-calendar': 'Europe', '1980-olympics': 'US',
    '1990-de-klerk': 'Africa', '1905-norway-king': 'Europe', '1948-berlin-airlift': 'US',
    # the new moments ("Americas" means the Americas outside the United States; Egypt counts as the Middle East)
    '480bc-salamis': 'Europe', '49bc-rubicon': 'Europe', '1077-canossa': 'Europe', '1215-magna-carta': 'Europe', '1698-beard-tax': 'Europe',
    '1793-macartney': 'Asia', '1812-moscow': 'Europe', '1822-brazil': 'Americas', '1839-opium': 'Asia', '1848-denmark': 'Europe',
    '1861-serfs': 'Europe', '1914-belgium': 'Europe', '1921-treaty': 'Europe', '1922-rome': 'Europe', '1930-salt': 'Asia',
    '1938-oil': 'Americas', '1940-visas': 'Europe', '1861-sumter': 'US', '1933-banks': 'US', '1946-nhs': 'Europe',
    '1956-speech': 'Europe', '1956-brasilia': 'Americas', '1961-moon': 'US', '1961-wall': 'Europe', '1964-flag': 'Americas',
    '1970-october': 'Americas', '1973-carfree': 'Europe', '1950-schuman': 'Europe', '1854-japan': 'Asia', '1977-sadat': 'Middle East',
    '1985-nuclear-free': 'Oceania', '1991-semipalatinsk': 'Asia', '1983-petrov': 'Europe', '1957-little-rock': 'US', '1981-patco': 'US',
    '1994-ukraine': 'Europe', '1974-pardon': 'US', '1958-guinea': 'Africa', '1998-malaysia': 'Asia', '1999-east-timor': 'Asia',
    '1888-golden-law': 'Americas', '1973-embargo': 'Middle East', '1951-iran-oil': 'Middle East', '1999-mandela': 'Africa', '1988-chile': 'Americas',
    '1893-nz-vote': 'Oceania', '1783-washington': 'US', '1970-nigeria': 'Africa', '1986-marcos': 'Asia',
}

# The order in which the new moments are played, after the 23 live ones. Only ever add at the end.
# Day 24 (26 October 2026) is the first of them.
ORDER = [
    '1698-beard-tax', '1957-little-rock', '1977-sadat', '1822-brazil', '1973-carfree',
    '1930-salt', '1783-washington', '1994-ukraine', '1970-october', '1950-schuman',
    '1986-marcos', '1961-wall', '1861-sumter', '1922-rome', '1998-malaysia',
    '1956-brasilia', '1215-magna-carta', '1981-patco', '1964-flag', '480bc-salamis',
    '1893-nz-vote', '1951-iran-oil', '1999-mandela', '1983-petrov', '1999-east-timor',
    '1988-chile', '1914-belgium', '1961-moon', '1839-opium', '1921-treaty',
    '1970-nigeria', '1861-serfs', '1938-oil', '1077-canossa', '1991-semipalatinsk',
    '1848-denmark', '1958-guinea', '1933-banks', '49bc-rubicon', '1888-golden-law',
    '1956-speech', '1854-japan', '1973-embargo', '1812-moscow', '1974-pardon',
    '1946-nhs', '1985-nuclear-free', '1793-macartney', '1940-visas',
]
